### ISSUE TITLE
Noticeable lag when loading speaker hover images

### ISSUE THREAD

**Issue by kieranmasterton** [smashingmagazine/redesign#1]
URL: https://next.smashingmagazine.com/events/san-francisco-2017/

What was I doing: hovering over speakers on the events page

What did I expect: instant switch to hover image

What did I get: noticeable lag while the image loaded 

This is pretty minor but I thought it was worth mentioning that there was a noticeable delay when hovering over the speakers, using sprites would avoid the issue.

**Comment by vitalyfriedman** [comment]
The issue has been addressed. Patched the bugfix, but we need to find a cleaner solution. On it. Thanks @kieranmasterton!

**Comment by indysigner** [comment]
I'll close this issue here for now, thank you, Kieran! :-)
