### ISSUE TITLE
Links to "become a supporter" three times

### ISSUE THREAD

**Issue by smash-it-on** [smashingmagazine/redesign#10]
So I'm on the membership page (https://next.smashingmagazine.com/member/), looking at the three options. Obviously when the options are next to each other on a larger screen resolution, this cannot be seen. But as soon as you try it on a smaller resolution, you can clearly see that the "back links" to _Become a Member_ and _Become Smashing_ should be replaced (they currently both link back to _Become a Supporter_...

Shouldn't the reader be linked back to the option s/he chose?

I'm attaching a short recording of my screen to explain my point :)

[quick-preview.zip](https://github.com/smashingmagazine/redesign/files/848742/quick-preview.zip)

**Comment by vitalyfriedman** [comment]
Yes, absolutely. Putting on the To-Do list. @smash-it-on

**Comment by indysigner** [comment]
To be continued via https://github.com/smashingmagazine/smashing-magazine/issues/516
