### ISSUE TITLE
Mixed http and https content on some articles

### ISSUE THREAD

**Issue by daprice** [smashingmagazine/redesign#100]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
On certain articles, assets are loaded from provide.smashingmagazine.com via insecure http even though the article is being accessed over https, which makes the user’s browsing less secure and causes the browser to not show a lock icon or show a warning icon in place of the lock icon.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Visit https://next.smashingmagazine.com/2016/08/using-a-static-site-generator-at-scale-lessons-learned/

**- What is the expected behavior?**
All content should be loaded via https, allowing the browser to show a lock icon for the page.

**- Please mention your operating system version and the version of your browser**
MacOS 10.12.3, Safari 10.0.3, also tested in Firefox 52

**Comment by vitalyfriedman** [comment]
Ouch — we will be looking into it, thanks @daprice!

**Comment by biilmann** [comment]
This seems to be an issue in the current site as well:

https://www.smashingmagazine.com/2016/08/using-a-static-site-generator-at-scale-lessons-learned/

I'll see if we can get these assets migrated to https URLs during the migration

**Comment by indysigner** [comment]
hi @daprice, many thanks for reporting the issue, this has been fixed in the meanwhile. Thank you!
