### ISSUE TITLE
Zooming an image with transparent background makes it unreadable

### ISSUE THREAD

**Issue by daprice** [smashingmagazine/redesign#101]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
When zooming an image that is largely transparent, it overlaps the content making it difficult to read. (this is related to #12, #19, #31 but I wasn’t sure if it was a duplicate since it’s not exactly the same issue)

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to https://next.smashingmagazine.com/2016/08/using-a-static-site-generator-at-scale-lessons-learned/
2. Zoom in on the first image (the source control diagram)

**- What is the expected behavior?**
The zoom feature should overlay a light colored background behind the image so it remains readable when it overlaps other content.

**- Please mention your operating system version and the version of your browser**
MacOS 10.12.3, Safari 10.0.3

**Comment by vitalyfriedman** [comment]
Thanks @daprice — good stuff, accepted!

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#589
