### ISSUE TITLE
Low-res thumbnail image on category page

### ISSUE THREAD

**Issue by daprice** [smashingmagazine/redesign#102]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
The featured image for the top article on some category pages is too low-res for the size it’s displayed at, making it blurry.

![screen shot 2017-03-17 at 4 03 04 pm](https://cloud.githubusercontent.com/assets/3615519/24062931/812a91bc-0b2b-11e7-909b-2398d4131ba7.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Visit https://next.smashingmagazine.com/categories/wallpapers/ where the issue is most pronounced. It also affects other category pages like [Photoshop](https://next.smashingmagazine.com/categories/photoshop/) and [Graphics](https://next.smashingmagazine.com/categories/graphics/) at large browser window sizes and high-DPI displays, but not as severely as the Wallpapers page.

**- What is the expected behavior?**
The image should be displayed at an appropriate resolution for its size, taking into account the width of the browser window and, if feasible, the user’s screen DPI.

**- Please mention your operating system version and the version of your browser**
MacOS 10.12.3, Safari 10.0.3

**Comment by vitalyfriedman** [comment]
Images have been adjusted — integrating Cloudinary's responsive images solution for a better experience. @daprice — thanks for reporting the issue!

**Comment by indysigner** [comment]
Hi @daprice, we have resolved this issue, many thanks for reporting it! And happy holidays!
