### ISSUE TITLE
"Ah, what's Membership?" link incorrect

### ISSUE THREAD

**Issue by smash-it-on** [smashingmagazine/redesign#11]
The link next to "Login" on the right, i.e. "Ah, what's Membership?" should at least link to the info on the page below. https://next.smashingmagazine.com/membership/

**Comment by vitalyfriedman** [comment]
It's supposed to be linking to the article introducing the Membership in the Magazine, but we haven't published it yet. Linking it to the Open Beta release post so far! Good catch, @smash-it-on

**Comment by indysigner** [comment]
Closed via https://github.com/smashingmagazine/smashing-magazine/issues/515
