### ISSUE TITLE
a11y: search clear button broken when using keyboard

### ISSUE THREAD

**Issue by dstorey** [smashingmagazine/redesign#110]
Steps:

* click Topics button
* type something
* tab to clear button
* try to activate it

Expected:

Clear text in search field

Actual:

Chrome: 

Nothing happens. 

Edge:

As soon as you tab to the x button some kind of auto-focus forces the input back to the search field right away. Not had time to look what is causing it.

I've also seen the page navigate when pressing enter on the X

This should also be a button element not an anchor as clearing is an action, not a navigation to a different page or location.

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#584
