### ISSUE TITLE
a11y: emoji in email subscription makes accName weird

### ISSUE THREAD

**Issue by dstorey** [smashingmagazine/redesign#114]
Steps:

navigate the page until you reach the input to sign up to the news letter then read the label of the input using screen reader (or check accName using browser dev tools such as Edge or Chrome)

Expected;

Something like "your fancy email"

Actual:

"your fancy email circus tent", which is pretty confusing.

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#585
