### ISSUE TITLE
Broken links in author profile.

### ISSUE THREAD

**Issue by bharani91** [smashingmagazine/redesign#116]
**- What is the current behavior?**
Links to author's Twitter & Github profile are not working. There is another hard-coded link called "SaraSoueidan.com".

**- If the current behavior is a bug, please provide the steps to reproduce.**
[https://next.smashingmagazine.com/author/vitaly-friedman/](https://next.smashingmagazine.com/author/vitaly-friedman/)

**- Please mention your operating system version and the version of your browser**
Chrome 56/Mac OS X El Capitan

![image](https://cloud.githubusercontent.com/assets/919147/24069431/1083163e-0bce-11e7-932d-1e069f1e24f5.png)

**Comment by vitalyfriedman** [comment]
Thanks @bharani91 — it was hardcoded. Will be fixed in the next PR.
