### ISSUE TITLE
Article hover when browsing from mobile

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#118]
**- Do you want to request a *feature* or report a *bug*?**
An enhancement.

**- What is the current behavior?**
Focusing on an article will activate the desktop hover effect. This will hide a bit of the ad above it.

![screen shot 2017-03-18 at 8 20 43 am](https://cloud.githubusercontent.com/assets/8038659/24069591/316b4e9e-0bb4-11e7-8aa9-9e95e9ea0999.jpg)

**- What is the expected behavior?**
To keep the hover for desktop and adding a simple effect for focus on mobile.

**- Please mention your operating system version and the version of your browser**
Latest Chrome on OSX.

**Comment by vitalyfriedman** [comment]
Thanks, @shadeed — bug accepted and will resolve it.

**Comment by vitalyfriedman** [comment]
That's intended behavior. Thanks @shadeed :-)
