### ISSUE TITLE
Zoom function for images does not work properly

### ISSUE THREAD

**Issue by smash-it-on** [smashingmagazine/redesign#12]
Clicking on the zoom icon on images in articles seems buggy.

Example: First image in this article: https://next.smashingmagazine.com/2017/03/world-wide-web-not-wealthy-western-web-part-2/

I'm using Firefox 52.0 and Chrome 56.0 — both react the same.

**Comment by indysigner** [comment]
To be continued via https://github.com/smashingmagazine/smashing-magazine/issues/30
