### ISSUE TITLE
Vimeo videos not working

### ISSUE THREAD

**Issue by sumnermic** [smashingmagazine/redesign#123]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Vimeo videos not opening upon click.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Please visit [example article here](https://next.smashingmagazine.com/2017/02/live-stream-awwwards-london-conference-smashingconf-videos/#15-lessons-from-15-years-in-ux) and try clicking on vimeo videos below (ones with the magnifying glass element).

**- What is the expected behavior?**
Vimeo videos to open upon click, to darken screen and centre to page.

**- Please mention your operating system version and the version of your browser**
MacOS 10.12.3, Chrome 56.0.2924.87

**Comment by vitalyfriedman** [comment]
That's very strange! Will be looking into it, thanks @sumnermic!

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#596

**Comment by indysigner** [comment]
Turns out, we intentionally used image placeholders so that we can save bandwidth for mobile users. It's the same thing with the [original article](https://www.smashingmagazine.com/2017/02/live-stream-awwwards-london-conference-smashingconf-videos/).
