### ISSUE TITLE
Issues with line-height in some articles?

### ISSUE THREAD

**Issue by vitalyfriedman** [smashingmagazine/redesign#124]
Apparently, some articles have been migrated with some issues.
Example: https://next.smashingmagazine.com/2017/02/designing-html-apis/

Look into migration issues.

![screen shot 2017-03-18 at 22 30 35](https://cloud.githubusercontent.com/assets/4688396/24076507/a45f8548-0c2a-11e7-8847-ec71fff83c0b.png)

**Comment by biilmann** [comment]
Yes, looks like there's some issues in the migration script around pre tags

**Comment by indysigner** [comment]
To be continued at https://github.com/smashingmagazine/redesign/issues/57
