### ISSUE TITLE
Remove ligatures in monospaced fonts

### ISSUE THREAD

**Issue by vitalyfriedman** [smashingmagazine/redesign#125]
Remove ligatures in monospaced fonts.

![c7pxtatv4aajwwl](https://cloud.githubusercontent.com/assets/4688396/24079775/1e03dec8-0c88-11e7-9400-c7d19dea6bcc.jpg)

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#583
