### ISSUE TITLE
Long bottom space below the title in search results

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#127]
**- Do you want to request a *feature* or report a *bug*?**
An enhancement.

**- What is the current behavior?**
If the article thumb is too long, there will be a lot of space below the article title. (I added orange rectangles to visualize the issue).

![screen shot 2017-03-19 at 4 56 44 pm](https://cloud.githubusercontent.com/assets/8038659/24081922/a055f130-0cc5-11e7-83e4-b8695f69dcc2.jpg)

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to https://next.smashingmagazine.com/search/?q=airlines
2. Check the article "40 Travel Icons To Spruce Up Your Designs".

**- What is the expected behavior?**
Bottom space should be equal for all results.

**- Please mention your operating system version and the version of your browser**
Latest Chrome on OSX.

**Comment by vitalyfriedman** [comment]
Thanks @shadeed — layout issue. Will fix!

**Comment by vitalyfriedman** [comment]
The layout issue should be fixed, @shadeed :-)
