### ISSUE TITLE
Job listing: Space between map marker and location is inconsistent

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#128]
**- Do you want to request a *feature* or report a *bug*?**
An enhancement.

**- What is the current behavior?**
The horizontal space between the map marker and location is inconsistent across other items.

![screen shot 2017-03-19 at 5 04 31 pm](https://cloud.githubusercontent.com/assets/8038659/24082208/5a91f8ce-0cca-11e7-9c91-296eaaed6c78.jpg)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Go to https://next.smashingmagazine.com/jobs/

**- What is the expected behavior?**
Space should be consistent.

**The Solution**
Since `.job-meta` element is floated to the right, any child element with `display: block` will take a width value based on the location text length. Changing that to `display: inline-block` will solve it.

```css
.job__meta {
   text-align: right;
}

.jobs__list .job__location {
   display: inline-block;
}
```

Result after adding the above CSS:

![screen shot 2017-03-19 at 5 38 21 pm](https://cloud.githubusercontent.com/assets/8038659/24082244/f5e56e8c-0cca-11e7-952b-392912d050b1.jpg)

**Comment by vitalyfriedman** [comment]
Accepting the bug! @shadeed

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#582
