### ISSUE TITLE
Jobs fixed filtering is overlapping the footer

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#129]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
Jobs fixed filter is overlapping with the footer, in the below screenshot I scrolled all the way down and the menu "Write for us, Contact us... etc" is not 100% visible.

![screen shot 2017-03-19 at 5 51 54 pm](https://cloud.githubusercontent.com/assets/8038659/24082376/3eb54018-0ccd-11e7-82d1-d950f4791183.jpg)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Go to https://next.smashingmagazine.com/jobs/ and test on iPad size (Chrome dev tools).

**- What is the expected behavior?**
Fixed bar should revert back to its initial state after the job listing is done.

**Comment by vitalyfriedman** [comment]
Good point, @shadeed — added to the to-do list. We haven't touched the Job Board yet.
