### ISSUE TITLE
Font size in "more articles on ...." (see second paragraphs)

### ISSUE THREAD

**Issue by smash-it-on** [smashingmagazine/redesign#13]
![screen shot 2017-03-16 at 8 19 06 pm](https://cloud.githubusercontent.com/assets/26403660/24014629/01bd221e-0a86-11e7-959d-a9ff499af672.png)
![screen shot 2017-03-16 at 8 20 00 pm](https://cloud.githubusercontent.com/assets/26403660/24014635/049987b6-0a86-11e7-8cc5-fa15cf714b8c.png)

**Comment by vitalyfriedman** [comment]
The issue is probably the paragraph tags that are being used in articles. Will require a bit more clean-up / attention @pukhalski @biilmann. Thanks @smash-it-on

**Comment by indysigner** [comment]
To be continued via https://github.com/smashingmagazine/smashing-magazine/issues/513
