### ISSUE TITLE
article-head z-index is higher, therefore making the content inaccessible

### ISSUE THREAD

**Issue by senadir** [smashingmagazine/redesign#131]
**- Do you want to request a *feature* or report a *bug*?**
bug
**- What is the current behavior?**
can't select text or click links of the content that is besides the title
**- If the current behavior is a bug, please provide the steps to reproduce.**
go to an article [example](https://next.smashingmagazine.com/2017/03/world-wide-web-not-wealthy-western-web-part-2/) try to click the part 1 link, fail
**- What is the expected behavior?**
link should be clickable
**- Please mention your operating system version and the version of your browser**
Windows 10, Chrome latest

possible fix, changed the z-index value of `.col--article-head` to 0, not sure if there will be side effect since it exists for a reason, probably try to change the content z-index to a higher value

**Comment by shadeed** [comment]
A possible duplicate for #22 ?

**Comment by vitalyfriedman** [comment]
A duplicate for #22 — thanks @senadir, will fix. :-)
