### ISSUE TITLE
2 of the 3 payment options don't work

### ISSUE THREAD

**Issue by mickm77** [smashingmagazine/redesign#132]
Hi, I'm trying to give you guys some money and take the $5 subscription option, but that and the $3 just take you to the back to the top of the page. The $9 option seems to work ;) 

After clicking the $5 The URL is 

https://next.smashingmagazine.com/member/signup/member 

But the $9 is

https://next.smashingmagazine.com/member/signup/smashing

**Comment by vitalyfriedman** [comment]
Indeed, @mickm77 — the Membership isn't working properly yet, so please stay tuned. Thanks for reporting the issue though!
