### ISSUE TITLE
Just no...

### ISSUE THREAD

**Issue by MadeByArne** [smashingmagazine/redesign#133]
I still hope this design is a very elaborate April Fools joke. That red is headache-inducing unbearable, and it looks like the dreaded Web 2.0 without the gloss (especially because of the menu icons). And that title font, those tilted avatars... Sorry, guys, I just had to say it...

**Comment by vitalyfriedman** [comment]
No worries, @savalina — we are happy to take any constructive criticism we can get! :-) It's not an April Fools joke though!
