### ISSUE TITLE
Honking Huge Promo Blocks Reduce Reading Comprehension 

### ISSUE THREAD

**Issue by kasnj** [smashingmagazine/redesign#134]
The promo blocks inserted into the articles first make you think the text ended abruptly, but if you do push past, you lose the thread of what you were reading by the time you find the end of the block/next section of text.

**Comment by vitalyfriedman** [comment]
Thanks for reporting the issue, @kasnj — could you please be more specific about the issue and add a screenshot/video in here?

**Comment by vitalyfriedman** [comment]
Made some refinement to visually separate the promo block from article. @kasnj
