### ISSUE TITLE
Wrong alignment for ticket input fields

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#138]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
Input fields are not aligned. (Added guides to show the issue)

<img width="700" alt="screen shot 2017-03-20 at 9 56 03 am" src="https://cloud.githubusercontent.com/assets/8038659/24091797/0b2937f0-0d53-11e7-9843-91c6a98f408d.png">

**- If the current behavior is a bug, please provide the steps to reproduce.**
Go to https://next.smashingmagazine.com/events/checkout/?event=san-francisco-2017&sku=san-francisco-2017-combo and check it out on iPad landscape mode. 

**- What is the expected behavior?**
Inputs should be aligned. 

**- Please mention your operating system version and the version of your browser**
Latest Chrome on OSX.

**Comment by vitalyfriedman** [comment]
Very good point, @shadeed — on it!

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#599
