### ISSUE TITLE
Stray semicolon on Account Details page

### ISSUE THREAD

**Issue by nilsmielke** [smashingmagazine/redesign#139]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Account Details page showing a stray semicolon at the bottom of the page, above the footer (see screenshot)
![bildschirmfoto 2017-03-20 um 09 22 50](https://cloud.githubusercontent.com/assets/8496033/24092590/78c165b6-0d4f-11e7-82a9-6b37a8c34f42.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Goto: https://next.smashingmagazine.com/member/personal-details
and scroll to the bottom.

**- What is the expected behavior?**
Not seeing a semicolon there. :D

**- Please mention your operating system version and the version of your browser**
macOS 10.12.3, Safari 10.0.3

**Comment by vitalyfriedman** [comment]
Ahhh, you are gooood @nilsmielke — thanks, will be fixed! :-)

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#593
