### ISSUE TITLE
Credit card payment for subscription boomeranged.

### ISSUE THREAD

**Issue by nilsmielke** [smashingmagazine/redesign#141]
**- Do you want to request a *feature* or report a *bug*?**
Maybe more like a question.

**- What is the current behavior?**
I opted for the Smashing! Subscription.
My credit card was charged only €1 (instead of $9) and then I was reimbursed €1 to that credit card the same day.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Paying for a subscription via credit card.

Is the subscription not live, yet?  
Then it might be a good idea to mark it in some way and/or disable payment.

**Comment by vitalyfriedman** [comment]
Subscription isn't quite ready yet — but we are on it! Will introduce some changes to make it clear. E.g. disabling "Membership" link from the navigation yet. Thanks @nilsmielke
