### ISSUE TITLE
Personal details actions are broken on small viewports

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#142]
**- Do you want to request a *feature* or report a *bug*?**
Bug & Enhancement.

**- What is the current behavior?**
Account actions looks weird on small viewport width.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Go to https://smashing-magazine.netlify.com/member/personal-details and check responsive mode (800px width).

<img width="825" alt="screen shot 2017-03-20 at 10 43 33 am" src="https://cloud.githubusercontent.com/assets/8038659/24092873/bc6428d0-0d59-11e7-9a92-647887c69c93.png">

**- What is the expected behavior?**
I suggest to stack them.

**Another thing**
The actions are left aligned for some reason. However, I think it's better to center them by removing the below CSS:

```css
.dashboard__header__actions {
   justify-content: left;
}
```

**Before**

<img width="683" alt="screen shot 2017-03-20 at 10 48 04 am" src="https://cloud.githubusercontent.com/assets/8038659/24092963/36cd1bae-0d5a-11e7-83d8-77ac6c5d26fc.png">

**After**

<img width="693" alt="screen shot 2017-03-20 at 10 48 10 am" src="https://cloud.githubusercontent.com/assets/8038659/24092973/41517390-0d5a-11e7-8ff4-cf359794a812.png">

**Comment by vitalyfriedman** [comment]
Good point @shadeed — accepting!

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#594
