### ISSUE TITLE
Back to top button visible even when at the top

### ISSUE THREAD

**Issue by prashantpalikhe** [smashingmagazine/redesign#143]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Back to top button appears even when I am already at the top.

**- What is the expected behavior?**
Only show the button when I have scrolled down the page.

**- Please mention your operating system version and the version of your browser**
macOS Sierra v10.12.3
Chrome Version 59.0.3046.0 (Official Build) canary (64-bit)

<img width="1400" alt="smashing_magazine" src="https://cloud.githubusercontent.com/assets/2657709/24095211/4e8663b6-0d5c-11e7-9235-c77aa2b677d4.png">

**Comment by vitalyfriedman** [comment]
Actually we feel it's important to consistently display the button all the time. Would love to avoid any extra interactions. But we need to change it's appearance when clicked/acive/non-active for sure! Thanks @prashantpalikhe!
