### ISSUE TITLE
In-article section links seem to be broken

### ISSUE THREAD

**Issue by beep** [smashingmagazine/redesign#145]
**- Do you want to request a *feature* or report a *bug*?**

Bug.

**- What is the current behavior?**

The URL doesn’t update, and the section headline doesn’t scroll into view.

Additionally, some of the links will show a distorted focus box:

![screen shot 2017-03-20 at 10 45 32 am](https://cloud.githubusercontent.com/assets/124493/24105282/bc4407c0-0d5a-11e7-89e3-58fbefc8208b.png)

Most show a regular focus style (but the box is very slightly misaligned):

![screen shot 2017-03-20 at 10 45 41 am](https://cloud.githubusercontent.com/assets/124493/24105327/dd2056b0-0d5a-11e7-8d05-3db62e0b6117.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Visit https://next.smashingmagazine.com/2017/03/web-development-reading-list-174/
2. Click on the link icon next to the `General` subhed.

**- What is the expected behavior?**

1. The URL should change to `https://next.smashingmagazine.com/2017/03/web-development-reading-list-174/#general`
2. The page should scroll the section hed into view.

**- Please mention your operating system version and the version of your browser**

- macOS 10.12.3 (16D32)
- Firefox Nightly 55.0a1 (2017-03-18) (64-bit)

**Comment by vitalyfriedman** [comment]
Thanks @beep — adding on the to-do list as well!
