### ISSUE TITLE
Performance improvements before going for release

### ISSUE THREAD

**Issue by vitalyfriedman** [smashingmagazine/redesign#146]
Before we go live, we need to optimize the delivery of assets. Suggestions:

1. Group CSS files — we have partials anyway, so instead of combining everything into one, let's keep all partials as they are for now and plug them all in the <head>. 

2. Step 1 will allow us to load some CSS files asynchronously (e.g. fonts.css, checkout.css, membership.css and others).

3. Lazy loading scripts like flickity.js and gravatars would help as well.

4. Use CSS containment to isolate some expensive components

5. Use prefetch, prerendering, preload etc. to load some assets faster on subsequent visits.

More stuff to do: https://www.smashingmagazine.com/2016/12/front-end-performance-checklist-2017-pdf-pages/

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#580

**Comment by addyosmani** [comment]
Any plans to make smashingmagazine/smashing-magazine OSS too? A few of us work on Chrome's preload/prefetch story and were just interested in how you're going to use those loading primitives :)

**Comment by vitalyfriedman** [comment]
@addyosmani Oh, it sounds really interesting ;-) What exactly did you have in mind? :)
