### ISSUE TITLE
Clear Shopping Cart

### ISSUE THREAD

**Issue by slabbe** [smashingmagazine/redesign#148]
**- Do you want to request a *feature* or report a *bug*?**
FEATURE

**- What is the current behavior?**
We can only clear completly the shopping cart.

**- What is the expected behavior?**
We should be able to remove a specific item instead of having to clear completly the shopping cart and then re-select the correct item we want to buy.

**Comment by vitalyfriedman** [comment]
Good point, @slabbe — adding to the list!

**Comment by vitalyfriedman** [comment]
Fixed @slabbe — thanks for reporting it! :-)
