### ISSUE TITLE
Most links in text on membership page broken

### ISSUE THREAD

**Issue by nilsmielke** [smashingmagazine/redesign#149]
**- Do you want to request a *feature* or report a *bug*?**
Maybe a bug, maybe a beta thing.

**- What is the current behavior?**
Most of the links like the ones in the screenshot attached point to "https://next.smashingmagazine.com/member/#". The one in the right column reading "Smashing Print" points to "https://next.smashingmagazine.com/author/emersonloustau".
![bildschirmfoto 2017-03-20 um 21 03 46](https://cloud.githubusercontent.com/assets/8496033/24119260/dbfd9bb6-0db0-11e7-8f06-a21f4c9deee4.png)

**- Please mention your operating system version and the version of your browser**
macOS 10.12.3, Safari 10.0.3

**Comment by vitalyfriedman** [comment]
Yes, as the Membership isn't quite ready yet, it's still a work in progress. Thanks for reporting the issue though @nilsmielke!
