### ISSUE TITLE
First talk (by Denys) is a 404 link

### ISSUE THREAD

**Issue by smash-it-on** [smashingmagazine/redesign#15]
The link to Denys' talk (underneath _Event Schedule_ please see here https://next.smashingmagazine.com/events/san-francisco-2017/) is a 404 link... It currently links to https://next.smashingmagazine.com/speaker/denys-m.-mishunov#perceived-performance

**Comment by vitalyfriedman** [comment]
Good catch! Not sure why Denys is missing from the speakers list — that's probably the issue? @indysigner

**Comment by indysigner** [comment]
Fixed, thank you! :-)
