### ISSUE TITLE
Author avatar of featured article on category page is horizontally distorted

### ISSUE THREAD

**Issue by nilsmielke** [smashingmagazine/redesign#150]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
Author avatar of featured article on category page is horizontally distorted. See screenshot.
![bildschirmfoto 2017-03-20 um 21 09 16](https://cloud.githubusercontent.com/assets/8496033/24119544/da95886e-0db1-11e7-9c7a-da0c75f9a7a3.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Visit https://next.smashingmagazine.com/categories/accessibility/ or other category page.

**- Please mention your operating system version and the version of your browser**
macOS 10.12.3, Safari 10.0.3 (you might know that by now 😁)

**Comment by vitalyfriedman** [comment]
Thanks @nilsmielke — we'll look into the issue!

**Comment by vitalyfriedman** [comment]
The issue should be solved now, dear @nilsmielke — thanks for reporting it!
