### ISSUE TITLE
Empty error message when trying to recover my password

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#153]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
I got an empty error message while trying to recover my password.

<img width="659" alt="screen shot 2017-03-21 at 6 46 59 am" src="https://cloud.githubusercontent.com/assets/8038659/24132953/f5fa3118-0e01-11e7-8399-7dbff87e0c71.png">

**- If the current behavior is a bug, please provide the steps to reproduce.**
Go to https://next.smashingmagazine.com/auth/amnesia and try to recover your password.

**- What is the expected behavior?**
1. As a user, I should get a confirmation message, that the recover link has been sent to my email.
2. If the error message is empty, it should be hidden. 

Current HTML for the message:

```html
<span class="error-msg"><undefined></undefined></span>
```

Not sure why we have `<undefined>` element. I have an idea of using something like:

```css
.error-msg:empty {
    display: none;
}
```

I checked the error messages for the login page:

```html
<span class="error-server error-msg">No user found with this email</span>
```

CSS empty will work perfectly for the last message (in case it was empty for some reason), since we don't have that `undefined` element.

**- Please mention your operating system version and the version of your browser**
Latest Chrome on OSX.

**Comment by indysigner** [comment]
This has been resolved in the meanwhile, thanks for reporting the issue, dear @shadeed!
