### ISSUE TITLE
Shopping cart icon has blue line under it in Edge

### ISSUE THREAD

**Issue by dstorey** [smashingmagazine/redesign#157]
![sketch 2](https://cloud.githubusercontent.com/assets/465069/24138135/3ea7c5d4-0dd4-11e7-8923-a603a041e9ca.png)

Remains when icon changes to an X too.

**Comment by shadeed** [comment]
![virtualbox_ms edge_21_03_2017_10_46_02](https://cloud.githubusercontent.com/assets/8038659/24138979/ed27faf4-0e22-11e7-9582-775a6548fb22.png)

This is because of the link background, adding the following should solve it:
```css
.cart-trigger {
   background: none;
}
```

**Comment by indysigner** [comment]
Hi @shadeed, confirmed, thanks so much for suggesting the fix! Will deploy a fix in a moment. Also, many thanks for reporting the issue, dear @dstorey!
