### ISSUE TITLE
Plus icons are misaligned in Edge

### ISSUE THREAD

**Issue by dstorey** [smashingmagazine/redesign#158]
Tested on Edge 15.

The plus icon for the accordions (e.g. book details page) and the Events event drop down selector thing is misaligned in Edge. It displays at the bottom of the containing box.

![sketch 3](https://cloud.githubusercontent.com/assets/465069/24138265/d0298448-0dd4-11e7-9714-0bc88c908af7.png)

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#592
