### ISSUE TITLE
2 categories in the footer are 404s

### ISSUE THREAD

**Issue by smash-it-on** [smashingmagazine/redesign#16]
Responsive Design:. https://next.smashingmagazine.com/categories/responsive-design

UI Design: https://next.smashingmagazine.com/categories/ui-design

Unsure what the issue is... both _responsive-design.yml_ as well as _ui-design.yml_ files can be found in _site/data/categories_

**Comment by annban** [comment]
https://next.smashingmagazine.com/contact/ (another footer link) also results in 404 and a 🐱,

**Comment by vitalyfriedman** [comment]
Thank you so much, dear @smash-it-on and @annban — please look into it, @indysigner @biilmann  ;-)

**Comment by indysigner** [comment]
Closing this issue here, but it still is in the works. Thanks for reporting, @annban!
