### ISSUE TITLE
Can tab to and edit category headings

### ISSUE THREAD

**Issue by dstorey** [smashingmagazine/redesign#161]
When trying to use keyboard on category pages, e.g. https://next.smashingmagazine.com/categories/accessibility/ the title of the page is in the tab rotor and is editable for some reason.  I presume this was an accident.

This is due to having contenteditable="true" on the row div.

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#573

**Comment by indysigner** [comment]
Well, that's a bit funny! :-) Thank you for reporting it, dear @dstorey!

**Comment by dstorey** [comment]
@indysigner why have some issues been moved to a private repo and not others? Makes it hard to track if/when they're fixed

**Comment by indysigner** [comment]
Understand your concern, @dstorey, we do this to keep track of our many issues in one place and where the actual code lies. Thanks for your understanding!

The issue has been fixed. ✓
