### ISSUE TITLE
Missing fonts - No text shown

### ISSUE THREAD

**Issue by alvarotrigo** [smashingmagazine/redesign#166]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Most of the text is not visible in the latest Chrome v57.0.2987.110
Removing the style `wf-loaded .h2, .wf-loaded h2` where `font-family` is defined fixes the issue.

![text](https://cloud.githubusercontent.com/assets/1706326/24149263/cbbccfd6-0e39-11e7-9854-b7309ef20d5d.JPG)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Enter into the page: https://next.smashingmagazine.com/

**- What is the expected behavior?**
Text should be visible :) 

**- Please mention your operating system version and the version of your browser**
Windows 7 Chrome v57.0.2987.110.

**Comment by indysigner** [comment]
Thanks for reporting this, @alvarotrigo! Will move & close the issue shortly.

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#576

**Comment by alvarotrigo** [comment]
@indysigner link to the issue is broken. You meant #76 ? or #57 ?

**Comment by indysigner** [comment]
Ah sorry, it's our private repository with all the code included... Thanks! :-)
