### ISSUE TITLE
Meta tags open graph & twitter card

### ISSUE THREAD

**Issue by flexbox** [smashingmagazine/redesign#167]
**- Do you want to request a *feature* or report a *bug*?**
feature

**- What is the current behavior?**
<img width="594" alt="capture d ecran 2017-03-21 a 15 03 50" src="https://cloud.githubusercontent.com/assets/360936/24150947/a2613f92-0e47-11e7-98f2-180192552621.png">

**- If the current behavior is a bug, please provide the steps to reproduce.**
Share a link on twitter

**- What is the expected behavior?**
See a picture like the smashing logo
Or a "featured picture"

**- Please mention your operating system version and the version of your browser**
All,
You can debug with this nice Google Chrome extention 
https://chrome.google.com/webstore/detail/open-graph-preview/ehaigphokkgebnmdiicabhjhddkaekgh

**Comment by indysigner** [comment]
Thanks for reporting this, @flexbox! Will move & close the issue shortly.

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#577
