### ISSUE TITLE
Incorrect Open Graph Url

### ISSUE THREAD

**Issue by mingyjongo** [smashingmagazine/redesign#168]
**- Do you want to request a *feature* or report a *bug*?**
Report a bug

**- What is the current behavior?**
Opengraph url doesn't reflect the correct url. For example:
https://next.smashingmagazine.com/2017/03/a-little-surprise-is-waiting-for-you-here--meet-the-next-smashing-magazine/
source has
`<meta property="og:url" content="https://www.smashingmagazine.com/2017/03/a-little-surprise-is-waiting-for-you-here--meet-the-next-smashing-magazine/" />`
Which leads to a 404 page. Makes it hard to share your site!

**Comment by indysigner** [comment]
Hi @mingyjongo, thanks for reporting this! I'll make sure to get this fixed ASAP.
