### ISSUE TITLE
Links on commenters' names

### ISSUE THREAD

**Issue by smash-it-on** [smashingmagazine/redesign#17]
All commenters' names in the articles' comments section have links, but they do not link anywhere. Also, when wanting to leave a comment, it only asks for the message, name and email, so just wondering why the names are shown as links? Where are they supposed to lead to? 🤔

![screen shot 2017-03-16 at 10 23 24 pm](https://cloud.githubusercontent.com/assets/26403660/24019238/9046f58a-0a97-11e7-9b12-abdec69805c0.png)

**Comment by vitalyfriedman** [comment]
Actually, initially we wanted to ask for the Twitter account (and I think we still should!) and then link to the Twitter profile. Good catch @smash-it-on!

**Comment by indysigner** [comment]
moved to https://github.com/smashingmagazine/smashing-magazine/issues/508
