### ISSUE TITLE
Set a background-color (eg. #fff)

### ISSUE THREAD

**Issue by charakterziffer** [smashingmagazine/redesign#172]
At the moment the background-color of the main section is unset.

This results in the default background color of the browser – which could be a color other than white (for example a light grey in Firefox on Ubuntu). Seeing white shadows behind the links I understand that the intented background color is white.

Please set the background-color:#fff (on the main section or the body element).

**Comment by vitalyfriedman** [comment]
Fixed — thanks for reporting the issue, @charakterziffer!
