### ISSUE TITLE
Article paragraf unclicable 

### ISSUE THREAD

**Issue by ilicmarko** [smashingmagazine/redesign#174]
**- Do you want to request a feature or report a bug?**
Bug

**- What is the current behavior?**
You can't copy the start from the article because it's hiding behind a padding

**- If the current behavior is a bug, please provide the steps to reproduce.**
Open any article, example:
https://next.smashingmagazine.com/2017/03/a-little-surprise-is-waiting-for-you-here--meet-the-next-smashing-magazine/
Try to select some starting lines on the left.

**- What is the expected behavior?**
You should be able to select (click) on the actual paragraph not the title

**- Please mention your operating system version and the version of your browser**
All modern browsers, W10

**-Additional info**
![Image](http://i.imgur.com/trbBt53.png)

It can't be fixed simple by adding `pointer-events: none;` because you wont be able to select the title. Also using something like `z-index: -1` won't work because the title will be behind so you can't select it

**Comment by ilicmarko** [comment]
## Posible solution
Replace the padding with a margin, and add a with of (100% - padding)

```
.col--article-head {
    position: relative;
    z-index: 2;
    /* padding-left: 42%; */
    margin-left: 42%;
    width: 58%;
}
```

Changing the `z-index` to `0` is not a good solution, because you won't be able to select the title by draging over the text

**Comment by ilicmarko** [comment]
Duplicate of #22 and #95

**Comment by indysigner** [comment]
We'll continue this via https://github.com/smashingmagazine/redesign/issues/22 Thanks for reporting it, @ilicmarko!
