### ISSUE TITLE
Header is overlapping the shopping cart

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#177]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**

![screen shot 2017-03-22 at 8 17 18 am](https://cloud.githubusercontent.com/assets/8038659/24184780/5152407e-0ed8-11e7-8f70-dcd0e4db7b99.jpg)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Just open the cart at the top of homepage.

I think this is a regression related to the fix of #77.

**Comment by indysigner** [comment]
Thanks for reporting this, @shadeed! Will move & close the issue shortly.

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#575
