### ISSUE TITLE
Link in first paragraph of article not clickable.

### ISSUE THREAD

**Issue by skanne** [smashingmagazine/redesign#178]
**- Do you want to request a *feature* or report a *bug*?**
*bug*

**- What is the current behavior?**
On https://next.smashingmagazine.com/2016/11/css-inheritance-cascade-global-scope-new-old-worst-best-friends/ there is a link in the first paragraph of the article: “_I'm big on **modular design**._” One can not click the link, neither can you select text in the first paragraph, because the `<div class="col col-12 col--article-head">` for the article's title is superimposed.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Just go to above mentioned page/article and try to click the link.

**- What is the expected behavior?**
Obvious, the content of the first paragraph should be reachable by mouse clicks.

**- Please mention your operating system version and the version of your browser**
macOS Sierra, Safari

**Comment by indysigner** [comment]
We'll continue this via https://github.com/smashingmagazine/redesign/issues/22 Thanks for reporting it, @skanne!
