### ISSUE TITLE
I was transported back to the 80's

### ISSUE THREAD

**Issue by Martinix** [smashingmagazine/redesign#18]
The "New" site looks like a trip back to the 80's. LOTS of icons and animations 👎 , LOTS of content in one page. In fact, it looks like the offspring of an 80's website and a children's book.

If you had some background music your new site could look like this: http://www.lingscars.com/

~Martin

**- Do you want to request a *feature* or report a *bug*?**

**- What is the current behavior?**

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your operating system version and the version of your browser**

**Comment by vitalyfriedman** [comment]
Thanks for your feedback, @Martinix — point taken. Well, let's see what we can do! But have to close the issues and #wontfix it :-)
