### ISSUE TITLE
Top section of text unselectable.

### ISSUE THREAD

**Issue by fritz-riha** [smashingmagazine/redesign#180]
See GIF
![selection-issue](https://cloud.githubusercontent.com/assets/26288243/24207882/56f54dda-0edf-11e7-83ce-4bcadccba006.gif)

**- Do you want to request a *feature* or report a *bug*?**
BUG

**- What is the current behavior?**
Cant select anything inside the first paragraph - including links.
Go here: https://getpocket.com/redirect?url=https%3A%2F%2Fnext.smashingmagazine.com%2F2017%2F03%2Fworld-wide-web-not-wealthy-western-web-part-2%2F&formCheck=ad8314db8838293bbf70e4ee7eb49b66
Try to click 'Part 1'

**- What is the expected behavior?**
Actually able to select text or click links.

**- Please mention your operating system version and the version of your browser**

**Comment by MadMikeyB** [comment]
The padding-left on the title is causing this.

Cannot click a link either - https://next.smashingmagazine.com/2013/01/off-canvas-navigation-for-responsive-website/

![screen shot 2017-03-23 at 14 14 30](https://cloud.githubusercontent.com/assets/831828/24251777/35d7e870-0fd3-11e7-8ec6-5c4e43540d08.jpg)

**Comment by indysigner** [comment]
We'll continue this via https://github.com/smashingmagazine/redesign/issues/22 Thanks for reporting it, @MadMikeyB!
