### ISSUE TITLE
Our Sponsors covering table of contents

### ISSUE THREAD

**Issue by ghost** [smashingmagazine/redesign#181]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
"Our Sponsors" sits on top of "Table of Contents"

**- If the current behavior is a bug, please provide the steps to reproduce.**
When you open the screen at a medium width, say 950px, open & close "Table of Contents" then expand your screen width to something large, say 1440px, the "Our Sponsors" block is sitting on top of the "Table of Contents"

**- What is the expected behavior?**
"Our Sponsors" should sit below the "Table of Contents"

**- Please mention your operating system version and the version of your browser**
OS X El Capitan, Firefox v52

screencast: http://amd.d.pr/IAkH

**Comment by indysigner** [comment]
Great catch, we'll be working on it! Thanks for reporting this issue, @ahite-archermalmo!

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#595
