### ISSUE TITLE
Link highlighting visual issue on Microsoft Edge

### ISSUE THREAD

**Issue by piedoom** [smashingmagazine/redesign#182]
Using MS Edge version 38.14393.0.0

To replicate, highlight a link.  This is the result.

![image](https://cloud.githubusercontent.com/assets/8846211/24209327/4f18f09a-0efc-11e7-8dc0-444b79be5d25.png)

You can see the link gets blurry and unreadable.

Guessing this is a polyfill to fix some text rendering issues with IE/Edge.

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#574

**Comment by indysigner** [comment]
Thanks for reporting it, @piedoom
