### ISSUE TITLE
Bug: Newsletter form input is not selectable and is in bad order 

### ISSUE THREAD

**Issue by sidvishnoi** [smashingmagazine/redesign#183]
Bug: Newsletter form input is not selectable and is in bad order 
Using Chrome 57 on Linux (Ubuntu) at 1920x1080
The form input is not even selected by Inspector (issue with CSS position)
![screenshot from 2017-03-23 18 16 19](https://cloud.githubusercontent.com/assets/8426945/24248473/9e7c95a2-0ff5-11e7-83e8-5c21b31ad8b1.png)

**Comment by indysigner** [comment]
To be continued at https://github.com/smashingmagazine/smashing-magazine/issues/565 (non-public repository). Thanks for reporting it, @sidvishnoi
