### ISSUE TITLE
Twitter card image error

### ISSUE THREAD

**Issue by filose** [smashingmagazine/redesign#187]
**- What is the current behavior?**
When an article is shared on Twitter, the Twitter card image is not displayed

![image](https://cloud.githubusercontent.com/assets/7524767/24290352/90f07aca-107c-11e7-9744-de49402b939f.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Copy URL from any page and paste into Tweet.

**- What is the expected behavior?**
Twitter card should display image specified in `twitter:image` meta tag content attribute.

**- Please mention your operating system version and the version of your browser**
Mac OSX 10.11.4, Google Chrome Version 56.0.2924.87

**Comment by indysigner** [comment]
Twitter does validate the articles again (I tested it today), so this should be resolved. thanks for reporting it, dear @filose!

![2017-12-21 5](https://user-images.githubusercontent.com/4224281/34259050-fd85584e-e660-11e7-98ea-eceb9c6d980d.png)
