### ISSUE TITLE
webfonts dynamic loading not working properly

### ISSUE THREAD

**Issue by michaelz** [smashingmagazine/redesign#189]
**- Do you want to request a *feature* or report a *bug*?**

A bug

**- What is the current behavior?**

The fonts are not loading correctly as per the image below. All pages are like this.
![image](https://cloud.githubusercontent.com/assets/584155/24297179/15e1a838-10a2-11e7-8bf8-5880d739dcdc.png)

However, if I remove the wf-loaded body class in the inspect tool the site is readable :

![image](https://cloud.githubusercontent.com/assets/584155/24298325/ed13955c-10a5-11e7-9bb7-1748b1f0a2fd.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**

I just opened the page.

**- What is the expected behavior?**

The webfonts should show up, or if there is a problem with them loading, local fonts should be used.

**- Please mention your operating system version and the version of your browser**

Archlinux 4.9.11-1-ARCH, tested with Firefox 54.0a2 and 52.0.1, as well as Chromium 57.0.2987.110 (64-bit).

**Comment by justincavery** [comment]
I'm also getting the same issue

http://whatsmybrowser.org/b/ES83OJD
![image](https://cloud.githubusercontent.com/assets/204469/24555054/9e361798-1627-11e7-8a32-986c663ec2ad.png)

**Comment by vitalyfriedman** [comment]
The issue has been recently resolved — thanks for reporting it, @michaelz :-)
