### ISSUE TITLE
Can't zoom image more than once in an article (unless page is refreshed again)

### ISSUE THREAD

**Issue by vinujosef** [smashingmagazine/redesign#19]
**- I want to report a bug.

**- I think there is a bug in the new website. If you open page https://next.smashingmagazine.com/2017/02/art-calligraphy-getting-started-lessons-learned/ and click on any of the images in the article to zoom it, you won't be able to zoom the same image or another image for the second time unless you refresh the page. I check it with multiple article and the issue persists. The zoom event is not getting fired after the first time.

**- To reproduce the bug
       > go to https://next.smashingmagazine.com/2017/02/art-calligraphy-getting-started-lessons-learned/ and click on any of the images in the article to zoom it. 
       > click again to un-zoom the image and try to repeat the same task (which won't work)

**- Expected to zoom and un-zoom any image any number of times.

**- I am using Window 10 + latest version of Google Chrome browser.

**Comment by vitalyfriedman** [comment]
Thanks @vinujosef — good point! Adding a new task on the to-do list! Bug indeed.

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#590
