### ISSUE TITLE
Checkout not working. Form validation fails on city field. No umlauts allowed.

### ISSUE THREAD

**Issue by jackblackCH** [smashingmagazine/redesign#190]
- Order something. i.e an ebook. https://next.smashingmagazine.com/ebooks/
- Go to checkout: https://next.smashingmagazine.com/checkout/
- If u fill out the form and use german umlauts in the city field, the validation fails:
  - Test: Zürich, Brüssel, München ...

browser: chrome ( 57.0.2987.98 )
os: macosSierra (10.12.3)

Solution: Adapt the regex in the city field .

**Comment by vitalyfriedman** [comment]
Oh, good catch @jackblackCH — thank you! Assigning to fix!

**Comment by vitalyfriedman** [comment]
The issue has been resolved, @jackblackCH — thanks for reporting it! @pukhalski
