### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by afaolek** [smashingmagazine/redesign#194]
A bug? A CSS issue?
It's in the image

I'm on Firefox 51.0.1 (32-bit) on Windows 10 (64-bit)

![screenshot-next smashingmagazine com](https://cloud.githubusercontent.com/assets/699191/24482820/0065f9ac-14ec-11e7-963a-8d27180aaea8.png)

**Comment by vitalyfriedman** [comment]
Fixing — there was a migration issue! Thanks for reporting the issue @afaolek!
