### ISSUE TITLE
View more button is overlapping the article thumb

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#195]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
<img width="570" alt="screen shot 2017-03-31 at 9 26 24 pm" src="https://cloud.githubusercontent.com/assets/8038659/24563801/5a0bc0b4-1658-11e7-961b-bb482d2fe3da.png">

Also on smaller viewports (added opacity to show the issue):

<img width="1180" alt="screen shot 2017-03-31 at 9 26 03 pm" src="https://cloud.githubusercontent.com/assets/8038659/24563835/78afc92a-1658-11e7-97d9-cab30a25c955.png">

**- If the current behavior is a bug, please provide the steps to reproduce.**
Check the jobs in this article: https://next.smashingmagazine.com/2017/03/a-little-surprise-is-waiting-for-you-here--meet-the-next-smashing-magazine/

**- What is the expected behavior?**
Jobs button should not overlap with the content below it.

**- Please mention your operating system version and the version of your browser**
Latest Chrome on OSX.

**Comment by indysigner** [comment]
This has been fixed in the meanwhile. :-)
