### ISSUE TITLE
Navigation on mobile is not hidden

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#196]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
Mobile navigation vertical space is there (reserved) but all items has `opacity: 0`.

![screen shot 2017-03-31 at 9 29 46 pm](https://cloud.githubusercontent.com/assets/8038659/24564103/6e4175aa-1659-11e7-8236-134733c25fef.jpg)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Check on mobile

**Comment by vitalyfriedman** [comment]
Should be resolved now. Thanks for reporting it @shadeed
