### ISSUE TITLE
Newsletter title is not looking good on mobile

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#197]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
![screen shot 2017-03-31 at 9 33 25 pm](https://cloud.githubusercontent.com/assets/8038659/24564252/f4d7fbe8-1659-11e7-9ab2-5bccfe0bdb10.jpg)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Check this article on mobile: https://next.smashingmagazine.com/2017/03/a-little-surprise-is-waiting-for-you-here--meet-the-next-smashing-magazine/

**- What is the expected behavior?**
![screen shot 2017-03-31 at 9 37 01 pm](https://cloud.githubusercontent.com/assets/8038659/24564357/41c8d1d4-165a-11e7-9a84-b596b8d729da.jpg)

^ or maybe to make the illustration take a full line or something.

**UX Point**

To reach the actual content of the article, I need to scroll through the following:
- Title
- Author
- Summary + Table of contents
- Newsletter
- Jobs

I think it's better to move them below the content.

**Comment by indysigner** [comment]
We've refined this NL panel in the meanwhile, thanks for reporting this!
