### ISSUE TITLE
Long URLs are cropped on mobile

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#198]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
Notice how the URL "next.smashingmagazine.com" is cropped.
![screen shot 2017-03-31 at 9 41 19 pm](https://cloud.githubusercontent.com/assets/8038659/24564546/e5de7404-165a-11e7-8fb6-a10795eac82a.jpg)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Check the paragraph in the screenshot on mobile: https://next.smashingmagazine.com/2017/03/a-little-surprise-is-waiting-for-you-here--meet-the-next-smashing-magazine/

**- What is the expected behavior?**
URL should wrap, similar to the following:
![screen shot 2017-03-31 at 9 42 45 pm](https://cloud.githubusercontent.com/assets/8038659/24564592/0cff5134-165b-11e7-8fd5-cca8b032cb3c.jpg)

^ I used `word-break: break-all` in the above screenshots. [this](https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/) article is good for implementing a cross browser solution.

**Comment by indysigner** [comment]
This is a great suggestion, will add `word-break: break-word;` which seems to be a bit more sensitive than using `break-all`. Thank you, dear @shadeed!
