### ISSUE TITLE
Image alt attribute for job listing logos

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#199]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
VoiceOver read the job item as the following:
![screen shot 2017-04-01 at 9 36 17 am](https://cloud.githubusercontent.com/assets/8038659/24576147/15bef34c-16bf-11e7-8f69-72ab5f99a803.jpg)

Notice that the img src is read.

**- If the current behavior is a bug, please provide the steps to reproduce.**
https://next.smashingmagazine.com/jobs/

**- What is the expected behavior?**
I suggest to:
- Keep the alt empty `alt=""`
- or add a descriptive text

**Comment by indysigner** [comment]
Hi @shadeed, this issue has been fixed, thank you!
