### ISSUE TITLE
Bug with "Check what's in it for you" button on Memberships

### ISSUE THREAD

**Issue by kieranmasterton** [smashingmagazine/redesign#2]
URL: https://next.smashingmagazine.com/member/

What was I doing: browsing the members page

What did I expect: when I clicked the "Check what's in it for you" button the page would scroll to the correct section below.

What did I get: I was directed to the following URL where no page content is displayed - https://next.smashingmagazine.com/member/#choose-your-option

**Comment by vitalyfriedman** [comment]
Should be working now, @kieranmasterton! :-)
