### ISSUE TITLE
Image size of camera icon different in different browser

### ISSUE THREAD

**Issue by vinujosef** [smashingmagazine/redesign#20]
**- I want to report a bug

**- Given below is the screenshot from Google Chrome latest version
![image](https://cloud.githubusercontent.com/assets/15977266/24022236/89b00302-0aa5-11e7-9931-8c15d70f6ece.png)

Given below is the screenshot from Microsoft Edge 38.14393.0.0

![image](https://cloud.githubusercontent.com/assets/15977266/24022263/b4eb630e-0aa5-11e7-832e-4a83124b8601.png)

The grey image of camera (used to indicate its a photo in Microsoft Edge is bigger than the normal size it should be).

**- To see the bug, just open any of the articles in Microsoft Edge and see any photos in that article

**- Operating system is Windows 10 + Microsoft Edge 38.14393.0.0 as browser

**Comment by vitalyfriedman** [comment]
Ouch! Will look into it @vinujosef — thanks!

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#591
