### ISSUE TITLE
Content is not refreshing

### ISSUE THREAD

**Issue by WaleedSaed** [smashingmagazine/redesign#200]
**- Do you want to request a *feature* or report a *bug*?**
 Bug
**- What is the current behavior?**
Content is the same, lastest article 16 days ago
**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**
Up-to-date content
**- Please mention your operating system version and the version of your browser**
Windows 10, Chrome latest version.

**Comment by vitalyfriedman** [comment]
We are updating the content every 3 weeks — currently working on fixing the latest bugs. Please stay tuned @WaleedSaed :-)
