### ISSUE TITLE
Vimeo shortcode not working

### ISSUE THREAD

**Issue by thecristen** [smashingmagazine/redesign#201]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
![image](https://cloud.githubusercontent.com/assets/2136286/24630406/996f9e22-188a-11e7-8a40-d44e82b9e3f4.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Visit [https://next.smashingmagazine.com/2017/03/sketch-figma-showdown/#collaboration-features](https://next.smashingmagazine.com/2017/03/sketch-figma-showdown/#collaboration-features) and view the Vimeo video under "Collaboration Features"

**- What is the expected behavior?**
The video should render in place of the shortcode.

**- Please mention your operating system version and the version of your browser**
MacOS 10.12.3, Chrome 57.0.2987.133

**Comment by indysigner** [comment]
I've cleaned up all the markup in the meanwhile, many thanks for reporting it and please let me know in case you find any further issues. Thank you!

**Comment by indysigner** [comment]
Just resolved the broken link, many thanks for reporting it!
