### ISSUE TITLE
Incorrect spelling of 'cohesive'

### ISSUE THREAD

**Issue by barrymcgee** [smashingmagazine/redesign#202]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

'incohesive' is spelt as 'incosehive'

**- If the current behavior is a bug, please provide the steps to reproduce.**

- Go to https://next.smashingmagazine.com/2017/03/a-little-surprise-is-waiting-for-you-here--meet-the-next-smashing-magazine/#why-such-a-big-change
- Incorrect spelling is in the middle of the second paragraph

**Comment by vitalyfriedman** [comment]
Can you fix it, please @indysigner ;-)

**Comment by indysigner** [comment]
Updated at the source, will be updated on ‘next’ with the next content update from Wordpress. Thanks for reporting it!
