### ISSUE TITLE
Index: carousel navigation buttons do not animate

### ISSUE THREAD

**Issue by walshd** [smashingmagazine/redesign#205]
**- Do you want to request a *feature* or report a *bug*?**
Bug (s)

**- What is the current behavior?**
All logo style buttons animate when hovered over except for the index page carousel navigation buttons.
In Safari the carousel content is lower making the buttons not align in the middle 
<img width="1239" alt="screen shot 2017-05-21 at 20 58 35" src="https://cloud.githubusercontent.com/assets/1941346/26286953/999d3d7e-3e68-11e7-86a0-106b75d72ba9.png">

**- If the current behavior is a bug, please provide the steps to reproduce.**
visit https://next.smashingmagazine.com and scroll down to the carousel and hover over the left or right navigation button. 

simply open in safari for the second misalignment issue.

**- What is the expected behavior?**
Button to animate to fall flat and square.
This may not be a bug but a design issue but I was expecting it to animate like everything else.

In safari expected the carousel nav buttons to be aligned to the middle of the carousel content like in other browsers.

**- Please mention your operating system version and the version of your browser**
OS = OSX Siera 10.12.5 
Browser = Chrome 58.0.3029.110 ; Firefox 52.0.2 ; Firefox 53.0.3 ; Safari 10.1.1

**Comment by indysigner** [comment]
We've removed the carousel in the meanwhile (ppl didn't really use it), so that the issue has been resolved. Many thanks for reporting it!
