### ISSUE TITLE
Unable to put the smashing library ebook into cart

### ISSUE THREAD

**Issue by jackblackCH** [smashingmagazine/redesign#207]
Try to order the smashing library here: https://next.smashingmagazine.com/ebooks/
Click on the cta button. Nothing happens.

Seems to work for the other ebooks on on the page.

browser: chrome ( 57.0.2987.98 )
os: macosSierra (10.12.3)

Console output:
```
ReferenceError: OA_output is not defined
    at postLoadLater ((index):2998)
    at (index):3013
```

Solution: Don't now.

**Comment by vitalyfriedman** [comment]
The issue should be resolved now, @jackblackCH — thanks Marc!
