### ISSUE TITLE
"Check reviews" link on membership page is broken.

### ISSUE THREAD

**Issue by odeland** [smashingmagazine/redesign#208]
**- Do you want to request a *feature* or report a *bug*?**
Report a *bug*

**- What is the current behavior?**
Clicking the "read reviews" link close to the end of the membership page does nothing (except for the anchor back to the top of the page)

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to https://next.smashingmagazine.com/membership/
2. Scroll all the way down to the "Smashing Magazine Print" section.
3. In the last paragraph, the following sentence contains a link that is broken: 
> You might want to **check reviews** of previous issues first though.

**- What is the expected behavior?**
After clicking "check reviews", I should see some reviews.

**- Please mention your operating system version and the version of your browser**
Windows 8.1 and Chrome 60

**Comment by indysigner** [comment]
This issue has been resolved in the meanwhile, thanks for reporting it!
