### ISSUE TITLE
Random floating line in membership page

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#209]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
There is a random line floating in the page.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to https://staging.smashingmagazine.com/membership/
2. Resize the browser to 750px
2. Scroll to "That's What Members Say" section.

<img width="708" alt="screen shot 2017-09-23 at 8 40 11 am" src="https://user-images.githubusercontent.com/8038659/30770524-d2434c4c-a03b-11e7-8237-f04294291e10.png">

**- What is the expected behavior?**
The line shouldn't be there. 

**- What is causing the bug?**
1. The button "Uhm... Still not interested? ↓" is living outside the `.col` wrapper, this is what happen when I select the button, the whole wrapping div is selected!

<img width="1081" alt="screen shot 2017-09-23 at 8 43 07 am" src="https://user-images.githubusercontent.com/8038659/30770504-28a2ac3c-a03b-11e7-9ae9-e55a369cbf6c.png">

Moving the button inside `.col` will solve the bug.

**- Please mention your operating system version and the version of your browser**
Chrome 60, OSX.

**Comment by indysigner** [comment]
Fixed!
