### ISSUE TITLE
404 on Emerson Loustau's article "How To Make WordPress Hard For Clients To Mess Up"

### ISSUE THREAD

**Issue by annban** [smashingmagazine/redesign#21]
Meow! What happens?

When you visit https://next.smashingmagazine.com/author/emersonloustau/ and try to access 1st article from a list, it results in 404.

![screenshot 2017-03-17 00 28 15](https://cloud.githubusercontent.com/assets/1413115/24022778/a8dc192a-0aa8-11e7-932f-bd63dce10a43.png)

**Comment by vitalyfriedman** [comment]
Ouch — we will look into it, thanks @annban!

**Comment by indysigner** [comment]
Fixed, thank you @annban! :-)

https://next.smashingmagazine.com/2016/07/how-to-make-wordpress-hard-for-clients-to-mess-up/
