### ISSUE TITLE
Membership link is cropped on small sizes

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#210]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
"Membership" word is looking like "Members"

<img width="637" alt="screen shot 2017-09-23 at 9 04 57 am" src="https://user-images.githubusercontent.com/8038659/30770645-7c96fd4a-a03e-11e7-8284-ad25bca9342e.png">

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to https://staging.smashingmagazine.com/membership/
2. Resize the browser to 640px
3. Activate the navigation.

**- What is the expected behavior?**
Membership should appear without cropping.

**- Please mention your operating system version and the version of your browser**
Chrome 60, OSX

**Comment by indysigner** [comment]
Resolved!
