### ISSUE TITLE
Login form on small screens

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#211]
**- Do you want to request a *feature* or report a *bug*?**
An enhancement.

**- What is the current behavior?**
Some of the login box content is cropped, before the user activate an input. 

**- If the current behavior is a bug, please provide the steps to reproduce.**
<img width="1402" alt="screen shot 2017-09-23 at 9 19 41 am" src="https://user-images.githubusercontent.com/8038659/30770729-8e227056-a040-11e7-8714-95713de122c9.png">

On the iPad, it looks fine. However, for the iPhone 5s, it looks a bit weird.

**- What is the expected behavior?**
I believe that the rotation should be only when we have enough horizontal space. Not sure that all users will expect that activating the input, is an affordance to rotate the form.

**Comment by indysigner** [comment]
This has been resolved, as well. Thank you!
