### ISSUE TITLE
Event ticket form validation

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#215]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
Since the ticket is an SVG, adding more content inside it, will make it go outside the ticket boundaries.
![smashing-ticke](https://user-images.githubusercontent.com/8038659/30771114-8e6d1ab8-a048-11e7-8774-285bb6218d0f.gif)

Also, while the Twitter handle is optional, a green check mark will appear once submitting, which is a bit unexpected. 

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to a conference page.
2. Select the workshop option.
3. Click on "Proceed to checkout" button.

**- What is the expected behavior?**
Maybe using HTML5 validation will help.

**Comment by indysigner** [comment]
We've fixed this issue in the meanwhile, thank you dear @shadeed!
