### ISSUE TITLE
Hot topic article is breaking with long names

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#217]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
![screen shot 2017-09-23 at 10 44 06 am](https://user-images.githubusercontent.com/8038659/30771277-2e30065c-a04c-11e7-8e75-1857b83fd0de.jpg)

I tried to search for a long name and found the above.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to home page.
2. Scroll down into "hot design" articles.

**- What is the expected behavior?**
Long name should break into a new line.

**Comment by indysigner** [comment]
Hi @shadeed, we have removed this panel so that should be no longer an issue. :-) Thanks for reporting it!
