### ISSUE TITLE
Fonts doesn't work correctly from the first load

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#219]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
The custom font is not loaded for some reason.

<img width="1439" alt="screen shot 2017-09-23 at 3 44 37 pm" src="https://user-images.githubusercontent.com/8038659/30773276-4b942a46-a076-11e7-9e8a-4577ccc723b1.png">

Notice how events and jobs subtitles are overlapped.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Clear cache.
2. Open the home page.

**- What is the expected behavior?**
<img width="1076" alt="screen shot 2017-09-23 at 3 47 40 pm" src="https://user-images.githubusercontent.com/8038659/30773279-74e2f846-a076-11e7-97cb-e5634ba0c0be.png">

Please note that the custom font works fine when I reload the page.

**- Please mention your operating system version and the version of your browser**
Chrome 60, OSX

**Update**

The font is not working in Edge 38, even If I reload the page for more than one time.

![virtualbox_ms edge_23_09_2017_15_49_53](https://user-images.githubusercontent.com/8038659/30773301-edcfc252-a076-11e7-9ac8-2d3d34a521f1.png)

**Comment by vitalyfriedman** [comment]
Dear @shadeed — could you look into this preview one more time, please?
https://deploy-preview-1958--smashing-magazine.netlify.com/

**Comment by shadeed** [comment]
Sure @vitalyfriedman, please see the below screenshot (Edge 38).

![virtualbox_ms edge_01_12_2017_10_22_02](https://user-images.githubusercontent.com/8038659/33473970-48648db6-d681-11e7-8c8e-6ce5ad27d6b5.png)

**Comment by vitalyfriedman** [comment]
The issue should be resolved now, @shadeed :-)
