### ISSUE TITLE
Unselectable Text in The Beginning of Article

### ISSUE THREAD

**Issue by smatric** [smashingmagazine/redesign#22]
`col--article-head` section has `padding-left` set to 42% and covers the top area of `article__content` which prevents users from being able to select text.

Perhaps `margin-left: 42%;` could be used instead.

This was tested in Google Chrome 57 with page width set to >= 1024px.

**Comment by dervondenbergen** [comment]
I can confirm the bug on my side.
This can be also seen in this video: https://www.youtube.com/watch?v=y3lwp2UT83U
@smatric was just faster creating the issue 😉 

Chrome 56 and also Safari 10

**Comment by vitalyfriedman** [comment]
Thanks @smatric and @dervondenbergen — on it!

**Comment by whmii** [comment]
I made a duplicate issue like a dummy 😆  but I wanted to go ahead and post the gif I made of this behavior. See below.

![moo](https://cloud.githubusercontent.com/assets/2489247/24050766/4a43acbc-0b06-11e7-84b1-53813c07217f.gif)

**Comment by vitalyfriedman** [comment]
Thank you, @whmii — we will look into it!

**Comment by vitalyfriedman** [comment]
"Possible fix, changed the z-index value of .col--article-head to 0, not sure if there will be side effect since it exists for a reason, probably try to change the content z-index to a higher value"

**Comment by ilicmarko** [comment]
@vitalyfriedman That would not fix the problem completely. Because then the paragraph will overlap part of the title 😆 

![Problem](http://i.imgur.com/2r9IBDn.png)

I wrote a solution i my report. As far as I tested it will work, because title is above the content `z-index: 2` and it won't overlay the content because of the margin.

**Comment by vitalyfriedman** [comment]
Fixed!
