### ISSUE TITLE
Numbers are looking weird in Edge

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#220]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
Numbers are looking like `<sup>` elements.

![virtualbox_ms edge_23_09_2017_15_54_44](https://user-images.githubusercontent.com/8038659/30773371-da17100c-a077-11e7-9673-bfee89d6af35.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to https://staging.smashingmagazine.com/membership/
2. Open with Microsoft Edge 38

**- What is the expected behavior?**
Numbers should be the same size as its surrounding text. Removing `font-feature-settings: "onum" 1,"frac" 1,"sups" 1,"subs" 1;` from the body will solve that issue.

**Comment by vitalyfriedman** [comment]
The issue has been resolved, @shadeed — thanks for reporting it!
