### ISSUE TITLE
Incorrect underline color for read more link

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#222]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
Read more underline is in white, while it should be in grey.

<img width="514" alt="screen shot 2017-09-23 at 7 30 50 pm" src="https://user-images.githubusercontent.com/8038659/30775061-c34dbf06-a095-11e7-81b8-60cbb0e86d15.png">

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to https://staging.smashingmagazine.com/2017/08/success-quality-of-work/
2. Scroll down to "STAYING PRODUCTIVE IN EVERYTHING YOU DO" section.

**- What is the expected behavior?**
Underline color should be in grey.

**Comment by vitalyfriedman** [comment]
Thank you so much, @shadeed — it has been resolved long time ago!

If you have some time, it'd be great if you could do another round of testing!

**Comment by shadeed** [comment]
@vitalyfriedman Sure thing! My pleasure :)
