### ISSUE TITLE
Book image is overlapping with the article content

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#223]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
Book image is overlapping with the article content.

<img width="914" alt="screen shot 2017-09-23 at 7 33 50 pm" src="https://user-images.githubusercontent.com/8038659/30775087-379b32c6-a096-11e7-8133-42dffeaa0bb5.png">

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to https://staging.smashingmagazine.com/2017/08/success-quality-of-work/
2. Resize the browser to 1024px.
3. Scroll down to the section with the book.

**- What is the expected behavior?**
The book shouldn't overlap with the content.

**Comment by indysigner** [comment]
This has been fixed, too. Thanks!
