### ISSUE TITLE
Credits list is broken on mobile

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#224]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
The list content is broken.

<img width="285" alt="screen shot 2017-09-23 at 7 42 48 pm" src="https://user-images.githubusercontent.com/8038659/30775165-6d1162b2-a097-11e7-86b2-209525e75268.png">

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to https://staging.smashingmagazine.com/about/
2. Browser with iPhone 5 size.
3. Scroll down to "Role... Cat" section.

**- What is the expected behavior?**
Content should not be broken.

**Comment by indysigner** [comment]
This also has been fixed, thank you!
