### ISSUE TITLE
Flashing red when scrolling

### ISSUE THREAD

**Issue by zanedev** [smashingmagazine/redesign#225]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
Scrolling fast seems to flash red header and footer in middle of page, it's a bit jarring on the eyes. 
See attached recording:
![kapture 2017-09-23 at 9 42 11](https://user-images.githubusercontent.com/817344/30775198-22fa6a64-a044-11e7-900f-776f97946a5c.gif)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Go to site, scroll mouse wheel from top to bottom fast and notice all the flashing that happens, sometimes in the middle of the page.

**- What is the expected behavior?**
Shouldn't flash at me while I'm scrolling.

**- Please mention your operating system version and the version of your browser**
Chrome 64bit v61.0.3163.91, macOS Sierra 10.12.6, LG widescreen monitor

**Comment by vitalyfriedman** [comment]
Good call, @zanedev — will have to investigate why it happens! Thanks for reporting it.

**Comment by zanedev** [comment]
@vitalyfriedman it dawned on me that it might be happening on my monitor an lg ultra wide only because I didn't see it later on my laptop.  Anyway if you can't reproduce it easily that might explain it

**Comment by vitalyfriedman** [comment]
Should be fixed now. :-) @zanedev
