### ISSUE TITLE
Search results list item counter is clipped

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#226]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
Search list counter is clipped on mobile.

<img width="433" alt="screen shot 2017-09-23 at 7 47 58 pm" src="https://user-images.githubusercontent.com/8038659/30775405-642f3738-a09b-11e7-8343-be67a8ef6c90.png">

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Search on mobile.
2. Check the counter for each result item.

**Browser**
Chrome 60, OSX

**Comment by indysigner** [comment]
Fixed!
