### ISSUE TITLE
Gutter width is inconsistent on mobile

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#227]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
Gutter width is inconsistent.

<img width="455" alt="screen shot 2017-09-23 at 8 34 41 pm" src="https://user-images.githubusercontent.com/8038659/30775581-325a7610-a09f-11e7-8bb2-cf2ed7230fe6.png">

And here is how it's looking with smaller screens (iPhone 5), notice the different between left and right:

<img width="311" alt="screen shot 2017-09-23 at 8 40 43 pm" src="https://user-images.githubusercontent.com/8038659/30775594-79896afa-a09f-11e7-9baf-daa6d280a1c6.png">

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to https://staging.smashingmagazine.com/membership/orders/
2. Resize the browser to 450px

**- What is the expected behavior?**
Gutters should be equal on both left and right sides. The reason is because `.container` is bigger than its containing element.
**- Please mention your operating system version and the version of your browser**

**Comment by indysigner** [comment]
We've fixed this in the meanwhile, as well. Thanks for reporting this inconsistency!
