### ISSUE TITLE
Article thumb is overriding search results title

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#229]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
Article thumb is overriding the search results item title.

<img width="618" alt="screen shot 2017-09-25 at 1 01 23 pm" src="https://user-images.githubusercontent.com/8038659/30803325-e4b3dff6-a1f1-11e7-9a7e-5e19758641e3.png">

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Search about something.
2. Resize to iPad portrait.

**- What is the expected behavior?**
Image shouldn't override the title.

**Comment by indysigner** [comment]
This also has been fixed in the meanwhile. Thank you!
