### ISSUE TITLE
Why Vitalys photo so badly quality?

### ISSUE THREAD

**Issue by in-in** [smashingmagazine/redesign#23]
![9e9f7](https://cloud.githubusercontent.com/assets/8797432/24023061/f0cfda84-0aba-11e7-86a3-751a5833d84b.png)

**- Do you want to request a *feature* or report a *bug*?**
a bug

**- What is the current behavior?**
My eyes are bleeding

**- If the current behavior is a bug, please provide the steps to reproduce.**
Just visit this page https://next.smashingmagazine.com/2017/03/a-little-surprise-is-waiting-for-you-here--meet-the-next-smashing-magazine/
Or look at that avatar https://www.gravatar.com/avatar/e8977f4397be6ca8dcf6f2d6d8aa45f1?s=500&d=mm&r=g

**- What is the expected behavior?**
Other authors have nice crisp photo
![cb6ca](https://cloud.githubusercontent.com/assets/8797432/24023055/e26b1f76-0aba-11e7-9bda-ba5feafaa650.png)
![ffdb2](https://cloud.githubusercontent.com/assets/8797432/24023057/e5ff84ce-0aba-11e7-92f2-3cb147eb71de.png)

**- Please mention your operating system version and the version of your browser**
Mint 18 
Chrome Version 57.0.2987.110 (64-bit)

**Comment by vitalyfriedman** [comment]
Thanks @in-in — to be honest, at some point of the design process I didn't even see that photo on the page. :-) Adding it to the to-do list!

**Comment by vitalyfriedman** [comment]
Have found a few workarounds for this problem. Fixed!
