### ISSUE TITLE
Country flag is very small on mobile

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#231]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
Country flag is very small on mobile.

<img width="400" alt="screen shot 2017-09-25 at 1 23 55 pm" src="https://user-images.githubusercontent.com/8038659/30804293-89d01d1c-a1f5-11e7-91a9-3bce8c1f9c87.png">

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to: https://staging.smashingmagazine.com/events/barcelona-2017/
2. Browser is iPhone 5

**- What is the expected behavior?**
<img width="394" alt="screen shot 2017-09-25 at 1 29 30 pm" src="https://user-images.githubusercontent.com/8038659/30804285-7d58b3e6-a1f5-11e7-8ad3-d6ad0e86d33e.png">

^ I also edited the width of the line before the date, since it was pushing the year to a new line.

**Comment by indysigner** [comment]
Hi @shadeed, many thanks for reporting this bug as well, we've fixed it in the meanwhile. 

All the best,

— Markus
