### ISSUE TITLE
One of the speakers photos is inconsistent

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#232]
**- Do you want to request a *feature* or report a *bug*?**
An enhancement.

**- What is the current behavior?**
<img width="806" alt="screen shot 2017-09-25 at 1 21 31 pm" src="https://user-images.githubusercontent.com/8038659/30804478-499111ce-a1f6-11e7-81a1-a414983c2f32.png">

Notice that the first photo is bigger than the rest.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to https://staging.smashingmagazine.com/events/barcelona-2017/

**- What is the expected behavior?**
Speakers photos should be consistent in terms of width and height.

**Comment by indysigner** [comment]
Fixed, thank you! :-)
