### ISSUE TITLE
Newsletter subscription text-box displays error message when clicked in and clicked out of it

### ISSUE THREAD

**Issue by bhaskarmac** [smashingmagazine/redesign#237]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Displays "Your email seems to be... fishy! 🐟" error message.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Steps to reproduce:

1. Click in Newsletter textbox.
2. Click out of textbox.
3. Observe the error message.

**- What is the expected behavior?**
Error message should not be displayed until email address is entered or leaving focus after entering the email address

**- Please mention your operating system version and the version of your browser**
Windows 10 Pro
Google Chrome 62

Please ignore and close this issue if it is a feature or expected as it is.

**Comment by vitalyfriedman** [comment]
The issue is now resolved — thanks for reporting it @bhaskarmac :-)
