### ISSUE TITLE
UI issue with Subscribe button on article detail page

### ISSUE THREAD

**Issue by bhaskarmac** [smashingmagazine/redesign#239]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Height of Subscribe button is disturbed on any article detail page

**- If the current behavior is a bug, please provide the steps to reproduce.**
Visit any article details page and observe the Subscribe button

**- What is the expected behavior?**
Height of the Subscribe button should be same as the Subscribe textbox

**- Please mention your operating system version and the version of your browser**
Chrome 63.0.3239.18
Windows 10

**Comment by vitalyfriedman** [comment]
The issue has been resolved :-) Thank you so much for reporting it! @bhaskarmac
