### ISSUE TITLE
Hard space in comment inline error message

### ISSUE THREAD

**Issue by annban** [smashingmagazine/redesign#24]
When you try to send a comment with an empty input field, the copy of the error message contains an unnecessary '%nbsp"
![screenshot 2017-03-17 00 53 47](https://cloud.githubusercontent.com/assets/1413115/24023397/5c6f2a7e-0aac-11e7-9fd0-2a5c79ee8db7.png)

**Comment by vitalyfriedman** [comment]
Good catch! @annban Fixing in the next PR :-)

**Comment by vitalyfriedman** [comment]
Also, related: "Your name" and "Your email" don't throw any errors (although they should!) (Buggy comments behavior, will open a separate issue for it). 

**Video**
https://www.dropbox.com/s/9dcwj1ek31zf5y2/buggy-comments-behavior.mp4?dl=0

**Comment by vitalyfriedman** [comment]
Fixed @annban — thanks for reporting it!
