### ISSUE TITLE
Broken link to Membership

### ISSUE THREAD

**Issue by KarlFitz** [smashingmagazine/redesign#241]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**

1. Link to membership from main nav is missing "/" 
2. Message says page is being redirected, but it doesn't redirect

![screen shot 2017-11-07 at 14 03 39](https://user-images.githubusercontent.com/9219583/32497580-ec8b9b16-c3c4-11e7-98f8-8a622762441f.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**

1.Click on Membership link in main nav

![screen shot 2017-11-07 at 14 08 46](https://user-images.githubusercontent.com/9219583/32497734-765d89a8-c3c5-11e7-820d-818c10f9f161.png)

**- What is the expected behavior?**

Link should work correctly without need for a redirect message.
Redirect message should be honest.

**- Please mention your operating system version and the version of your browser**
Mac OS Sierra 10.12.6 
Chrome Version 61.0.3163.100

**Comment by indysigner** [comment]
Good point, will fix it soon. Thanks for reporting it!

**Comment by indysigner** [comment]
The issue should be resolved, could you please try again and let me know if it still redirects to `/membership/` instead of `/membership` @KarlFitz? Thank you!
