### ISSUE TITLE
New design - Person of the week

### ISSUE THREAD

**Issue by chaofix** [smashingmagazine/redesign#242]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
The design is not looking good

**- If the current behavior is a bug, please provide the steps to reproduce.**
Just open the site on a mobile device

**- What is the expected behavior?**
Text should wrap the image instead take a 50% of the screen width and the image 50% of the width

**- Please mention your operating system version and the version of your browser**
Android version: 6.0
Baseband version: MPSS.BO.2.5.c3-00101-M8994FAAAANAZM-1.59786.3.60886.1
Kernal version: 3.10.84
Build number: MRA58K
Software version: V20g-ISR-XX

Phone model: LG4
Chrome version: 62.0.3202.84
Operating system: Android 6.0.0; LG-H815 Build/MRA58K
![2017-11-22_07h24_15](https://user-images.githubusercontent.com/7779923/33111487-12ad02c4-cf57-11e7-918e-9d2a7f5bfdb5.png)

**Comment by vitalyfriedman** [comment]
Thanks @chaofix — the issue has been long resolved! Good catch!
