### ISSUE TITLE
New design -  Smashing newsletter

### ISSUE THREAD

**Issue by chaofix** [smashingmagazine/redesign#243]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
The design is not looking good

**- If the current behavior is a bug, please provide the steps to reproduce.**
Just open the site on a mobile device

**- What is the expected behavior?**
The text of "Subscribe" is going out of the "border"

**- Please mention your operating system version and the version of your browser**
Android version: 6.0
Baseband version: MPSS.BO.2.5.c3-00101-M8994FAAAANAZM-1.59786.3.60886.1
Kernal version: 3.10.84
Build number: MRA58K
Software version: V20g-ISR-XX

Phone model: LG4
Chrome version: 62.0.3202.84
Operating system: Android 6.0.0; LG-H815 Build/MRA58K
![whatsapp image 2017-11-22 at 07 34 12](https://user-images.githubusercontent.com/7779923/33111588-97cde4f0-cf57-11e7-9b17-e582eb7f4eca.jpeg)

**Comment by vitalyfriedman** [comment]
Thanks for reporting it, @chaofix — the issue should be resolved two weeks ago ;-)

**Comment by chaofix** [comment]
@vitalyfriedman thanks for the update, I opened this issue two weeks + 1 day ago :-)
