### ISSUE TITLE
Comment link on iPhone 6s does not jump to comments

### ISSUE THREAD

**Issue by marcthiele** [smashingmagazine/redesign#245]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

I see/jump to the footer of the page instead to the comments and can't find the comments.

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Visit smashingmagazine.com
2. In the article overview of Vitaly's relaunch article, click "2 Comments" (can be more now)

**- What is the expected behavior?**

I'd expect to get to the comments and see them.

**- Please mention your operating system version and the version of your browser**

I am on an iPhone 6s, iOS 11.1.2, latest Chrome version

**Comment by vitalyfriedman** [comment]
Should be fixed now, too ;-)
