### ISSUE TITLE
Visual bug on iPhone 6s

### ISSUE THREAD

**Issue by marcthiele** [smashingmagazine/redesign#246]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

Buttons are not centered (see screenshots)

https://marcthiele.com/download/sm-shot-01.png
https://marcthiele.com/download/sm-shot-2.png

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your operating system version and the version of your browser**

**Comment by vitalyfriedman** [comment]
Thanks for reporting the issue, @marcthiele — finally fixing ;-)
