### ISSUE TITLE
Link to SmashingConf London Party is broken

### ISSUE THREAD

**Issue by alienlebarge** [smashingmagazine/redesign#247]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
In "The place we call home" section, the link to "SmashingConf London Party" is broken.
The `s` of `events` is missing in the url.
`https://www.smashingmagazine.com/event/london-2018/`

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Got to [Member Dashboard](https://www.smashingmagazine.com/membership)
1. Click the "SmashingConf London Party" in "The place we call home" section

Here's [a video screen capture](https://cl.ly/3s1b340N3U0N)

**- What is the expected behavior?**
Link to https://www.smashingmagazine.com/events/london-2018/

**Comment by indysigner** [comment]
This issue has been resolved, thanks for reporting it!
