### ISSUE TITLE
Article Author Name Bug

### ISSUE THREAD

**Issue by menjilx** [smashingmagazine/redesign#25]
**- Article "title" please refer to the attached screenshot.
![screen shot 2017-03-17 at 7 52 45 am](https://cloud.githubusercontent.com/assets/14908836/24023756/65710628-0ae9-11e7-9ff0-d12141898cf1.png)

I hope this can help you debug/solve this issue 👍

**Comment by vitalyfriedman** [comment]
Thanks @menjxo — adding to the list!

**Comment by vitalyfriedman** [comment]
Has been resolved.
