### ISSUE TITLE
Printed Magazine: 2 or 4 editions as "Smashing" member?

### ISSUE THREAD

**Issue by anselmh** [smashingmagazine/redesign#250]
**- Do you want to request a *feature* or report a *bug*?**

Bug.

**- What is the current behavior?**

https://www.smashingmagazine.com/2017/11/from-cats-with-love-welcome-the-new-smashing-membership/ talks about four editions a year, while https://www.smashingmagazine.com/membership/ says two.

**- What is the expected behavior?**

Consistent number of editions per year.

<img width="427" alt="screen shot 2017-11-22 at 09 02 08" src="https://user-images.githubusercontent.com/399345/33116172-0543c994-cf64-11e7-8d1e-e9dfada3707e.png">
<img width="865" alt="screen shot 2017-11-22 at 09 02 23" src="https://user-images.githubusercontent.com/399345/33116173-055cc0d4-cf64-11e7-95c0-0d75540ebc70.png">

**Comment by crenshaw-dev** [comment]
Hover text on the membership page also says every 4 months.

![magazine](https://user-images.githubusercontent.com/350466/33783014-ede83902-dc28-11e7-8ae2-eecf8058c111.PNG)

**Comment by indysigner** [comment]
Fixed! Many thanks for reporting it @anselmh @mac9416
