### ISSUE TITLE
Unable to set non-alphanumeric country for the shipping address

### ISSUE THREAD

**Issue by scebotari66** [smashingmagazine/redesign#252]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Not possible to set a country with non-alphanumeric characters for the shipping address. The input gets red borders, and on hover it displays the "Please match the requested format" tool tip.

**- If the current behavior is a bug, please provide the steps to reproduce.**
 - navigate to https://www.smashingmagazine.com/membership
 - scroll to the "Update your addresses" section
 - try to set a country like "Moldova, Republic of", or "Falkland Islands (Malvinas)", or "Côte d'Ivoire" etc.

**- What is the expected behavior?**
To be able to set the countries provided in the dropdown menu.

**- Please mention your operating system version and the version of your browser**
Ubuntu 16.04 LTS, Firefox 57.0

**Comment by vitalyfriedman** [comment]
Dear @scebotari66 — oh good point! On it! Thanks so much for reporting it!

**Comment by vitalyfriedman** [comment]
@scebotari66 The fix is being deployed! Thanks for reporting it!
