### ISSUE TITLE
Call to Action overlapse the table of contents

### ISSUE THREAD

**Issue by lucprincen** [smashingmagazine/redesign#253]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
In articles with a very long table of contents, the call to action will still be full-screen and overlap the toc.

**- If the current behavior is a bug, please provide the steps to reproduce.**
In a desktop-sized browser window, go to this url: https://www.smashingmagazine.com/2017/06/designing-efficient-web-forms/
scroll down to #form-structure and see the cta overlap (see screenshot:)
![schermafbeelding 2017-11-22 om 09 26 28](https://user-images.githubusercontent.com/3257545/33117190-cb7cf736-cf67-11e7-92b3-8f3ab42e8529.png)

**- What is the expected behavior?**
call to action should shrink to a smaller width

**- Please mention your operating system version and the version of your browser**
MacOS High Sierra, Latest stable version of chrome

**Comment by vitalyfriedman** [comment]
Good call! Fixed! Thanks for reporting it @lucprincen
