### ISSUE TITLE
Jobs filter doesn't work properly. 

### ISSUE THREAD

**Issue by sytheveenje** [smashingmagazine/redesign#255]
**- Report a *bug***

**- What is the current behavior?**
When I click some things in the Filter on the Jobs page (i.e. "full-time") no results are shown. Also when you type something and hit enter a "nothing found" page appears.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to Jobs > Click on full-time > Click on all.
2. Go to Jobs, type in Amsterdam. Then hit Enter.

**- What is the expected behavior?**
1. Go to jobs, click full-time, see full-time jobs.

**- Please mention your operating system version and the version of your browser**
OSx + last version of Chrome

**Comment by 42pe** [comment]
Confirmed, I have the same issue. OSX latest + Firefox Quantum (latest stable)

**Comment by vitalyfriedman** [comment]
Thank you so much for reporting it! The issue has been resolved almost a week :-) @42pe @sytheveenje
