### ISSUE TITLE
DO NOT WANT

### ISSUE THREAD

**Issue by buimf** [smashingmagazine/redesign#257]
horrible, just horrible. Waste of space, yet less text.  Stuff only becomes readable below "person of the week". Boo to columns! Can you tell I hate this?

**- Do you want to request a *feature* or report a *bug*?**

**- What is the current behavior?**

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your operating system version and the version of your browser**

**Comment by crgeary** [comment]
It looks fantastic, we must be looking at different websites ;)

**Comment by vitalyfriedman** [comment]
Thanks @buimf and @chrisgeary92 — I'm afraid there is no way we'll go back though. ;-)
