### ISSUE TITLE
Code lost its pretty printing

### ISSUE THREAD

**Issue by leoloso** [smashingmagazine/redesign#258]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
PHP/Bash code does not have the pretty printing anymore. JS code sometimes works fine, sometimes not (at least in the link I provide below)

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to this page: https://www.smashingmagazine.com/2017/10/service-worker-single-page-application-wordpress-sites/
2. Scroll down to where there is code:
![screenshot-2017-11-22 implementing a service worker for single-page app wordpress sites 1](https://user-images.githubusercontent.com/1981996/33123081-10ff62e8-cfb4-11e7-81a5-4c8c58302b02.png)

**- What is the expected behavior?**
Code should be colored

**- Please mention your operating system version and the version of your browser**
Firefox 57

**Comment by vitalyfriedman** [comment]
The code highlighting has been recovered. Thanks for reporting it, @leoloso :-)
