### ISSUE TITLE
Data hierarchy seems to be all over the place

### ISSUE THREAD

**Issue by blaknite** [smashingmagazine/redesign#26]
This is less of a bug and more constructive feedback because I love the content you provide and would love it to continue be the star of the show.

When visiting the new site on a display over 1200px you have made what can only be described as 'interesting' choices regarding the hierarchy of your data. As a reader I am left confused and unmotivated to read the great content you provide.

On my 1080p display I am greeted by a giant author bio before even being told what the current page is about. My eye travel is then torn between the equal weight of the bold title and the heavily embellished drop-cap of the first paragraph. The end result is an uneasy feeling about where I should be going and why I landed at the page.

I notice that on smaller displays you are showing these elements in an order that is more conducive to my eyes tracking through your content. Swapping the page title to be above the drop cap and placing the bio where the title currently is would improve the balance of the page on large displays.

An author's bio is secondary to the article's title and content and it seems an odd decision to feature it so prominently.

I'm running safari on macOS seirra for reference.

Insert terrible picture for reference:

![layout suggestion](https://d1bh5m8o3ysx9y.cloudfront.net/uploads/images/6a986a5f-e122-428b-98ec-d05f73600b63.png)

Thank you for the fantastic content you provide and I hope my feedback is of use.

**Comment by vitalyfriedman** [comment]
Very good point, @blaknite — will be looking into adjusting the hierarchy for larger screens. Having the author's bio in the top right corner is intentional, and we'll explain soon why. ;-)

**Comment by blaknite** [comment]
No worries. I'm glad the feedback was helpful and I look forward to seeing what the final release looks like.
