### ISSUE TITLE
Previous RSS feed is mis-redirected

### ISSUE THREAD

**Issue by rik** [smashingmagazine/redesign#261]
**- Do you want to request a *feature* or report a *bug*?**
Bug report

**- What is the current behavior?**
I'm not subscribed to the RSS feed anymore.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Previous RSS feed was http://rss1.smashingmagazine.com/feed/. That redirects to http://www.smashingmagazine.com/feed/feed/ which redirects to the https version https://www.smashingmagazine.com/feed/feed/ which is a 404.

**Comment by vitalyfriedman** [comment]
Thanks @rik — will take care of it soon!

**Comment by vitalyfriedman** [comment]
Fixed, @rik — thanks for reporting it!
