### ISSUE TITLE
Comment form shifts a few pixels when hovering over Profile Icons

### ISSUE THREAD

**Issue by orielsy** [smashingmagazine/redesign#263]
**- Do you want to request a *feature* or report a *bug*?**
Reporting a Bug
**- What is the current behavior?**
Upon scrolling to bottom of comment area and hovering above Profile Icons the comment form shifts a few pixels. 
**- If the current behavior is a bug, please provide the steps to reproduce.**
1) Scroll to bottom of comments.
2) Hover mouse over any profile Icon.
**- What is the expected behavior?**

**- Please mention your operating system version and the version of your browser**
Windows 10
Chrome 62

**Comment by vitalyfriedman** [comment]
Adding a video in here to investigate what's going on.

![weird-jumps](https://user-images.githubusercontent.com/4688396/33678359-2d6902e8-dac4-11e7-8f56-6e85e7b6ad12.gif)

Adding on our to-do list to explore after taking care of all critical issues. Thanks for reporting the issue, @orielsy!

**Comment by indysigner** [comment]
Hi @orielsy, this is a version-specific bug in Chrome 62. Once you upgrade to v63 (or the upcoming 64) this will be resolved. Thanks for reporting it!
