### ISSUE TITLE
z-index on bizarre sticky header

### ISSUE THREAD

**Issue by Lewiscowles1986** [smashingmagazine/redesign#265]
**- Do you want to request a *feature* or report a *bug*?**

Bug (visual)

**- What is the current behavior?**

Section sticky header on homepage has too high priority, covers content.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Scroll homepage on "Don’t Miss These Articles on Smashing" (single accidental tap on down cursor)

**- What is the expected behavior?**

Being able to read content and view text (after all content is more important than the heading)

**- Please mention your operating system version and the version of your browser**

Linux Ubuntu Xenial Chrome 62.0.3202.94 (Official Build) (64-bit)
![screenshot capture - 2017-11-22 - 13-05-49](https://user-images.githubusercontent.com/2605791/33129046-98b69d10-cf86-11e7-9129-4dc4252048cf.png)  

Linux Ubuntu Xenial Firefox 57.0 (64-bit)
![smashing magazine for web designers and developers smashing magazine](https://user-images.githubusercontent.com/2605791/33129174-f45b0e9e-cf86-11e7-8fd9-b3a34e89f8f7.png)

**Comment by vitalyfriedman** [comment]
Thanks for reporting the issue @Lewiscowles1986 — we are aware of it and we are exploring options and refinements. We are on it ;-)
