### ISSUE TITLE
Upgrade to newer Hugo

### ISSUE THREAD

**Issue by bep** [smashingmagazine/redesign#266]
Hey,

I'm the lead developer of Hugo and the new smashingmagazine.com is really cool.

I do, however, notice that you use a rather old Hugo 0.19 development version to build the site. The current Hugo version is 0.31.

Even if you don't need the new features added (nested sections, custom output formats, related content, native syntax highlighting ... the list is long), there have been a number of important bug fixes, performance improvements etc.

The upgrade from 0.19 to 0.31 should be trivial. There have been some deprecations/method renamings that may hit you, but that should be easy to fix.

Let me know if you need any help.

**Comment by indysigner** [comment]
Hi Bjørn, yes we are working on it (in our internal repo), thanks so much for the heads-up! I'm closing this issue over here since the Hugo update should go live soon. Thank you!
