### ISSUE TITLE
E-mail sign up button broken on Nexus 5 / Chrome

### ISSUE THREAD

**Issue by TheDutchCoder** [smashingmagazine/redesign#268]
**- Do you want to request a *feature* or report a *bug*?**
Report a bug.

**- What is the current behavior?**
"Subscribe" button in newsletter signup callout breaks because of long text.

**- If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**- What is the expected behavior?**
 * Text to wrap and button to expand, or
 * Text to be truncated

**- Please mention your operating system version and the version of your browser**
 * Nexus 5
 * Android 6.0.1
 * Chrome 62.0.3202.84

**Screenshot**
![image](https://user-images.githubusercontent.com/1668207/33131092-81cc052c-cf63-11e7-892c-1c2868fc72cc.png)

**Comment by marlass** [comment]
On homepage subscribe button is also broken. Below 600px resolution "227K smashing folks" does not get wrapped. Tested on Chrome 61 on Ubuntu.

**Comment by vitalyfriedman** [comment]
Thanks for reporting the issue! Please double check again, @marlass @TheDutchCoder.

**Comment by marlass** [comment]
Looks great now.

**Comment by vitalyfriedman** [comment]
Fantastic! Closing the issue now, @marlass
