### ISSUE TITLE
Everything is Red

### ISSUE THREAD

**Issue by lukehardiman** [smashingmagazine/redesign#269]
I don't like red. Revert!

**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
extreme redness

**- If the current behavior is a bug, please provide the steps to reproduce.**
edit css background property.

**- What is the expected behavior?**
A site that no longer assaults my pupils with hot lavaness.

**- Please mention your operating system version and the version of your browser**
Mac chrome. but it's fkn red everywhere. ok maybe not in mosaic.

**Comment by stefany-newman** [comment]
It's too red!!!!

**Comment by vitalyfriedman** [comment]
Oh, but there is a contrast switcher in the right upper corner on the front page? :-) Feel free to remove the redness; that's perfectly fine!

<img width="1104" alt="screen shot 2017-11-22 at 10 38 09 pm" src="https://user-images.githubusercontent.com/4688396/33148807-fb36a256-cfd5-11e7-8a47-9dc57093541f.png">

@lukehardiman @Stefany93

**Comment by webbie** [comment]
That switcher is not visible when adblock is active.
