### ISSUE TITLE
Bug: Code sample <pre> styling

### ISSUE THREAD

**Issue by prahladmishra** [smashingmagazine/redesign#271]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Text not formatted

**- If the current behavior is a bug, please provide the steps to reproduce.**
See code samples in article: https://www.smashingmagazine.com/2017/10/improving-performance-security/
![smashing-mag-bug](https://user-images.githubusercontent.com/5468084/33138614-d67ad73a-cfa2-11e7-9fce-90fd668c1e41.png)

**- What is the expected behavior?**
Code samples should be well formatted and styled.

**- Please mention your operating system version and the version of your browser**
Windows, Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by vitalyfriedman** [comment]
The issue has been resolved, but we'll improve the code highlight in the next iteration. Thanks for reporting it, @prahladmishra :-)
