### ISSUE TITLE
text under card in the "hot topic" area

### ISSUE THREAD

**Issue by stefany-newman** [smashingmagazine/redesign#272]
![image](https://user-images.githubusercontent.com/2403939/33138946-6ee3ec3c-cf71-11e7-858a-a7c017d6404a.png)

I am using Chrome last version on Win 10

**Comment by shellbryson** [comment]
Confirmed here too (Chrome 62, High Sierra)

![screen shot 2017-11-23 at 17 05 29](https://user-images.githubusercontent.com/1268036/33183682-bd219bf6-d070-11e7-82e0-f91ce6100812.png)

**Comment by vitalyfriedman** [comment]
Thanks for reporting the issue, @Stefany93 — can you confirm that it happens only on resize? The issue shouldn't be there on load. We are using Flickity here, and are consider on moving to an alternative. Adding to my list for refinements after all critical issues are closed!

**Comment by vitalyfriedman** [comment]
Issue resolved, and a bugfix coming up shortly! Thanks so much for your help, @Stefany93!

**Comment by stefany-newman** [comment]
^^ No problem and the problem isn't on resize it is on a desktop PC.
