### ISSUE TITLE
Missing author names

### ISSUE THREAD

**Issue by williamukoh** [smashingmagazine/redesign#276]
Some books are missing the Author's name. See screenshot below:

![screen shot 2017-11-22 at 8 54 49 pm](https://user-images.githubusercontent.com/472783/33147419-f6b5334a-cfc7-11e7-9c1f-e2ebc8ea9bed.png)

URL: https://www.smashingmagazine.com/printed-books/
Firefox Quantum 58.0.b4 (64 bit)
macOS Sierra 10.12.6

**Comment by vitalyfriedman** [comment]
Thanks @williamukoh — fixing with today's deploy!
