### ISSUE TITLE
Problems with SW and content in FF 57

### ISSUE THREAD

**Issue by Philosoft** [smashingmagazine/redesign#278]
screenshot
![screenshot-2017-11-23 web design ebook bundle 10 ebooks](https://user-images.githubusercontent.com/296326/33160469-cac21648-d02d-11e7-9cfa-5d1b7e9ba640.png)

Copy-paste from browser console

```
 action  REQUEST_CART_START  @ 09:02:35.522
app.js:26:8480
 action  REQUEST_CART_SUCCESS  @ 09:02:35.525
app.js:26:8480
Failed to load ‘https://www.googletagmanager.com/gtm.js?id=GTM-NW3MXNP’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.
sw.js:1297:4
 action  CALCULATE_MEMBER_PRICE_SUCCESS  @ 09:02:35.798
app.js:26:8480
Failed to load ‘https://www.smashingmagazine.com/js/ads.js’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.
sw.js:1297:4
```

There is no errors on network panel, disabling cache and using incognito mode results in exactly same behaviour

**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

Missing content in FF 57

**- If the current behavior is a bug, please provide the steps to reproduce.**

Open https://www.smashingmagazine.com/ebook-bundles/web-design-ebook-bundle-10-ebooks/ in FF 57 on Ubuntu 17.10

**- What is the expected behavior?**

to see content

**- Please mention your operating system version and the version of your browser**

https://whatismybrowser.com/w/CECX53S

**Comment by Philosoft** [comment]
Forgot to mention - disabling all extensions resulting in excatly the same behaviour, sorry.

**Comment by Philosoft** [comment]
Unfortunatelly it's not only this landing, but all book-selling landings and more on main site, e.g. [main page](https://www.smashingmagazine.com/) - link to [screenshot](https://screenshots.firefox.com/DNVj03ydWbIoYUoy/www.smashingmagazine.com) (valid up to 2017.12.22)

**Comment by vitalyfriedman** [comment]
Thank you so much for reporting it, on it! @Philosoft

**Comment by vitalyfriedman** [comment]
Still on it — now labelling as high priority to fix next.

**Comment by vitalyfriedman** [comment]
Is it by any chance related to this #318 — but will explore in more detail.

**Comment by zachleat** [comment]
I’m downloading Ubuntu to test this.

**Comment by Philosoft** [comment]
@zachleat there is no more need for this - FF 57.0.4 - all seems to display right (pages i report here, some articles/events - site seems ok to me now)

Thanks for reacting
