### ISSUE TITLE
When adding a comment, replace "Your Twitter" with "Your website", or at least have the option for any

### ISSUE THREAD

**Issue by leoloso** [smashingmagazine/redesign#279]
**- Do you want to request a *feature* or report a *bug*?**
Feature

**- What is the current behavior?**
When adding a comment, it requests to add a Twitter handle. I see 2 problems here:
- Not everyone uses Twitter, and they don't want to be forced to have to use it
- In this great community of designers/developers, a great many of them have their own websites, showing their portfolios and long blog posts, and they certainly will prefer to show that instead.

In addition, adding one's personal website plays nice with the [IndieWeb](https://indieweb.org/) philosophy.

**- What is the expected behavior?**

Maybe that input could say "Your Twitter (@handle) or Website (https://...)". Then only if it starts with @ it's Twitter...

**Comment by vitalyfriedman** [comment]
Oh, good point. Will either make the Twitter username optional, and also make it clear. @leoloso

**Comment by vitalyfriedman** [comment]
Currently resolved. Twitter username isn't required any longer. @leoloso Good catch!
