### ISSUE TITLE
Reloading fonts/jumping experience

### ISSUE THREAD

**Issue by vic-georgiev** [smashingmagazine/redesign#28]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
The system reloads all elements, causing the page to jump (fonts reloading) which is visually distracting..

**- If the current behavior is a bug, please provide the steps to reproduce.**
Click on the main navigation to go to different pages

**- What is the expected behavior?**
After first load, all major resources are cached (fonts, JS, some images).

**- Please mention your operating system version and the version of your browser**
iMac 10.12.3, Safari 10.0.3, AdBlock extension installed

**Comment by vitalyfriedman** [comment]
Interesting — because it doesn't happen here at all (with Safari 10). Will be looking into it — thanks @vic-topcoder!

**Comment by vitalyfriedman** [comment]
Should be fixed now, @vic-topcoder — please double check, and thanks for reporting the issue!

**Comment by vic-georgiev** [comment]
Yes, it is working as expected now, @vitalyfriedman :)
