### ISSUE TITLE
Up/down voting of comments is lost?

### ISSUE THREAD

**Issue by leoloso** [smashingmagazine/redesign#280]
**- Do you want to request a *feature* or report a *bug*?**
Feature

**- What is the current behavior?**
In the previous version we could up/down vote comments. It was a nice feature, showing what is important to the community in green, and which comments were completely off-mark in red. 

It would be nice to have it added again, if possible.

**Comment by leoloso** [comment]
It feels nice to show our support to an insightful comment by up-voting it, and not being able to do it anymore feels kind of empty. (I actually noticed that it was not there anymore, when I went to up-vote one of the comments added on your new website...)

**Comment by vitalyfriedman** [comment]
Thank you, good point, @leoloso — it wasn't an intention to "kill" it. Let me see what we can do over the next few weeks to bring it back! Thanks for being smashing! :-)

**Comment by vitalyfriedman** [comment]
Closing this issue as I'm moving it to our to-do board.
