### ISSUE TITLE
"Don’t Miss These Articles  on Smashing" seems intrusive

### ISSUE THREAD

**Issue by sidvishnoi** [smashingmagazine/redesign#282]
Bug: `.featured-articles__teaser.sticky` seems intrusive ("Don’t Miss These Articles  on Smashing")
Current behaviour: Overlaps articles (See video https://streamable.com/rbqun)
Browser: Chrome 62, Ubuntu 16.04 (1920x1080)

**Comment by theartofpeople** [comment]
Agree - it gets in the way of what you're trying to read!

**Comment by vitalyfriedman** [comment]
Thanks for the feedback — let's see what we can do @theartofpeople @sidvishnoi

**Comment by vitalyfriedman** [comment]
Closing this issue as I'm moving it to our to-do board.
