### ISSUE TITLE
Preloaded fonts are of the wrong URL

### ISSUE THREAD

**Issue by yoavweiss** [smashingmagazine/redesign#284]
The fonts stated in the `preload` links are not the same URL as the fonts that are stated in the CSS, and therefore are loaded and never actually used. It'd be better to align them with the fonts actually loaded.

**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
Fonts are preloaded but not used, resulting in wasted bandwidth and console warnings.

**- If the current behavior is a bug, please provide the steps to reproduce.**

Load the site in Chrome with devtools open. You can see that the Elena and Mija fonts are loaded upfront, but later on fonts with similar names are loaded from a different host. The console will also include warnings saying that the fonts are preloaded but not used.

**- What is the expected behavior?**

Not preloading unused fonts...

**- Please mention your operating system version and the version of your browser**
Chrome 62/OSX

**Comment by vitalyfriedman** [comment]
Already fixed — thank you, @yoavweiss :-)
