### ISSUE TITLE
Logs in console in production

### ISSUE THREAD

**Issue by farskid** [smashingmagazine/redesign#286]
Great redesign by the way and a great amount of dare to pick **red** as primary color 👍 

This is neither a bug report nor feature request. This is just a question to ask:

Is there any reason behind allowing your `redux-logger` to log even on production?

![https://preview.ibb.co/ehGioR/Screen_Shot_2017_11_23_at_6_19_19_PM.png](https://preview.ibb.co/ehGioR/Screen_Shot_2017_11_23_at_6_19_19_PM.png)

**Comment by vitalyfriedman** [comment]
Oh, good catch! On it, @farskid :-)

**Comment by vitalyfriedman** [comment]
Currently still for debugging purposes. Will remove close to the final release date ;-) Thanks for reporting it! :-)

**Comment by indysigner** [comment]
Hi @farskid, many thanks for reporting the issue and sorry for the late reply! The issue has been resolved in the meanwhile!
Thank you,

— Markus

**Comment by farskid** [comment]
@indysigner It's a pleasure :) keep the awesomeness 👍
