### ISSUE TITLE
[Author page] Same article duplicated with different titles

### ISSUE THREAD

**Issue by adamsilver** [smashingmagazine/redesign#288]
As you can see from the screenshot, the [same article is appearing twice](https://www.smashingmagazine.com/author/adamsilver/) but appears to be a different article due to the differing title.

![image](https://user-images.githubusercontent.com/37163/33179012-eab9ec00-d05f-11e7-89c3-3f45a85ebcc8.png)

**Comment by indysigner** [comment]
The issue has been resolved. Thank you! :-)
