### ISSUE TITLE
Hover over article cuts off next article's text

### ISSUE THREAD

**Issue by TheDutchCoder** [smashingmagazine/redesign#289]
**- Do you want to request a *feature* or report a *bug*?**
Report a bug

**- What is the current behavior?**
Hovering over an article cuts off the text of the next article

**- If the current behavior is a bug, please provide the steps to reproduce.**
Hover over the article :P

**- What is the expected behavior?**
No visual cut off (it's not necessary at all)

**- Please mention your operating system version and the version of your browser**
Chrome (latest), Mac OS Sierra (latest)

**- Screenshot**
![image](https://user-images.githubusercontent.com/1668207/33183050-546561e6-d044-11e7-8528-608375064e9c.png)

**Comment by vitalyfriedman** [comment]
Thanks for the feedback — let's see what we can do.

**Comment by vitalyfriedman** [comment]
Closing this issue as I'm moving it to our to-do board.
