### ISSUE TITLE
Inconsistent message display for comment box warning

### ISSUE THREAD

**Issue by carbonrider** [smashingmagazine/redesign#29]
Just tried hitting "Submit comment" button without entering details (actually I entered it first and then removed it :P ). The error messages displayed are inconsistent. The first error message for "Your message" field is different that rest of the two (has icon and displays html entity in message). Find attached screenshot.

The message should be consistent. I am using Chrome 56 on windows 7

![image](https://cloud.githubusercontent.com/assets/5756215/24028328/08c26eca-0af4-11e7-8c4a-3e5184e1630e.png)

**Comment by vitalyfriedman** [comment]
Good catch, @carbonrider — fixing! Should go live with the next pull request!
