### ISSUE TITLE
Page ends abruptly with an empty select

### ISSUE THREAD

**Issue by ffraenz** [smashingmagazine/redesign#290]
**- Do you want to request a *feature* or report a *bug*?**
This is a **bug**. I don't know if it is related to the redesign.

**- What is the current behavior?**
[This article](https://www.smashingmagazine.com/2009/09/the-z-index-css-property-a-comprehensive-look/) ends abruptly with an empty select containing the rest of the article.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Navigate to [this article](https://www.smashingmagazine.com/2009/09/the-z-index-css-property-a-comprehensive-look/).

**- What is the expected behavior?**
The whole article should be visible.

**- Please mention your operating system version and the version of your browser**
Chrome Version 62.0.3202.94 on macOS

**Comment by vitalyfriedman** [comment]
Ouch, import issue, @ffraenz — on it!

**Comment by vitalyfriedman** [comment]
Yay, fixed now @ffraenz — thank you :-)
