### ISSUE TITLE
Newsletter sub field collapse on focus (bug?)

### ISSUE THREAD

**Issue by squaredindex** [smashingmagazine/redesign#292]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
When clicking/focused on the input field under "Smashing Newsletter" on the homepage, it seems when the classes of ".float" and ".focused" are added the button on the right of the input field gets pushed under the input.

I would assume this is due to the ".float" class.

Judging by the use of border-radius it doesn't seem like this is supposed to happen as it doesn't look quite right.

I'm on a MacBook Pro using Chrome Version 62.0.3202.94 (Official Build) (64-bit).

**Comment by vitalyfriedman** [comment]
Fix is on its way, @squaredindex — thanks so much for reporting it! You rock!
