### ISSUE TITLE
Quotes do not display correctly in Safari 11.0.1

### ISSUE THREAD

**Issue by kobebeef** [smashingmagazine/redesign#293]
**- Do you want to request a *feature* or report a *bug*?**
BUG

**- What is the current behavior?**
Quote is cut off, only partially readable

![screen_01](https://user-images.githubusercontent.com/2989936/33188014-8df28360-d096-11e7-9cd6-4e7c2562fd15.png)
![screen_02](https://user-images.githubusercontent.com/2989936/33188015-8e0cc5ae-d096-11e7-941b-005a8640cc34.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Load page in Safari 11.0.1 where a quote (&lt;blockquote class="pull-quote"&gt;) is in the text (check: https://www.smashingmagazine.com/2017/11/from-cats-with-love-welcome-the-new-smashing-membership/)

**- What is the expected behavior?**
That the quote is readable

**- Please mention your operating system version and the version of your browser**
macOS 10.13.1 - Safari 11.0.1

**Comment by vitalyfriedman** [comment]
That's very strange — couldn't replicate it in Safari 11. Is it possible that it happened on the first load only? Could it be the issue with critical CSS?

![screen shot 2017-12-01 at 12 13 50 am](https://user-images.githubusercontent.com/4688396/33457855-90cba788-d62c-11e7-8856-aa0db294d299.png)

@kobebeef

**Comment by kobebeef** [comment]
@vitalyfriedman it now work's on my machine. nice animation! I guess it's time to close the issue... probably one of these things where one won't really figure out what happened or what caused the bug
