### ISSUE TITLE
Membership nav item partially hidden in IE

### ISSUE THREAD

**Issue by rCollins1** [smashingmagazine/redesign#294]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Membership tab gets hidden beneath featured-articles-container div.

**- If the current behavior is a bug, please provide the steps to reproduce.**
When the window is adjusted to full screen (or close to it) in IE, the membership nav item is not fully displayed, such that only the top of the tent icon is seen. When the screen is reduced, the nav item is placed underneath the other four nav items.

**- What is the expected behavior?**
It is expected to work as in other browsers (namely, chrome), where membership is next to 'Jobs'.

![image](https://user-images.githubusercontent.com/18533242/33189046-10f6dc68-d06d-11e7-86ed-17383e5a0ad5.png)

![image](https://user-images.githubusercontent.com/18533242/33189171-51635ce4-d06e-11e7-9989-be1e0bf3dfcc.png)

**Comment by vitalyfriedman** [comment]
Issue found and fixed! Deploying coming up shortly! Thanks for reporting it @rCollins1!
