### ISSUE TITLE
RSS sends to 404

### ISSUE THREAD

**Issue by bumstaerk** [smashingmagazine/redesign#295]
I'm using Feedly to read your RSS feed, however when I try to go to the article from Feedly, it seems that it sends me to a 404 page.

An example would be if I clicked the article of:
Empty UX state
The link I get through feedly is this:
https://www.smashingmagazine.com/community-highlights/20171124-empty-states/

I do however have some issue finding the article on the actual page, so I can't confirm if this is just an issue with yet not published articles.

**Comment by verpixelt** [comment]
Yup can confirm the same behaviour on my end.
E.g.: https://www.smashingmagazine.com/talks/unlocking-the-power-of-css-grid-layout/

**Comment by vitalyfriedman** [comment]
Dear @bumstaerk @verpixelt 

The issue should be resolved now! Thank you so much for reporting it! The redirect is on its way, but please use https://www.smashingmagazine.com/articles/index.xml for now!
