### ISSUE TITLE
Create different RSS feeds for different content types

### ISSUE THREAD

**Issue by joshas** [smashingmagazine/redesign#296]
**- Do you want to request a *feature* or report a *bug*?**
Feature.

**- What is the current behavior?**
Every content type is in the same RSS feed.

**- What is the expected behavior?**
Different RSS feeds for content types, e.g. separate feeds for jobs, new articles, events etc.

**Comment by vitalyfriedman** [comment]
Good call, @joshas — adding for the list of things to add after all critical issues are resolved!
