### ISSUE TITLE
Ughh... No please, don't go for this new UI...

### ISSUE THREAD

**Issue by SerafDosSantos** [smashingmagazine/redesign#297]
**- Do you want to request a *feature* or report a *bug*?**
Bug and feature.
**- What is the current behavior?**
Ugly.
**- If the current behavior is a bug, please provide the steps to reproduce.**
Launch this new look/UI and I'll stop surfing it.
**- What is the expected behavior?**
As convenient as the precedent UI.
**- Please mention your operating system version and the version of your browser**
Windows 10 Pro and Google Chrome x (both are irrelevant, the new UI is fugly...)

Thank you but no thanks.

**Comment by vitalyfriedman** [comment]
Point taken — thanks for your feedback, Seraf!
