### ISSUE TITLE
<aside> element overlaps ContentTabs content

### ISSUE THREAD

**Issue by neilbridge** [smashingmagazine/redesign#298]
Hello, I think I found a bug.

Currently, when the browser viewport is more than 1024px in width the aside elements with a class product-panel overlap the ContentTabs div.
This often overlaps and obscures content as seen in the below image.

![screen shot 2017-11-27 at 12 05 01](https://user-images.githubusercontent.com/8971271/33266315-0197036c-d36d-11e7-869c-d23c45f65fb5.png)

This can be seen on the following page if your browser viewport is 1025px width or above:
https://www.smashingmagazine.com/2012/04/a-closer-look-at-font-rendering/

I'm not sure what the expected behaviour of this element is but I personally expect that its width would be restricted to the width of the article content and not overlap or obscure other content.

Tested on OSX 10.11.6 using:
Chrome 62.0.3202.94
Firefox 57.0
Safari 11.0

All of the browsers I used to test this displayed in the same way.

Good luck with your development and design!
Neil

**Comment by vitalyfriedman** [comment]
Thank you so much, @neilbridge — fixing in the new deploy tonight!
