### ISSUE TITLE
Don't require me to hover over cards to read content

### ISSUE THREAD

**Issue by kevincrafts** [smashingmagazine/redesign#299]
The active/hovered card covers up content of other cards, requiring the user to move their mouse around to read content.

![screen shot 2017-11-27 at 10 23 20 am](https://user-images.githubusercontent.com/349713/33279814-2f00c0be-d35d-11e7-87ca-9601f2f43ea3.jpg)

Issue type: Bug
Current behavior: Content on adjacent cards is covered by the card that is currently hovered
Reproduce: Hover mouse over a card in latest posts section
Expected behavior: I should still be able to read content on adjacent cards without having to hover over each card.
Tested on Mac OS 10.31.1 with Safari and Chrome.

**Comment by tehmooo** [comment]
Same behaviour for me - windows 10, chrome

I'll be honest, I think this whole new website is a giant mess and awfully designed.. :(

**Comment by vitalyfriedman** [comment]
Thanks for reporting the issue, @kevincrafts and @tehmooo — we are committed to minor and major changes coming up over the next few weeks and months, and it affects layout as well. Thanks for sticking around!
