### ISSUE TITLE
"about the author" should not link to sign-in page

### ISSUE THREAD

**Issue by smash-it-on** [smashingmagazine/redesign#3]
"About the author" (i.e. https://next.smashingmagazine.com/author/) links to "sign into your dashboard".  Found it via https://next.smashingmagazine.com/2017/03/the-smashing-email-newsletter/ by clicking on the author's avatar.

**Comment by vitalyfriedman** [comment]
Dear @smash-it-on, could you provide a screenshot? Looks perfectly fine around here?

**Comment by smash-it-on** [comment]
@vitalyfriedman Sure, I'm attaching a short video... using Firefox 52.0.
[wrong-link.mov.zip](https://github.com/smashingmagazine/redesign/files/848681/wrong-link.mov.zip)

**Comment by vitalyfriedman** [comment]
Wrong reference to the author. We'll have to look into it more closely. Happens on all other "internal" pages as well.

![screen shot 2017-03-17 at 07 51 40](https://cloud.githubusercontent.com/assets/4688396/24033797/926436a8-0ae6-11e7-8b4a-8f893e7a510a.png)

**Comment by indysigner** [comment]
To be continued via https://github.com/smashingmagazine/smashing-magazine/issues/523
