### ISSUE TITLE
Not able to delete name in comment box

### ISSUE THREAD

**Issue by carbonrider** [smashingmagazine/redesign#30]
I clicked on "Reply" button on one of the comment of some random article. That added name in "Your message" box. I realized it was a mistake and I just want to enter the message. Tried deleting the name, but it isn't working. The name remains in "Your message" and I have no option other than refreshing page to enter clean comment. That's too annoying, as I will have to click many times on "Load the next article" button to load the article, I was reading.

Should allow to clear contents in comment box.

![image](https://cloud.githubusercontent.com/assets/5756215/24028444/0b98ab72-0af5-11e7-87e4-36d9259dc480.png)

**Comment by vitalyfriedman** [comment]
Good catch, @carbonrider — we'll look into it!

**Comment by vitalyfriedman** [comment]
Has been fixed @carbonrider — thanks for reporting the issue!
