### ISSUE TITLE
Problem with button when checkout in FF 54

### ISSUE THREAD

**Issue by ut4utc** [smashingmagazine/redesign#300]
**report a bug**
Little problem with css: 

https://www.dropbox.com/s/g1euc8za7fth64t/Screen%20Shot%202017-11-27%20at%207.26.15%20PM.png?dl=0

Browser Firefox v54. 
In Chrome & Safari - working well, and can't problems.

**Comment by vitalyfriedman** [comment]
Ah, good catch! On it, @ut4utc :-)

**Comment by vitalyfriedman** [comment]
Fix is being deployed1 @ut4utc — thanks for reporting it!
