### ISSUE TITLE
Duplicate Tables of Content

### ISSUE THREAD

**Issue by jakemason** [smashingmagazine/redesign#301]
**- Do you want to request a *feature* or report a *bug*?**
Bug 

**- What is the current behavior?**
On pages where the author embedded a table of content into their writing you now end up with a weird duplicate in the sidebar.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Visit any pages that have a table of content in the content itself such as [this one](https://next.smashingmagazine.com/2017/11/comprehensive-guide-web-design/).

**- What is the expected behavior?**
There should only be a single table of contents on any page.

**- Please mention your operating system version and the version of your browser**
macOS Sierra 10.12.6 / Chrome 61

**Comment by indysigner** [comment]
Hi @jakemason, many thanks for reporting this bug. We have removed the inline Table of Contents. Thank you!
