### ISSUE TITLE
Not all articles seem to have been indexed by Algolia

### ISSUE THREAD

**Issue by leoloso** [smashingmagazine/redesign#303]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Searching for string "www.mydomain.com" produces no results, or searching for "wp_enqueue_script" produces results with either "enqueue" or "script", however there is at least one article with these strings: https://www.smashingmagazine.com/2017/10/service-worker-single-page-application-wordpress-sites/. It seems Algolia has not indexed that one article, and as such possibly many others too.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Click on Topics, enter "www.mydomain.com", it will say No results

**Comment by vitalyfriedman** [comment]
Thanks for reporting this issue @leoloso — on it, and will update the index!

**Comment by indysigner** [comment]
Heyho @leoloso, can you please double-check if this issue is still a thing? It should have been fixed in the meanwhile. Thank you! :-)

**Comment by indysigner** [comment]
This issue has been resolved thanks to Emily Hayman’s help.
