### ISSUE TITLE
Featured articles off-center on homepage

### ISSUE THREAD

**Issue by normanfrancis** [smashingmagazine/redesign#306]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
The featured articles on the homepage appear misaligned where edges meet in the center.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Navigate to [www.smashingmagazine.com](https://www.smashingmagazine.com)
![image](https://user-images.githubusercontent.com/31942547/33352538-5f8683de-d477-11e7-9811-70ca59d998fb.png)

**- What is the expected behavior?**
The edges for the featured articles should align evenly.
There is a CSS selector, .featured-article:first-of-type, that applies a left margin of -1px.
Removing this rule causes the articles to align.

**- Please mention your operating system version and the version of your browser**
Windows 10, Chrome 62

**Comment by vitalyfriedman** [comment]
Very good catch @normanfrancis! Just noticed Sara's comment on why it's in the code:

`margin-left: -1px; // FIXES THE FIRST LINE IN FLEXBOX IN SAFARI!! Safari shows one less item on first row for some reason, I noticed the first item in the grid is off to the right by 1px, so I tried moving it one px to the left and BOOM!`

:-\

**Comment by vitalyfriedman** [comment]
Removing the bugfix for now as I couldn't replicate the issue in Safari 11. @normanfrancis 
Fix being deployed! Thanks for reporting the issue!
