### ISSUE TITLE
Featured Articles Teaser Shadow blocks pointer events

### ISSUE THREAD

**Issue by Fjonan** [smashingmagazine/redesign#308]
the .featured-articles__teaser::after pseudo element blocks pointer events which on desktop results in some links not being clickable. I suggest to add pointer-events: none to the pseudo element

![pointerevents](https://user-images.githubusercontent.com/21336161/33363459-bb9f90ac-d4e0-11e7-918e-395976223017.jpg)

**Comment by vitalyfriedman** [comment]
Good call, @Fjonan — thanks will look into it!

**Comment by vitalyfriedman** [comment]
Fixed and will be deployed shortly @Fjonan!
