### ISSUE TITLE
Smashing Magazine Print image is not loading

### ISSUE THREAD

**Issue by maliMirkec** [smashingmagazine/redesign#309]
**- Do you want to request a *feature* or report a *bug*?**

Bug.

**- What is the current behavior?**

![bug](https://image.prntscr.com/image/MuAyKjKFRAKQ12P4zde2xQ.png)

**- Please mention your operating system version and the version of your browser**

Mac, Chrome Canary

**Comment by vitalyfriedman** [comment]
Fixing in the next deploy, thank you @maliMirkec!
