### ISSUE TITLE
magnify icon not working 

### ISSUE THREAD

**Issue by ghost** [smashingmagazine/redesign#31]
**- Do you want to request a *feature* or report a *bug*?**
      Report a bug

**- What is the current behavior?**
1. zoom-in button misaligned 
![zoomin-misaligned](https://cloud.githubusercontent.com/assets/26127819/24029904/8a55fa14-0aff-11e7-8370-4587978e76f3.jpg)

 2. Clicking on zoom-in beneath the image nothing happening
![zoomin-not-working](https://cloud.githubusercontent.com/assets/26127819/24029905/8a6cd2c0-0aff-11e7-8ddb-f5c191ff0451.jpg)

**- If the current behavior is a bug, please provide the steps to reproduce.**
     1. Go to https://next.smashingmagazine.com/2014/07/the-wai-forward/
     2. Scroll down 
     3. You can see zoom-in/magnify icon on left bottom corner of images.
     4. Click on zoom-in/magnify icon, nothing happen

**- What is the expected behavior?**
      When clicked on zoom-in/magnify icon image should zoom-in.

**- Please mention your operating system version and the version of your browser**
     OS version : Windows 8.1 PRO
     Chrome: Version 57.0.2987.110 (64-bit)

**Comment by vitalyfriedman** [comment]
Thanks @AswathyNath — will fix!

**Comment by indysigner** [comment]
We continue working on this via https://github.com/smashingmagazine/smashing-magazine/issues/30. Thanks for reporting it, @AswathyNath!
