### ISSUE TITLE
Don't see sharing social buttons

### ISSUE THREAD

**Issue by ghost** [smashingmagazine/redesign#310]
I don't see sharing social button (tweet it, share it,...) on article.
![screen shot 2017-11-29 at 5 25 25 pm](https://user-images.githubusercontent.com/25975197/33370538-667a707a-d52a-11e7-90a5-36762d052d68.png)

**Comment by vitalyfriedman** [comment]
Good call! Thanks @luannguyen252 — noticing for later, once all the critical issues are resolved.

**Comment by indysigner** [comment]
Hi @luannguyen252, many thanks for the feature suggestion and sorry for the late reply! We’ve implemented these link sharing links :-) just recently! 

Thank you,

— Markus

![screenshot 2018-07-27 10 04 02](https://user-images.githubusercontent.com/4224281/43309343-d200fda2-9184-11e8-87b1-d1b52d234aaa.png)
