### ISSUE TITLE
Smashing TV listing order is upside down

### ISSUE THREAD

**Issue by nilsmielke** [smashingmagazine/redesign#311]
**- Do you want to request a *feature* or report a *bug*?**
"Bug"

**- What is the current behavior?**
Webinar listing is ordered from the date farthest away (Tim) down to the closest date (Rachel).

**- If the current behavior is a bug, please provide the steps to reproduce.**
Visit https://www.smashingmagazine.com/smashing-tv/

**- What is the expected behavior?**
Order from closest date (Up next: Rachel) to date farthest away (Tim).

**- Please mention your operating system version and the version of your browser**
macOS 10.12.6, Chrome 62.0.3202.94

**Comment by vitalyfriedman** [comment]
Thanks for reporting it, @nilsmielke — aware of it and will fix it :)

**Comment by vitalyfriedman** [comment]
Fixed! :-)
