### ISSUE TITLE
Content on left area make my neck sick

### ISSUE THREAD

**Issue by opsional** [smashingmagazine/redesign#315]
It's not realy buggy but success make my neck sick, can you place content not on very left area? The old content placement better than now.

**Comment by vitalyfriedman** [comment]
Dear @opsional, how would you feel about this kind of layout?

![deploy-preview-2005--smashing-magazine netlify com_2017_09_new-font-technologies-improve-web_ 1](https://user-images.githubusercontent.com/4688396/33518679-a76a1f62-d7a1-11e7-9e30-5b7687daf0b2.png)

**Comment by Dorza** [comment]
Id suggest putting the title block and the stuff beneath it back to the sane place...above the opening paragraph as is standard in ALL reading materials. Then put the "about the author" in the second column with the avatar the same size above the text and to the centre of the column. Yes I know 2 columns are boring in a flex/grid world and we want to explore these things but serioulsy somethings are just fine the way they are - 2 columns work as they are for readability and comfort.

As with the other thread everything is also HUUUGE!!!.

**Comment by vitalyfriedman** [comment]
Dear @Dorza, thank you for pointing it out. The decision to keep the author at the top is a very conscious decisions that has been tested and validated in many usability tests. I know that we are breaking conventions here, but there is a good reason for it — well, at least we believe it's a good reason. The entire magazine is built on displaying and highlighting people making it all happen very prominently, and authors, who usually don't get enough credit, should be getting more credit and recognition for the remarkable work they are doing, sharing their thoughts, ideas, techniques with everybody for pennies.

We are not stubborn just for the sake of it, but the entire personality of the design is built on highlighting people prominently. We are exploring alternatives and happy to discuss if it's a right decision on it. We will move away from a left-aligned layout — that's quite certain though.

Could you specify what exactly is huge on the article page? Even if you compare it against Medium, you don't find such a huge difference in font sizes:

<img width="1254" alt="screen shot 2017-12-05 at 11 33 04 pm" src="https://user-images.githubusercontent.com/4688396/33631932-b9c37940-da14-11e7-82d8-a8a61332dd1f.png">

<img width="1247" alt="screen shot 2017-12-05 at 11 32 42 pm" src="https://user-images.githubusercontent.com/4688396/33631933-b9e39d88-da14-11e7-937a-b37a267ffb2b.png">

I do agree that font-sizes are getting a bit out of control on (quite) large screens, and that's something we have to address. 

Looking forward to your thoughts!

**Comment by vitalyfriedman** [comment]
I take the liberty of closing this issue as it seems to be repeated in other threads. Still, looking forward to your thoughts!
