### ISSUE TITLE
Skip to content doesn't set the taborder right

### ISSUE THREAD

**Issue by fwolle30** [smashingmagazine/redesign#316]
When I use the Tab Key after the page has loaded, the is a notification telling me, that I could skip to the main content.

However, if I use this link, and tab aggain, I'm back up to the top of the page.
What should happen instead is, that the next time I press tab, focus indicator should be on an element in the main content section, and not on top pf the page.

Used Browser: Google Chrome v. 62.0.3202.94 x64 on a Windows 10 System

**Comment by vitalyfriedman** [comment]
Dear @fwolle30 — I'm afraid it would break the experience for people who want to tab through the navigation without jumping to the content. I guess that if you intent to jump to the main page, it's expected to prompt the action to jump? Or am I misunderstanding something here?

**Comment by fwolle30** [comment]
Well, if you use the tab key, and then get the prompt:
"Skip to maincontent?", wich is a link by the way, I expect that by pressing the spacebar, I activate the link, and jump right into the main content. This is working fine. However if I press the tab key a second time, I'm back to the top, although I've visited the link.

**Comment by vitalyfriedman** [comment]
Ah! That's a good point! Adding it on my to-do list — got the problem now. Thanks @fwolle30 — will fix.

**Comment by vitalyfriedman** [comment]
Uhm. I can't replicate the issue. Is this the behavior you are expecting?

![bug-issue](https://user-images.githubusercontent.com/4688396/33637501-f11cc53a-da29-11e7-95de-83bfc6516191.gif)

@fwolle30

**Comment by fwolle30** [comment]
Okay, I've tested it again. It seems like chrome doesn't follow a link, when the spacebar is used, and instead scrolls down a bit. If I press enter inatead, the link works as expected and the the correct links are highlighted when the tab key is pressed again.

**Comment by vitalyfriedman** [comment]
Phew, glad we sorted it out! Thanks for your help, @fwolle30 :-)
