### ISSUE TITLE
Bug with icons on a page "possible related jobs"  on chrome 56

### ISSUE THREAD

**Issue by Nikita-schetko** [smashingmagazine/redesign#32]
*icons for "possible realted jobs" not showing properly on chrome 56*

*https://next.smashingmagazine.com/jobs/2017-1-31-reactengineer-russiaandukraine-foxcommerce-remote-russiaukrainepoland-fulltime/*

*icons should look like icons*

*windows 10, chrome 56.0.2924.87*

![2017-03-17 08 23 05](https://cloud.githubusercontent.com/assets/8004255/24030086/bc49025a-0aeb-11e7-8cf0-91e9f424020b.png)

**Comment by vitalyfriedman** [comment]
Good catch, @Nikita-schetko — will look into it!

**Comment by indysigner** [comment]
This issue has been fixed in the meanwhile. Thanks for reporting it, dear @Nikita-schetko!
