### ISSUE TITLE
Text cut off on right side of home page.

### ISSUE THREAD

**Issue by Heydon** [smashingmagazine/redesign#320]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Text is obscured on the right hand side of the screen at 0 zoom (default). See the image, below.
![image](https://user-images.githubusercontent.com/683558/33514922-54b89788-d753-11e7-928a-da1cf64fd8e2.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Go to the homepage with a long author line, like the one pictured.

**- What is the expected behavior?**
The text is not as long, or wraps.

**- Please mention your operating system version and the version of your browser**
OSX/ Chrome 62 (latest)

I suggest that the text is able to wrap, or the `<time>` element is placed on a new line by default.

**Comment by vitalyfriedman** [comment]
Thanks @Heydon — it was a `nowrap` property. Will double check one more time. :-)

**Comment by vitalyfriedman** [comment]
Will be resolved in the next deploy! :-) @Heydon
