### ISSUE TITLE
RSS/Atom feed too large

### ISSUE THREAD

**Issue by TravisCardwell** [smashingmagazine/redesign#321]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

The [RSS/Atom feed](https://www.smashingmagazine.com/feed/) currently contains 2,789 entries, taking about ~2.5MB.  This causes the following undesired behavior:

* It takes RSS readers a relatively long time to download the feed each update.
* It takes RSS readers a relatively long time to parse the feed each update.
* It bloats the size of RSS reader data store.

By the way, I notice that the XML in the feed is not minimized, resulting in a feed that is larger (in bytes) than it needs to be.  For an example of minimized XML, see the [Lifehacker RSS feed](https://lifehacker.com/rss).

**- If the current behavior is a bug, please provide the steps to reproduce.**

    $ wget -O sm.xml https://www.smashingmagazine.com/feed/
    ...
    $ ls -lh sm.xml 
    -rw-r--r-- 1 tcard tcard 2.5M 12月  3 10:10 sm.xml
    $ grep -o '<item>' sm.xml | wc -l
    2789

**- What is the expected behavior?**

RSS/Atom feeds usually only contain a constant number of the most recent articles.  For example,  the [Lifehacker RSS feed](https://lifehacker.com/rss) has the 25 most recent articles, resulting in a feed that is currently ~35KB in size:

    $ wget -O lh.xml https://lifehacker.com/rss
    ....
    $ ls -lh lh.xml
    -rw-r--r-- 1 tcard tcard 35K 12月  3 10:19 lh.xml
    $ grep -o '<item>' lh.xml | wc -l
    25

**- Please mention your operating system version and the version of your browser**

This is a server-side issue: RSS/Atom feed generation is not well implemented.

**Comment by siliconforks** [comment]
Interesting - I was looking at the feed yesterday to check whether #264 was fixed, and at that time it only had the 50 most recent articles (which seemed like a reasonable amount); it must have just started doing this in the last day or so.

**Comment by TravisCardwell** [comment]
I update my feeds twice per day, and this morning was the first time that the feed contained so many entries for me, but I may have been using the old feed.  (I removed the feed when it started causing issues, so I cannot check which one I was using.  I will of course put the feed back once the issue is resolved, btw!)

50 entries sounds reasonable to me.  Currently, that would contain entries from [Customizing Admin Columns In WordPress](https://www.smashingmagazine.com/2017/12/customizing-admin-columns-wordpress/) (Fri, 01 Dec 2017 17:46:00 +0100) to [Launching Your Design Career: Which Type Of Education Is Best For You?](https://www.smashingmagazine.com/2017/09/design-career-best-education/) (Tue, 12 Sep 2017 21:47:40 +0000).  Readers would not miss any articles even if they only update their feeds every 2.5 months.

**Comment by vitalyfriedman** [comment]
Thank you @TravisCardwell @siliconforks @lembitk — will be looking into it, definitely a bug that needs solving!

**Comment by siliconforks** [comment]
This bug was fixed for a while, but it seems to have returned today (Dec 11, 2017).

**Comment by Levdbas** [comment]
I have the same issue. Large RSS feed ocurring in my browser.
