### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by Fjonan** [smashingmagazine/redesign#324]
I had opened one of the articles as a kind of reminder (https://www.smashingmagazine.com/2016/06/the-current-state-of-authentication-we-have-a-password-problem/) to read later. That was last week (I guess monday or tuesday). Today I saw that the tab was with over 3 GB of memory usage. Unfortunately when I opened the dev tools the memory usage dropped down to about 140 mb (my guess is that forced GC kicked in).

I am not sure how to verify this behavior but I wanted to report it anyway. Maybe your devs already know what can cause this problem.

Even though the dev tools garbage collection seemed to have fixed the issue the regular user might not open the dev tools to read your page ;) and - with the tab left open - would eat away at the memory.

**Comment by Fjonan** [comment]
Additional comment - I left the tab open, not active and it accumulates 8 kb per second in memory usage (currently at 206,2 MB). I am positive that some interval is causing this effect.

**Comment by vitalyfriedman** [comment]
Oh thanks @Fjonan — we'll look into it of course!

**Comment by vitalyfriedman** [comment]
Dear @Fjonan — could you double check again, please? We've been running CrazyEgg to generate heatmaps, but it's gone now! (should be soon, after a new deploy) — could it be "//script.crazyegg.com/pages/scripts/0011/1125.js"?

**Comment by Fjonan** [comment]
I reloaded the tab and left it open for a bit and now it does not accumulate any more memory. So this seemed to have fixed that.

Maybe you can halt CrazyEgg on window blur or if any interaction of the user fails to register for about 30 seconds?

Edit: 6 hours later, same situation.

**Comment by vitalyfriedman** [comment]
Very strange. Looking into it @Fjonan.

**Comment by Fjonan** [comment]
Just to clarify - with "same situation" I meant "no memory usage increase". Could have said that clearer, sorry.

Tab is still open and still at 127 MB

**Comment by indysigner** [comment]
Hi @Fjonan, could you please double-check if this issue is this a thing? I’m afraid I'm not able to replicate this behavior... Thank you!

**Comment by Fjonan** [comment]
After Vitaly told me to re-check (third comment) it did not reoccur. I checkd it again just now and I cannot see the same behavior like when I created the ticket.

**Comment by indysigner** [comment]
Cool, thanks for the response! I think this was related to a heat map script from Crazyegg, where we wanted to visualize how users are using the new design. We already removed the script, so hopefully this shouldn't be an issue any longer. Thanks again!
