### ISSUE TITLE
Smashing TV - Different timezones

### ISSUE THREAD

**Issue by fredrikwoll** [smashingmagazine/redesign#326]
Couldn't find any open/closed issues about this. Was looking at when the webinar today was happening
and got a bit confused when it was listed in UTC two places and GMT another place. 

**- Do you want to request a *feature* or report a *bug*?**
"bug"?

**- What is the current behavior?**
The Smashing TV "overview" and /membership page show time in UTC while the sub-page about the actual webinar
shows time in GMT.

**- If the current behavior is a bug, please provide the steps to reproduce.**

UTC -> https://www.smashingmagazine.com/smashing-tv
UTC -> https://www.smashingmagazine.com/membership#webinars
GMT -> https://www.smashingmagazine.com/smashing-tv/global-web-design-hong-kong/

**- What is the expected behavior?**
I expected time to be shown in the same timezone. Was a bit confused. 

**- Please mention your operating system version and the version of your browser**
Google Chrome v. 62.0.3202.94  on Windows 10 Pro & macOS High Sierra

**Comment by vitalyfriedman** [comment]
Ouch, good point @fredrikwoll — fixing!

**Comment by vitalyfriedman** [comment]
Will be fixed with the next deploy @fredrikwoll — thanks for reporting it!
