### ISSUE TITLE
Firefox freezes when opening RSS feed

### ISSUE THREAD

**Issue by chriskirknielsen** [smashingmagazine/redesign#327]
Hello there,

I have a bit of an issue with Firefox (57.0 on macOS Sierra) concerning the RSS feed from Smashing Magazine.
I have it saved is as a dynamic bookmark, but every time I try to load it (= hover the bookmark to open the list of articles), Firefox freezes for a few seconds. The list of articles shows up after a shirt while.

I fear this is an issue related to the number of links in the RSS feed. I have to scroll over a dozen "pages" of 50+ links to get to the bottom of the list.

Suggested action: reduce number of links in the RSS feed.

Thanks!

**Comment by lembitk** [comment]
Related to / duplicate of #321.

**Comment by vitalyfriedman** [comment]
The fix is being deployed @lembitk @chriskirknielsen — thanks for reporting it!
