### ISSUE TITLE
On page load it displays red first and then white background on home page

### ISSUE THREAD

**Issue by bhaskarmac** [smashingmagazine/redesign#329]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behaviour?**
On page load, it displays red first and then white background on the homepage.

**- If the current behaviour is a bug, please provide the steps to reproduce.**
1. Visit homepage (https://next.smashingmagazine.com/)
2. Change theme to white.
3. Refresh the page.
4. Observe for few seconds it displays background red first and then white.

**- What is the expected behaviour?**
If the White theme is selected it should directly display the white instead of displaying red and then applying the theme.

**- Please mention your operating system version and the version of your browser**
Windows 10 Pro
Google Chrome beta 63.0.3239.70

**Comment by vitalyfriedman** [comment]
Actually, that's a desired behavior — switch from red to white. But let me see how we can improve it! Thanks for reporting it, @bhaskarmac!
