### ISSUE TITLE
Author biography is used differently between detail and article pages regarding content

### ISSUE THREAD

**Issue by anselmh** [smashingmagazine/redesign#33]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

Both, author pages and article pages show an author’s biography. However, the two texts differ, leading to an issue with how to write the biography. On the author’s page, starting the biography with a new sentence and eventually with the name makes sense while on an article page the biography starts automatically with an author’s name, meaning a new sentence start in the biography looks weird.

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. https://next.smashingmagazine.com/author/anselm-hannemann/#
2. https://next.smashingmagazine.com/2017/03/web-development-reading-list-173/

![screen shot 2017-03-17 at 06 41 40](https://cloud.githubusercontent.com/assets/399345/24030497/a6d43736-0add-11e7-9325-cdbcb3cdd055.png)
![screen shot 2017-03-17 at 06 41 55](https://cloud.githubusercontent.com/assets/399345/24030498/a6d43862-0add-11e7-8c8b-eb80a614d301.png)

**- What is the expected behavior?**

The biography is written in a way that appears always in a great readable and consistent way, regardless of the page it appears on. Likely starting with the name makes more sense, as it’s already done in the author’s section on an article page.

**Comment by vitalyfriedman** [comment]
Thanks @anselmh — good catch! Will look into it!

**Comment by indysigner** [comment]
This issue already has been resolved. Thanks for reporting it, dear @anselmh!
