### ISSUE TITLE
On homepage "Don’t Miss These Articles  on Smashing" text displayed on top of articles

### ISSUE THREAD

**Issue by bhaskarmac** [smashingmagazine/redesign#330]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
On homepage when scrolled "Don’t Miss These Articles  on Smashing" text displayed on top of articles

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Visit homepage (https://next.smashingmagazine.com/)
2. Scroll down and observe the "Don’t Miss These Articles on Smashing" text.

**- What is the expected behavior?**
"Don’t Miss These Articles on Smashing" text should be gone out of the screen like other top text does.
Please leave a comment if this is intended behaviour.

**- Please mention your operating system version and the version of your browser**

**Comment by vitalyfriedman** [comment]
Thanks for reporting it, but that was a desired behavior, too. Not sure if we'll keep it this way though! @bhaskarmac
