### ISSUE TITLE
Google search input doesn't bring me to results

### ISSUE THREAD

**Issue by djschoone** [smashingmagazine/redesign#333]
When searching smashingmagazine, it shows a nice search box as a result in Google. When using this search it get's me to https://www.smashingmagazine.com/?s=angular

I expected the results of this search, but got the homepage.

I think some configuration OR redirection has to take place, because the URL that gave me the results is (now) https://www.smashingmagazine.com/search/?q=angular

**Comment by indysigner** [comment]
Hi @djschoone, many thanks for reporting this! ATM I cannot replicate the issue, e.g. when I google for `angular site:smashingmagazine.com` Google gives me theses results: 

![screenshot 2017-12-20 18 32 45](https://user-images.githubusercontent.com/4224281/34220235-32f34692-e5b4-11e7-8b4c-3ebb24f3203c.png)

When using the on-site search, I'm seeing this:

![screenshot 2017-12-20 18 33 16](https://user-images.githubusercontent.com/4224281/34220262-5415ad24-e5b4-11e7-8496-65fdf02ad608.png)

Maybe you can try again and let me know if you still got the issue you initially reported? Many thanks!

**Comment by djschoone** [comment]
Hello @indysigner ,

Your welcome! Great to see this follow up.

The search I used was the free search Google gives me. See below. 

![image](https://user-images.githubusercontent.com/185512/34256933-f5207192-e657-11e7-9d4a-2a4cd61a54f9.png)

When entering 'angular' where it states 'Zoeken in smashingmagazine.com' it brings me to the wrong aforementioned URL.

**Comment by indysigner** [comment]
Interesting, thank you, that's super helpful.... will discuss with the team how to fix this.

**Comment by indysigner** [comment]
This issue has been (finally) resolved, thanks for reporting it!
