### ISSUE TITLE
PAYPAL

### ISSUE THREAD

**Issue by esoldao** [smashingmagazine/redesign#335]
**- Do you want to request a *feature* or report a *bug*?**

**- What is the current behavior?**

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your operating system version and the version of your browser**

**Comment by esoldao** [comment]
https://plus.google.com/communities/105086440586613576639

**Comment by vitalyfriedman** [comment]
Dear @esoldao — can you report, please? It says:

"You'll need to join the community to see posts."

**Comment by indysigner** [comment]
Closing this since the bug hasn't been described and the user doesn't answer.
