### ISSUE TITLE
"Dealing with stress as a designer" article shows up via search but page gives 404 error

### ISSUE THREAD

**Issue by lpar** [smashingmagazine/redesign#338]
**- Do you want to request a *feature* or report a *bug*?**

Bug.

**- What is the current behavior?**

Two days ago you published https://www.smashingmagazine.com/2017/12/dealing-with-stress-designer-what-research-says/
The page now gives a 404 error. Using the site's own search engine, the page is found, but still gives 404.

**- If the current behavior is a bug, please provide the steps to reproduce.**

 1. Go to https://www.smashingmagazine.com/2017/12/dealing-with-stress-designer-what-research-says/
 2. Get 404.
 3. Click search control.
 4. Type "dealing with stress as a designer"
 5. Get search result, click it.
 6. Get 404 again.

**- Please mention your operating system version and the version of your browser**

Safari 11.0.1, macOS High Sierra 10.13.1.

**Comment by indysigner** [comment]
hi @lpar, many thanks for reporting the issue, I just deployed a fix! Thank you.
