### ISSUE TITLE
Link rot on old subdomains

### ISSUE THREAD

**Issue by lembitk** [smashingmagazine/redesign#339]
A bit off topic (sorry), but still worth reporting IMHO… A while (years) ago you used to have content on “thematic subdomains”, e.g. `coding.smashingmagazine.com`, `mobile.smashingmagazine.com` etc. Now all such URLs are broken, so there's a lot of [broken](http://mobile.smashingmagazine.com/2013/12/09/mobile-google-analytics-tag-manager/
) [links](http://coding.smashingmagazine.com/2013/10/29/get-up-running-grunt/
) and [invalid](http://fireworks.smashingmagazine.com/2012/12/03/design-ios-apps-with-adobe-fireworks/
) [bookmarks](http://wp.smashingmagazine.com/2012/10/09/four-malware-infections-wordpress/
) left behind, having a lot of user frustration potential on the downside, and a lot of link juice / traffic potential on the upside. 

I would suggest considering redirecting those old subdomain URLs to their up-to-date counterparts. I know this can be tricky and laborious because possible interim slug changes come also into play. 

- An old article on its current URL: https://www.smashingmagazine.com/2013/12/mobile-google-analytics-tag-manager/. 
- In my bookmarks I have this URL: http://mobile.smashingmagazine.com/2013/12/09/mobile-google-analytics-tag-manager/ (won't resolve). 
- In my RSS reader I have this URL: http://www.smashingmagazine.com/2013/12/09/how-to-simplify-mobile-app-data-with-google-analytics-and-tag-manager/ (404).

When [checking Google](https://www.google.com/search?q=site:smashingmagazine.com+-site:www.smashingmagazine.com), those old `coding`, `wp` and other subdomains won't show up anymore. However, Google seems to have indexed quite many pages from a few other subdomains which might deserve a closer look (e.g. `shop` or `jobs`, among others). 

Sorry again, as this might be rather low priority stuff, and it also might very well be something you've discussed internally and found to be a non-issue. 

_Thank you_ for so much great content over so many years.

**Comment by indysigner** [comment]
Hi @lembitk, many thanks for reporting all these broken links. All the old subdomains are working again, and a redirect for the Google Analytics article is being deployed right at this moment. Thank you! :-)
