### ISSUE TITLE
Update cycle of the page?

### ISSUE THREAD

**Issue by anselmh** [smashingmagazine/redesign#34]
This is more of a question rather than a bug report. I just tried to update my biography but the changes are not shown immediately (probably on purpose due to static site generation, caching). I understand this is desired, however I think it makes sense to state that in the backend indicating that "it can take up to … minutes/hours" to update…?

**Comment by vitalyfriedman** [comment]
Thanks @anselmh — there is no replication just yet. So far, beta isn't affected by the "real" site (www.smashingmagazine.com). Wait and see ;-)
