### ISSUE TITLE
Remove upcoming events / webinars from RSS

### ISSUE THREAD

**Issue by Baysen** [smashingmagazine/redesign#340]
You recently started scheduling your webinars and that's really helpful, but they also appear on top of the RSS feed and every time you release a new article, I have to scroll way down to view it.
Could you remove the webinars from the feed or offer a serarate one for those? Thanks!

**Comment by indysigner** [comment]
Hi @RemizZ, thanks for reporting the issue! Can you please let me know the feed URL you are using? (we have several feeds). Thank you!

**Comment by Baysen** [comment]
Hey there! It's simply https://www.smashingmagazine.com/feed/ and it's the only feed shown to me by the Chrome extension Feeder.

**Comment by indysigner** [comment]
OK, on it, thank you!

**Comment by indysigner** [comment]
This has been resolved, thanks! :-)
