### ISSUE TITLE
Bug: Double dashes turns into en-dash

### ISSUE THREAD

**Issue by larsenwork** [smashingmagazine/redesign#341]
**- Do you want to request a *feature* or report a *bug*?**
🐛

**- What is the current behavior?**
`--` becomes `–`

**- If the current behavior is a bug, please provide the steps to reproduce.**
Go to e.g. https://www.smashingmagazine.com/2017/04/start-using-css-custom-properties/

**- What is the expected behavior?**
`--` stays untouched

**- Please mention your operating system version and the version of your browser**
Mac + Chrome latest.

<img width="585" alt="screen shot 6" src="https://user-images.githubusercontent.com/3859425/33862399-d32f7ec4-dee2-11e7-83e6-662ddd12077a.png">

**Comment by vitalyfriedman** [comment]
Thanks so much for reporting the issue @larsenwork — fixed, and it's being deployed!
