### ISSUE TITLE
Rendering issue on Membership page

### ISSUE THREAD

**Issue by bhaskarmac** [smashingmagazine/redesign#342]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
"-->" is displayed on membership page (https://next.smashingmagazine.com/membership/)

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Login to the https://next.smashingmagazine.com
2. scroll down till "Coming Up Next in Membership" section
3. Observe you can see the "-->" symbol

**- What is the expected behavior?**
"-->" symbol should not be displayed, probably its due to comments in code left unclosed.

**- Please mention your operating system version and the version of your browser**
![arrow](https://user-images.githubusercontent.com/4056847/33867807-1a17a180-df25-11e7-88fb-bff074d63a19.PNG)

**Comment by vitalyfriedman** [comment]
Thanks for reporting it! Fixed! :-) @bhaskarmac
