### ISSUE TITLE
Grid Size

### ISSUE THREAD

**Issue by daveek** [smashingmagazine/redesign#344]
**- Do you want to request a *feature* or report a *bug*?**
Feature Grid Size

**- What is the current behavior?**

I'm my desktop, it's a resolution of 1920x950px and the home page doesn't fit very good.. "It is too Big"
here it is the screenshot originaly:

![smash-origin](https://user-images.githubusercontent.com/4696050/33882345-11bbe9e8-df38-11e7-94c0-4e20e546f2e1.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

And If I make a reduce of 50%, It looks better:
![smash-better](https://user-images.githubusercontent.com/4696050/33882388-385a6bd8-df38-11e7-9d7b-06a9acaeebb4.png)

**- Please mention your operating system version and the version of your browser**

I'm in Windows 10, with Chrome v.62.0.32

**Comment by vitalyfriedman** [comment]
Already adjusted @daveek — thanks for reporting it!
