### ISSUE TITLE
"Search Job" input searches entire site

### ISSUE THREAD

**Issue by eclarrrk** [smashingmagazine/redesign#345]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
On Jobs page, enter a term into the "Search Jobs" search field.

If you *do not* hit Return, the results will be filtered.

If you *do* hit return, it will search the entire website—not just jobs— for that term upon hitting Return to submit the form. 

**If the current behavior is a bug, please provide the steps to reproduce.**
On Jobs page, enter a term into the "Search Jobs" input and hit Return to submit.

**What is the expected behavior?**
Return jobs that include the term.

**Comment by vitalyfriedman** [comment]
Ahhh good catch, @eclarrrk — thanks for reporting it!

**Comment by eclarrrk** [comment]
No problem @vitalyfriedman — I was trying to find a cat (Felix). Instead I found a bug!
