### ISSUE TITLE
Duplicate content and broken styling in article

### ISSUE THREAD

**Issue by chinchang** [smashingmagazine/redesign#347]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Duplicate content and broken styling

**- If the current behavior is a bug, please provide the steps to reproduce.**
https://www.smashingmagazine.com/2013/10/challenging-css-best-practices-atomic-approach/

**- What is the expected behavior?**
No duplicate content and correct code block styling

**- Please mention your operating system version and the version of your browser**
Chrome on Mac osx.

**Comment by vitalyfriedman** [comment]
Thanks for reporting it, @chinchang — we are on it!

**Comment by indysigner** [comment]
Hi @chinchang, many thanks for reporting it! I just deployed a fix which should go live in the next few minutes.
