### ISSUE TITLE
Search resaults

### ISSUE THREAD

**Issue by tinstin** [smashingmagazine/redesign#349]
It may not be an issue but search results displayed random, I think latest article (by date of issue) must show first then follow by older.

**Comment by vitalyfriedman** [comment]
Yes, fully agree, @tinstin — we are looking into it!

**Comment by indysigner** [comment]
Hi @tinstin, this should be the case indeed. Can you give me any examples (keywords you were looking for) where you are seeing the problem?

**Comment by vitalyfriedman** [comment]
Pretty much any keyword @indysigner, even "perf" returns a result from 2009.

![screen shot 2017-12-20 at 7 56 54 pm](https://user-images.githubusercontent.com/4688396/34221234-fbe592f2-e5bf-11e7-84cc-0c1accf57434.png)

**Comment by indysigner** [comment]
I see. But this really is because the keyword `perf` is nearer with the word “Perform” than with “Performance”. I think we can turn this ranking factor off, but that wouldn't really get us better search results. @vitalyfriedman 

Any other examples?

**Comment by tinstin** [comment]
@indysigner sorry for late reply.  I have try with "react" and the result is what I expected to see right now, I think it was fixed.

**Comment by indysigner** [comment]
Cool, thanks for letting me know! Also, feel free to reach out if you spot any other weirdness. I know it's not perfect yet, so I'll look for ways on how to improve the search results.
