### ISSUE TITLE
Next Article shows up on current article but doesn’t update URL dynamically

### ISSUE THREAD

**Issue by anselmh** [smashingmagazine/redesign#35]
**- Do you want to request a *feature* or report a *bug*?**

Bug.

**- What is the current behavior?**

On bottom of https://next.smashingmagazine.com/2017/03/web-development-reading-list-173/ there appears the next (previous) article on Smashing Mag, but when scrolling this into viewport, the URL doesn’t update so I’m very confused on which article I am currently.

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Visit an article, scroll beyond comments section to next article
2. Next article shows up
3. URL doesn’t update

**- What is the expected behavior?**

URL updates dynamically once the next article owns the majority of the viewport.

**- Please mention your operating system version and the version of your browser**

macOS 10.12, Firefox latest stable (52) and Nightly (55.0a1)

**Comment by vitalyfriedman** [comment]
Ouch — on it! ;-) @anselmh

**Comment by indysigner** [comment]
Thanks @anselmh, working on it via https://github.com/smashingmagazine/smashing-magazine/issues/165
