### ISSUE TITLE
Appearance of third article in large windows

### ISSUE THREAD

**Issue by petercalvert** [smashingmagazine/redesign#350]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
When the article grid at the top of the homepage extends to three columns per row, the third article content appears higher than the initial two.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Visible when the browser width is above ~1935px. Does not appear to occur on smaller windows when the section drops down to two columns per row and the fourth story is present.

**- What is the expected behavior?**
Articles should appear consistently

**- Please mention your operating system version and the version of your browser**
FF DE (58) - also replicated in Chrome 63.

![screen shot 2017-12-15 at 08 41 49](https://user-images.githubusercontent.com/23497755/34033842-dc2e46fc-e173-11e7-8d67-8b6fbef50188.png)
![screen shot 2017-12-15 at 08 42 02](https://user-images.githubusercontent.com/23497755/34033843-dd28a84a-e173-11e7-8958-9d020f7a41de.png)

**Comment by vitalyfriedman** [comment]
Ah thank you, @petercalvert — will look into it tonight!

**Comment by vitalyfriedman** [comment]
Fixed, thanks @petercalvert :-)
