### ISSUE TITLE
No footer on the page

### ISSUE THREAD

**Issue by Soean** [smashingmagazine/redesign#352]
**- Do you want to request a *feature* or report a *bug*?**
*bug*

**- What is the current behavior?**
I can't see the footer of the page:
https://www.smashingmagazine.com/2014/11/styling-and-animating-svgs-with-css/

**- What is the expected behavior?**
I want to read the full article and see the footer.

**- Please mention your operating system version and the version of your browser**
Mac OSX Firefox / Chrome

**Comment by indysigner** [comment]
The issue has been resolved, thanks for reporting it, dear @Soean!
