### ISSUE TITLE
Article's publishing time not right

### ISSUE THREAD

**Issue by leoloso** [smashingmagazine/redesign#353]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
An article was published just minutes ago, yet it reads "About 8 hours ago". I'm based in Malaysia, which is GMT +8, maybe that's why?

**- If the current behavior is a bug, please provide the steps to reproduce.**
Homepage => latest articles => time of last article published. Check screenshot (article was published just minutes ago):

![screenshot-2017-12-19 smashing magazine for web designers and developers](https://user-images.githubusercontent.com/1981996/34116681-437e85b4-e454-11e7-8b87-54fbe66a35fc.png)

**Comment by indysigner** [comment]
Hi @leoloso, this must have been an issue in our editorial workflow, where the timestamp wasn't updated for the article went live. Thanks for reporting it! (and sorry about that! :-)

**Comment by leoloso** [comment]
@indysigner Nops, it is still happening. I actually saw it said "20 min" and then it immediately became "7 hours" after loading, on top of this last article, so there's definitely something wrong on the javascript side. You will not see the bug unless you set your time to some other GMT

![screenshot-2017-12-28 smashing magazine for web designers and developers](https://user-images.githubusercontent.com/1981996/34414397-13c312cc-ec24-11e7-87de-931cc1a0313f.png)

**Comment by indysigner** [comment]
Right. There’s definitely something off here. Will look into it once we got some more critical issues out of the way, dear @leoloso. Thank you!
