### ISSUE TITLE
Detached "Hide talk details" button on London Conf page

### ISSUE THREAD

**Issue by dmgawel** [smashingmagazine/redesign#354]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Weird "Hide talk details" button appears on London Conf event page, near the "Select A Conference" switch. 

![hide-talk-details](https://user-images.githubusercontent.com/1322846/34212797-c298c964-e59d-11e7-96f4-79653fca58a8.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**

Enter https://www.smashingmagazine.com/events/london-2018/, its in the upper right corner.

**- What is the expected behavior?**

I suppose it should be somewhere else or should be hidden :-)

**- Please mention your operating system version and the version of your browser**

macOS Sierra, Chrome 62

**Comment by indysigner** [comment]
hi @dmgawel, many thanks for reporting this bug! A fix is on the way. Thank you! :-)
