### ISSUE TITLE
Duplicate content in article

### ISSUE THREAD

**Issue by chinchang** [smashingmagazine/redesign#356]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Duplicate content inside the article

**- If the current behavior is a bug, please provide the steps to reproduce.**
https://www.smashingmagazine.com/2017/09/building-inclusive-toggle-buttons

**- What is the expected behavior?**
No duplicate content.

**- Please mention your operating system version and the version of your browser**
Chrome on Mac osx.

**Comment by indysigner** [comment]
Hi @chinchang, thanks for reporting the issue, a fix is on the way!
