### ISSUE TITLE
Kinda ugly border on active link

### ISSUE THREAD

**Issue by Baysen** [smashingmagazine/redesign#357]
Just clicked a random link and saw this link border. Is this on purpose? I'm on Ubuntu Chrome 62. On Firefox 57 this looks a lot smoother. If this is on purpose, it looks... special :)
![activeborder](https://user-images.githubusercontent.com/8114313/34725529-822dd572-f551-11e7-9f36-67fb43938d59.png)

**Comment by indysigner** [comment]
This has been implemented by purpose, dear @RemizZ because of accessibility improvements.
