### ISSUE TITLE
Implement Web Share API

### ISSUE THREAD

**Issue by zcdunn** [smashingmagazine/redesign#358]
**- Do you want to request a *feature* or report a *bug*?**
Feature
The Web Share API would make it easy for users viewing the site in standalone mode (where the URL is unaccessible) to share a specific article. 
It can be feature detected so it only affects supporting browsers.
https://developers.google.com/web/updates/2016/09/navigator-share

**Comment by indysigner** [comment]
Hi @zcdunn,

Many thanks for your suggestion! While this is certainly interesting, it still is only being supported in Chrome Android (which make up only a small fraction of our readership), and it’s not even available in Chrome’s desktop versions (only as an experimental feature)... thus, we went for a more old school solution with no iframes or JavaScript required (using Twitter’s and Linkedin’s share URLs), like this:

![screenshot 2018-08-28 10 42 12](https://user-images.githubusercontent.com/4224281/44695708-6f69bf00-aaaf-11e8-82e0-ce246fb6b675.png)

So, this certainly might be interesting for the future, and once it’s coming to Chrome’s desktop  versions (we have a 75%+ user base reading Smashing in a Chrome browser). For now, let me close the issue, though. Thank you! 🙏
