### ISSUE TITLE
[Bug] Broken "Are you smashing, too?" button.

### ISSUE THREAD

**Issue by LukaszLabedzki** [smashingmagazine/redesign#359]
If you go to: https://www.smashingmagazine.com/2017/12/the-new-mystery-riddle-emoji-edition/ you can see that "Are you smashing, too?" button on the right is split by "Continue reading full screen" section. 

Viewed on latest Chrome, MacBook Pro

**Comment by indysigner** [comment]
Oh cool, thanks so much for the heads-up, dear @LukaszLabedzki. A fix is on the way.
