### ISSUE TITLE
Activating subscription via email takes me to smashing-magazine.netlify.com

### ISSUE THREAD

**Issue by anselmh** [smashingmagazine/redesign#36]
**- Do you want to request a *feature* or report a *bug*?**

Bug.

**- What is the current behavior?**

When clicking on the "activate" button in my membership confirmation email, I’m taken to `https://smashing-magazine.netlify.com/member/` instead of `https://next.smashingmagazine.com/member/`.

**Comment by vitalyfriedman** [comment]
Thanks @anselmh — will take care of it ;-)

**Comment by vitalyfriedman** [comment]
The issue has been resolved @anselmh — thanks for reporting it! :-)
