### ISSUE TITLE
Missleading slug for workshop

### ISSUE THREAD

**Issue by LukaszLabedzki** [smashingmagazine/redesign#360]
When you go to https://www.smashingmagazine.com/events/san-francisco-2018/#workshops-day-2 you can see Vitaly Friedman workshop called "New Front-End Adventures in Responsive Design" and it's URL is: https://www.smashingmagazine.com/workshops/new-front-end-adventures-in-responsive-design-london/ with london in it.

**Comment by indysigner** [comment]
Hi @LukaszLabedzki, many thanks for reporting the issue, I just deployed a fix! — Markus
