### ISSUE TITLE
Algolia is indexing also draft articles

### ISSUE THREAD

**Issue by leoloso** [smashingmagazine/redesign#361]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Algolia is showing articles not published yet, check the screenshot:

![screenshot-2018-1-31 articles](https://user-images.githubusercontent.com/1981996/35616547-82817360-06b0-11e8-9a3e-575be5d71c23.png)

**Comment by indysigner** [comment]
The issue has been fixed.
