### ISSUE TITLE
Site doesn't render correctly - at all - on FF Dev. Edition

### ISSUE THREAD

**Issue by trinaldi** [smashingmagazine/redesign#362]
[This is a screenshot](https://i.imgur.com/bgipRLq.png) of how the site renders -- without any add-ons or Privacy settings enabled on my `Firefox Developer Edition 59.0b5` using `Ubuntu 17.10`.

Well, the expected behavior is the one when I browse the site [using Chrome Version 65.0.3325.31 ](https://i.imgur.com/WL88emb.png)

The console doesn't show any errors, just a bunch of [debug info](https://i.imgur.com/Xya0OzB.png).

I really don't know what might be the issue, but I'm kinda disappointed that Web Devs are creating "Works best on Chrome" website nowadays (just a rant, I understand that's not the issue here)

Thanks

**Comment by indysigner** [comment]
Hi @trinaldi, many thanks for reporting the bug but I cannot replicate this behavior in my FF Dev Edition browser.... could you please try to flush the browser cache and try it again, @trinaldi? Thank you!

And BTW, we don't develop for Chrome only... ;-)

**Comment by trinaldi** [comment]
Hi @indysigner, thanks for your reply.

I'm also a developer and the first thing we tried is flushing the cache haha, but I did notice someting:
The issue might be related to the font rendering. As I tried to replicate the issue in my personal computer (`Arch LInux`), the site rendered perfectly (probably due a different `fontconfig` package?).

My Work notebook -- the one which doesn't render the site correctly -- is running `Ubuntu 17.10` with all default settings for the fonts. 

When I open the 'Inspector' and change the font from  `Mija` to the fallback `MijaInitial` the site renders somewhat correctly.

It might be a configuration issue, but one way to _try_ to replicate would be a vanilla Ubuntu machine. I'll check if `Hardware Acceleration` would be an issue, as well.

**Comment by indysigner** [comment]
Hi @trinaldi, many thanks for reporting the issue and sorry for the late reply! The issue should have been resolved in the meanwhile since we uploaded a new set of font files — can you please have a look and let me know if the problem still exists?

Thank you,

— Markus

**Comment by trinaldi** [comment]
Hi, @indysigner .

First of all, thanks for the feedback! Don't worry about being late, the important thing is that you showed up.

I can confirm that the site is [working as expected](https://i.imgur.com/dnnLp7k.png) now.

(Remember to remove the `console.log()` :) )

Thanks!
PS: I'm closing the issue, since this is not an issue.

**Comment by indysigner** [comment]
This is great to hear, thank you!
