### ISSUE TITLE
Staging is being indexed by Search Engines

### ISSUE THREAD

**Issue by leoloso** [smashingmagazine/redesign#365]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
I searched for myself in Duck Duck Go, and the results contained an entry to Smashing Magazine's Staging environment:

![screenshot-2018-3-16 leonardo losoviz at duckduckgo](https://user-images.githubusercontent.com/1981996/37503615-5b685b78-2914-11e8-99f6-5dddf610d453.png)

Apart from the fact that Staging should not be indexed, there is another problem: I clicked there and it seems to work fine, but comments in the articles do not load. A user coming from Duck Duck Go may be unaware this is not a Staging environment instead of the Live one, and think there are no comments whatsoever.

**- If the current behavior is a bug, please provide the steps to reproduce.**
[Search for "Leonardo Losoviz" in Duck Duck Go](https://duckduckgo.com/?q=leonardo+losoviz) (or anything else that will appear in Smashing Magazine) and scroll down, around the 20th result is the entry in the screenshot.

**- What is the expected behavior?**
Staging should not be indexed.

**Comment by indysigner** [comment]
Oh yeah, that’s a good point. We were closing staging in the meanwhile, so that should be fixed. Thank you! :-)
