### ISSUE TITLE
Spectrum teaser in Member dashboard broken above 2232 px viewport width

### ISSUE THREAD

**Issue by nilsmielke** [smashingmagazine/redesign#366]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
![bildschirmfoto 2018-03-20 um 09 38 06](https://user-images.githubusercontent.com/8496033/37644314-b170ab94-2c23-11e8-84ab-aa36e71d242a.png)

**- Please mention your operating system version and the version of your browser**
macOS 10.12.6, Chrome 65.0.3325.162

**Comment by indysigner** [comment]
Hi @nilsmielke, many thanks for reporting the issue and sorry for the late reply! The issue has been resolved in the meanwhile!
Thank you,

— Markus

![screenshot 2018-07-27 09 56 23](https://user-images.githubusercontent.com/4224281/43308917-706ffc7e-9183-11e8-872c-d88bfe77b6aa.png)
