### ISSUE TITLE
Superscript digits in the comments area

### ISSUE THREAD

**Issue by charakterziffer** [smashingmagazine/redesign#368]
I’d like to report a bug. In the comments section of the Smashing website some digits are superscript, see combined screenshot:

![superscript](https://user-images.githubusercontent.com/7194876/42247777-8959e6e6-7f22-11e8-9e0c-7f9b13ee29dd.png)

I think it affects 1, 2 and 3 of the font Mija and may be because of the css code
`.article__comments { font-feature-settings: "lnum" 1,"frac" 1,"sups" 1,"subs" 1; }`

The numbers should be 01 02 3 10 and 29 instead of 0¹ 0² ³ ¹0 and ²9.

I visited your website with Firefox 60 on Ubuntu Linux 16.04. Hopefully the bug reports in this repo are still watched.

**Comment by indysigner** [comment]
Hi @charakterziffer, many thanks for reporting the issue, I just deployed a fix!

Thank you,

— Markus
