### ISSUE TITLE
Image not showing

### ISSUE THREAD

**Issue by maliMirkec** [smashingmagazine/redesign#369]
**- Do you want to request a *feature* or report a *bug*?**

Bug.

**- What is the current behavior?**

Image not showing. 

[Printscreen](http://prntscr.com/kgzfyh)

**- If the current behavior is a bug, please provide the steps to reproduce.**

Open https://www.smashingmagazine.com/category/membership.

**- What is the expected behavior?**

To see an image.

**- Please mention your operating system version and the version of your browser**

macOS High Sierra 10.13.6, Version 68.0.3440.84 (Official Build) (64-bit).

**Comment by indysigner** [comment]
Hi @maliMirkec,

Many thanks for reporting the issue, I just deployed a fix!

Thank you,

— Markus
