### ISSUE TITLE
Ad-free Membership doesn’t mean tracking-free

### ISSUE THREAD

**Issue by anselmh** [smashingmagazine/redesign#37]
**- Do you want to request a *feature* or report a *bug*?**

Sort of in-between.

**- What is the current behavior?**

As an active paying member, I get an ad-free experience. However, I’m still being tracked by third-parties like hotjar (I personally am not but normal people will be). I’d be happy to upgrade to 5 or even 9$/mth plan if this would mean _no_ 3rd party tracking anymore.

**Comment by indysigner** [comment]
Good point! I already took off Hotjar since we wanted to implement it only temporarily anyway and to discover usability issues when users see the redesign for the first time. :-)
