### ISSUE TITLE
Can’t find "manage subscription" as paying member

### ISSUE THREAD

**Issue by anselmh** [smashingmagazine/redesign#38]
**- Do you want to request a *feature* or report a *bug*?**

Bug.

**- What is the current behavior?**

As paying member, I can find "account details" and "orders" but none of the links contains any information regarding my current membership (e.g. which plan I’m on) or an option to cancel my subscription.

**- What is the expected behavior?**

Have a clear way to cancel subscription or change the plan of the membership.

**Comment by vitalyfriedman** [comment]
Yes, indeed, we have to work through all the UX flows for Membership. Not done yet! @anselmh Will do :-)

**Comment by vitalyfriedman** [comment]
The issue has been resolved, @anselmh — please double check ;-)
