### ISSUE TITLE
Not enough articles are displayed

### ISSUE THREAD

**Issue by smash-it-on** [smashingmagazine/redesign#4]
Example --> Category: Usability: https://next.smashingmagazine.com/categories/usability/

It says that there are 111 articles related to that topic, but only 10 articles are displayed, and then the illustration of the sad cat at the bottom stating that there are no more articles. Kindly fix.

**Comment by vitalyfriedman** [comment]
Very good catch, the pagination is missing! Putting it on the TO-DO list! @smash-it-on

**Comment by smash-it-on** [comment]
@vitalyfriedman um, which to-do list? :D

**Comment by vitalyfriedman** [comment]
...to-do list for us to fix ;-)

**Comment by indysigner** [comment]
To be continued via https://github.com/smashingmagazine/smashing-magazine/issues/521
