### ISSUE TITLE
Illustrations overlap with text in Smashing Membership Pricing

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#41]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
In Smashing membership pricing (slider view), the text is overlapping with the illustrations on the right side. 

1600px viewport width:
![screen shot 2017-03-17 at 9 35 15 am](https://cloud.githubusercontent.com/assets/8038659/24033341/192cd164-0af5-11e7-8f7f-4d2b513d32e1.jpg)

2560px viewport width:
![screen shot 2017-03-17 at 9 30 21 am](https://cloud.githubusercontent.com/assets/8038659/24033224/884f5aa4-0af4-11e7-871d-6afc1386f0a5.jpg)

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to https://next.smashingmagazine.com/member/#
2. Click on slider view.
3. Navigate between the input range values.

**- What is the expected behavior?**

The illustration should not overlap with the text.

Kindly note that the issue happens for the prices ($3, $6, $9).

**- Please mention your operating system version and the version of your browser**
macOS Sierra, Version 57.0.2987.98, iMac 27" full screen width.

**Comment by vitalyfriedman** [comment]
Ouch! @shadeed Thanks Ahmad — will fix.
