### ISSUE TITLE
image/caption slightly cut-off on the right side

### ISSUE THREAD

**Issue by iamwebrocker** [smashingmagazine/redesign#42]
the image/caption portion that's offset to the right in the article is a tad bit too close to the browser's right side, so the last letter of a longer caption is cut off (see screenshot)
![img_0921](https://cloud.githubusercontent.com/assets/1223080/24033428/240367a4-0aed-11e7-93d5-c01465473501.PNG)
![img_0922](https://cloud.githubusercontent.com/assets/1223080/24033612/13f46402-0aee-11e7-95b1-dbc1cf9cc664.PNG)
[edit: added 2nd screenshot]

**- What is the expected behavior?**
long captions not cut-off on the right side

**- Please mention your operating system version and the version of your browser**
iOS 10.2.1, safari (normal mode, private mode, in-app mode)

**Comment by vitalyfriedman** [comment]
Very good catch, @iamwebrocker Tom — will fix! :-)
