### ISSUE TITLE
Keeping the comment area fixed when replying

### ISSUE THREAD

**Issue by vitalyfriedman** [smashingmagazine/redesign#43]
It would be way more comfortable to have the comment area floating on the right as the user keeps reading the article and/or comments. At this point it requires too much effort of going back and forth when replying to comments.

**Comment by vitalyfriedman** [comment]
![screen shot 2017-03-17 at 07 48 26](https://cloud.githubusercontent.com/assets/4688396/24033714/24ca46c8-0ae6-11e7-8c23-2b8a0617d38e.png)

**Comment by indysigner** [comment]
This issue already has been resolved. :-)
