### ISSUE TITLE
Shadow is clipped in the comment textarea

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#44]
**- Do you want to request a *feature* or report a *bug*?**

Bug.

**- What is the current behavior?**

The shadow looks weird when focusing the textarea for adding a comment. 
![screen shot 2017-03-17 at 9 53 57 am](https://cloud.githubusercontent.com/assets/8038659/24033926/e5aeeed2-0af7-11e7-8b36-0f5215354d7e.jpg)

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Go to an article.
2. Scroll down to the comments section.
3. Focus the textarea box.

**- What is the expected behavior?**
Shadow should not be clipped. 

![screen shot 2017-03-17 at 9 56 22 am](https://cloud.githubusercontent.com/assets/8038659/24033967/01a681c2-0af8-11e7-9171-b6089c199ded.jpg)

**- Please mention your operating system version and the version of your browser**
macOS Sierra, Version 57.0.2987.98.

**Comment by vitalyfriedman** [comment]
Good catch! It's indeed a bug! Will fix it! Thanks @shadeed — we'll fix it!

**Comment by vitalyfriedman** [comment]
Just fixed @shadeed — thanks for reporting the issue!
