### ISSUE TITLE
"Don’t Miss These Articles on Smashing" showing on top of search results

### ISSUE THREAD

**Issue by leoloso** [smashingmagazine/redesign#45]
Bug: searched "Head", scrolled down to see the results, and the message "Don’t Miss These Articles on Smashing" also appeared. Screenshot:

![image](https://cloud.githubusercontent.com/assets/1981996/24034117/fd6d7e48-0b2a-11e7-848a-ceb3c287d528.png)

System: 13" Macbook running Chrome, resolution 1440x900px

**Comment by vitalyfriedman** [comment]
Oh, it shouldn't be! We thought we fixed it. What version of Chrome are you running? The small-caps issues with the URL look weird, too. @leoloso

**Comment by leoloso** [comment]
Version 56.0.2924.87 (64-bit)

The small-caps does look weird, I thought it was a feature...
