### ISSUE TITLE
Styling of the focus state on .footer__topics__list

### ISSUE THREAD

**Issue by lukasholzer** [smashingmagazine/redesign#48]
**styling of focus state on .footer__topics__list**

The outline should not include the dot – heights of the `display: inline-block` are different.

<img width="912" alt="bildschirmfoto 2017-03-17 um 09 17 31" src="https://cloud.githubusercontent.com/assets/11156362/24034689/a84cfb2e-0af2-11e7-92cf-13d9cffaf7f3.png">

**Comment by vitalyfriedman** [comment]
Good catch, @lukasholzer — will fix.

**Comment by vitalyfriedman** [comment]
The issue has been fixed, @lukasholzer — thanks for reporting it!
