### ISSUE TITLE
The contact page is broken – 404

### ISSUE THREAD

**Issue by lukasholzer** [smashingmagazine/redesign#49]
# Contact page returns 404

**Request URL:** https://next.smashingmagazine.com/contact/
**Request Method:** GET
**Status Code:** 404  (from ServiceWorker)
**Remote Address:** 54.93.37.149:443

[Link to page](https://next.smashingmagazine.com/contact/)

**Comment by vitalyfriedman** [comment]
Thanks @lukasholzer — will fix! ;-)

**Comment by indysigner** [comment]
Working on it via https://github.com/smashingmagazine/smashing-magazine/issues/462 (private repository) — thanks so much for reporting it, @lukasholzer!
