### ISSUE TITLE
Missing image (WP ebook bundle)

### ISSUE THREAD

**Issue by smash-it-on** [smashingmagazine/redesign#5]
There's an image missing for the _The Wordpress Bundle (5 eBooks)_ which should be shown below the _Smashing Library_ over here: https://next.smashingmagazine.com/ebooks/ (and of course here too: https://next.smashingmagazine.com/ebooks/the-smashing-wordpress-bundle/)

![screen shot 2017-03-16 at 7 39 13 pm](https://cloud.githubusercontent.com/assets/26403660/24013068/7e059f3c-0a80-11e7-9d97-878d6ad42f51.png)

**Comment by indysigner** [comment]
In the works. :-)
