### ISSUE TITLE
Add article title to <title>

### ISSUE THREAD

**Issue by hudochenkov** [smashingmagazine/redesign#51]
**- Do you want to request a *feature* or report a *bug*?**
Please, add article title to `<title>`. 

**- What is the current behavior?**
Tabs is unrecognizable. This are three different articles:

![screen shot 2017-03-17 at 11 34 58](https://cloud.githubusercontent.com/assets/654597/24035288/0488e5f2-0b06-11e7-99d9-ee7e56066189.png)

**- What is the expected behavior?**
Article title in `<title>`.

**Comment by vitalyfriedman** [comment]
Ouch, @hudochenkov — we must have forgotten it! Will be done, of course :-)

**Comment by indysigner** [comment]
Done via https://github.com/smashingmagazine/smashing-magazine/pull/571 — thanks for reporting it, @hudochenkov!

**Comment by hudochenkov** [comment]
Fantastic! Thank you!
