### ISSUE TITLE
All conference event schedules date April 4 and April 5

### ISSUE THREAD

**Issue by nilsmielke** [smashingmagazine/redesign#52]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
The schedules of all conferences have the same dates: April 4 and April 5
![bildschirmfoto 2017-03-17 um 09 37 31](https://cloud.githubusercontent.com/assets/8496033/24035321/6c5dda36-0af5-11e7-87c3-e3e79bb20c7f.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Go to individual conference pages.

**- What is the expected behavior?**
Schedule dates meeting the conference dates. ;)

**- Please mention your operating system version and the version of your browser**
macOS 10.12.3, Safari 10.0.3

**Comment by vitalyfriedman** [comment]
Good catch! Will fix, @nilsmielke!
