### ISSUE TITLE
Article navigation item takes to me homepage

### ISSUE THREAD

**Issue by bigandy** [smashingmagazine/redesign#54]
As a user I want to access a list of all articles so when I click on "Articles" in the header I expect to be taken to /articles/ but I am taken to the homepage.

**Comment by vitalyfriedman** [comment]
Thanks @bigandy — will be looking into the issue!

**Comment by indysigner** [comment]
hi @bigandy, thanks for this suggestion, the article icon now leads to `/articles/`. Thank you!
