### ISSUE TITLE
Missing content in article

### ISSUE THREAD

**Issue by kouratoras** [smashingmagazine/redesign#55]
There is a bug related with the content of an article.

**Current behavior**
Navigating through some articles in new site, I've came across some one that is missing content. The article is:
https://next.smashingmagazine.com/2015/09/wordpress-management-with-wp-cli/
You can see that the article ends at the `Manipulate Data` section title.

**Expected behavior**
The page should have more content as you can see in the original page:
https://www.smashingmagazine.com/2015/09/wordpress-management-with-wp-cli/
You can see that there's a lot more after the `Manipulate Data` section title.

**Comment by vitalyfriedman** [comment]
Thanks @kouratoras — must be migration issues! We'll look into them, of course!

**Comment by indysigner** [comment]
Thanks for reporting! :-) We continue working on it via https://github.com/smashingmagazine/smashing-magazine/issues/563

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#597
