### ISSUE TITLE
Permalink font on search looks weird

### ISSUE THREAD

**Issue by KimBranzell** [smashingmagazine/redesign#56]
![Image of the font bug](http://i.imgur.com/etx0goz.png)

The permalink text looks a bit wonky (or is it supposed to look like that?) when you're using the search form. Pic is taken on MacOS Sierra 10.12.3, on Chrome 56.0.2924.87 (but I had the same result on Firefox 52, Safari 10.0.3 and Opera 43.0).

I've tried the font in question - Consolas - on other pages, but it works as expected there.

**Comment by vitalyfriedman** [comment]
Thanks @kimgoransson — must be related to OpenType features and small-caps. Will look into it!

**Comment by vitalyfriedman** [comment]
Is fixed now @kimgoransson — thanks for reporting the issue!
