### ISSUE TITLE
Incorrect markup generated for “Stylelint: The Style Sheet Linter We've Always Wanted” article

### ISSUE THREAD

**Issue by hudochenkov** [smashingmagazine/redesign#57]
**- Do you want to request a *feature* or report a *bug*?**
Bugs.

**- What is the current behavior?**
There're lots of issues with [Stylelint: The Style Sheet Linter We've Always Wanted](https://next.smashingmagazine.com/2016/05/stylelint-the-style-sheet-linter-weve-always-wanted/) article. They are mostly because of incorrect parsing and HTML generation.

### Incorrect line breaks:

![screen shot 2017-03-17 at 11 49 53](https://cloud.githubusercontent.com/assets/654597/24035763/efff6f8c-0b07-11e7-8b19-205f97afdcb0.png)
---
![screen shot 2017-03-17 at 11 50 01](https://cloud.githubusercontent.com/assets/654597/24035766/f001f1bc-0b07-11e7-9a5d-b553e127b544.png)
---
![screen shot 2017-03-17 at 11 50 06](https://cloud.githubusercontent.com/assets/654597/24035765/f001faae-0b07-11e7-9d6d-f19f104850b4.png)
---
![screen shot 2017-03-17 at 11 50 18](https://cloud.githubusercontent.com/assets/654597/24035764/f0007a6c-0b07-11e7-985b-9472c66ac487.png)

### Incorrect code snippets:

![screen shot 2017-03-17 at 11 51 52](https://cloud.githubusercontent.com/assets/654597/24035865/31f95240-0b08-11e7-9b74-81632bccd9ff.png)
![screen shot 2017-03-17 at 11 52 05](https://cloud.githubusercontent.com/assets/654597/24035864/31f8ec1a-0b08-11e7-8a11-432de5b285f5.png)
![screen shot 2017-03-17 at 11 52 14](https://cloud.githubusercontent.com/assets/654597/24035866/31fee264-0b08-11e7-8b83-74337e804cbe.png)

### Paragraphs isn't in `<p>` tags

![screen shot 2017-03-17 at 11 53 50](https://cloud.githubusercontent.com/assets/654597/24035914/792162c0-0b08-11e7-9d34-0061c587bc84.png)

### Magnified image smaller, than actual size

![image](https://cloud.githubusercontent.com/assets/654597/24035957/b10f98e6-0b08-11e7-84db-8e27993855f0.png)

### Code snippets are typographied (wrong quotes)

![image](https://cloud.githubusercontent.com/assets/654597/24036006/ded9968c-0b08-11e7-9f6b-8c269fd11009.png)

**Comment by vitalyfriedman** [comment]
Good catch, @hudochenkov! Must be a migration issue — on it!

**Comment by biilmann** [comment]
Looks like the same issue with pre blocks as #124

**Comment by indysigner** [comment]
To be continued at https://github.com/smashingmagazine/smashing-magazine/issues/563

**Comment by indysigner** [comment]
Resolved via https://migration-script-fixes--smashing-magazine.netlify.com/2016/05/stylelint-the-style-sheet-linter-weve-always-wanted/
