### ISSUE TITLE
Article Overview (IE11)

### ISSUE THREAD

**Issue by oemueller** [smashingmagazine/redesign#58]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Can't open Article Overview in IE11

**- If the current behavior is a bug, please provide the steps to reproduce.**
Go to https://next.smashingmagazine.com click "Articles"

**- What is the expected behavior?**
Overview is loaded

**- Please mention your operating system version and the version of your browser**
IE11, WIN7

**Comment by vitalyfriedman** [comment]
Thanks for reporting the issue! Could you submit a screenshot as well, @oemueller?

**Comment by oemueller** [comment]
Probably related to missing Promises on IE11:
![ie11-articles](https://cloud.githubusercontent.com/assets/351824/24092397/49e5b3e2-0d4e-11e7-9508-6d3128591ff0.png)

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#588
