### ISSUE TITLE
Updating personal details in account fails

### ISSUE THREAD

**Issue by nilsmielke** [smashingmagazine/redesign#59]
**- Do you want to request a *feature* or report a *bug*?**
Bug
**- What is the current behavior?**
Personal details do not save.
**- If the current behavior is a bug, please provide the steps to reproduce.**
After buying a subscription I tried updating my personal details. When clicking the save button, it says "Saving" and the wheel spins, but that never stops. Initiating a reload prompts a browser message, whether it should actually reload or not. After reloading the detail fields are empty again.
**- What is the expected behavior?**
Saving the details.
**- Please mention your operating system version and the version of your browser**
macOS 10.12.3, Safari 10.0.3 and Firefox 52.0 and Chrome 56.0.2924.87

**Comment by marcus-herrmann** [comment]
Console output of this bug

```
1.js:1 Uncaught TypeError: Cannot read property 'twitter' of undefined
    at Object.M.handleUpdatePersonalDetails [as onSave] (1.js:1)
    at t.value (1.js:6)
    at HTMLFormElement.w (app.js:1)
```

**Comment by vitalyfriedman** [comment]
Ouch! Thanks @marcus-herrmann — we'll get to it!

**Comment by vitalyfriedman** [comment]
Is fixed now @marcus-herrmann :-)
