### ISSUE TITLE
Javascript Promises Bug

### ISSUE THREAD

**Issue by oemueller** [smashingmagazine/redesign#60]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
JS Error: Promise is undefined

**- If the current behavior is a bug, please provide the steps to reproduce.**
https://next.smashingmagazine.com/

**- What is the expected behavior?**
Promises should work (with a Polyfill at least)

**- Please mention your operating system version and the version of your browser**
IE11 / WIN7

**Comment by vitalyfriedman** [comment]
Thanks @oemueller! We'll look into it.
