### ISSUE TITLE
No hover styles to distinguish between links in featured articles section.

### ISSUE THREAD

**Issue by carpenumidium** [smashingmagazine/redesign#61]
First of all, good job everyone, the new design looks splendid.

**- Do you want to request a *feature* or report a *bug*?**
In the homepage, add hover styles to distinguish between links in featured articles section.

**- What is the current behavior?**
Hovering my mouse over each featured article, I assumed clicking anywhere on the whole block would lead to the article but I accidentaly clicked on the author's name without looking at the browser's link description.

**Comment by vitalyfriedman** [comment]
Good catch! Well, the only area where you can NOT to straight to the article is the author's name. I think it's logical, wouldn't you agree @carpenumidium?

**Comment by carpenumidium** [comment]
> Well, the only area where you can NOT to straight to the article is the author's name. 

And the comments & tags too. 

I guess it's a personal preference? It just felt a tad confusing to have seamless links.

**Comment by indysigner** [comment]
Hi @carpenumidium, thanks for this suggestion / question. We indeed put quite some time into enabling users to click on Authors / Comments directly using nested links... so... allow me to close this issue since it's a desired behavior. Thank you.
