### ISSUE TITLE
Article tile click area bug

### ISSUE THREAD

**Issue by futekov** [smashingmagazine/redesign#62]
The selector `.article--grid__title a:before` has a wrong order of some of its properties, and some are duplicated:

```
    content: "";
    display: block;
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 0;
    width: calc(100% + 80px);
    height: calc(100% + 60px);
    height: 100%;
    padding: 30px 40px 0 40px;
    left: -40px;
    top: -30px;
    transition: background-color .1s ease-out;
    background-color: transparent;
```

The issues:

- `top` is found twice
- `left` is found twice
- `height` is found three times and in such a way, that the calc one will never get used (resulting in a smaller click area)

**Comment by vitalyfriedman** [comment]
Wow, good catch — on it @futekov!

**Comment by indysigner** [comment]
Oh dear.. this is indeed sub-ideal. A fix will be on the way in any moment. Thanks for reporting it!
