### ISSUE TITLE
site says I'm blocking ads while I'm not

### ISSUE THREAD

**Issue by Haroenv** [smashingmagazine/redesign#63]
**- Do you want to request a *feature* or report a *bug*?**

bug

**- What is the current behavior?**

![screen shot 2017-03-17 at 10 37 01](https://cloud.githubusercontent.com/assets/6270048/24037322/b107c504-0afd-11e7-8f57-c431aaf1a7e9.png)

Homepage reports that I have an ad blocker, but I don't 

**- If the current behavior is a bug, please provide the steps to reproduce.**

Go to the homepage with no ad blocker

**- What is the expected behavior?**

see ads

**- Please mention your operating system version and the version of your browser**

macOS 10.12, Safari 11 and Chrome 59

**Comment by vitalyfriedman** [comment]
Weird. Are you using any privacy extensions? Not sure why you're seeing this! We'll look into it though! Thanks @Haroenv!

**Comment by Haroenv** [comment]
I just noticed that I do get the ad just below the message, both in Chrome and Safari. 

Safari has these extensions: 

<img width="200" alt="screen shot 2017-03-19 at 00 04 31" src="https://cloud.githubusercontent.com/assets/6270048/24076704/d1ec0d12-0c37-11e7-856e-4f831dbf5d8d.png">

FF (dev edition) also shows the message, and it doesn’t have any extensions at all, also showing the ad, like in the others.

**Comment by indysigner** [comment]
Hi @Haroenv, thanks for reporting this. We have fixed the issue in the meanwhile. Thank you.

**Comment by Haroenv** [comment]
yep, was fixed meanwhile!
