### ISSUE TITLE
Hot Topic articles wrong icons?

### ISSUE THREAD

**Issue by nachtfunke** [smashingmagazine/redesign#64]
_This is technically not a bug, rather a proposed improvement_

In the [Hot Topic-Section](https://next.smashingmagazine.com/#hot-topics), the Icon choice seems a bit odd. The reading-time uses a calendar icon, and the comments-count uses a leaf. Maybe using something more meaningful would be a better choice?

![screen shot 2017-03-17 at 11 00 41](https://cloud.githubusercontent.com/assets/4201323/24038272/02f3494e-0b01-11e7-9b44-6f40b266234e.png)

**Comment by vitalyfriedman** [comment]
Good question, @nachtfunke — we will look into it. Any suggestions? ;-)

**Comment by indysigner** [comment]
Hi @nachtfunke, we have removed the panel for now... many thanks for reporting it! And happy holidays!
