### ISSUE TITLE
Not able to reply to some comments

### ISSUE THREAD

**Issue by vinujosef** [smashingmagazine/redesign#65]
**- I want to report a bug

**- In the comments sections of the article https://next.smashingmagazine.com/2017/03/web-development-reading-list-173/ , we have 4 comments at the moment.

![image](https://cloud.githubusercontent.com/assets/15977266/24039349/1b899234-0b05-11e7-9098-5f7659a920cf.png)

It is possible to reply to the first and the last comment. But on clicking "Reply" for the second and the third comment, no action is fired i.e @username is not coming in the comments box

**- To reproduce the bug:
      > go to the link https://next.smashingmagazine.com/2017/03/web-development-reading-list-173/ 
      > navigate to the comments section
      > click on the second or the third comment and notice no event is getting fired

**- I am using Window 10 + Latest Google Chrome

**Comment by vitalyfriedman** [comment]
Good catch, @vinujosef — will fix! :)
