### ISSUE TITLE
A few bugs, or is it intentional?

### ISSUE THREAD

**Issue by ahmadawais** [smashingmagazine/redesign#67]
**- Do you want to request a *feature* or report a *bug*?**
Bug
**- What is the current behavior?**
The accessibility features look weird. https://i.imgur.com/kjL68tF.png
**- If the current behavior is a bug, please provide the steps to reproduce.**

**- Please mention your operating system version and the version of your browser**
Mac OS Chrome :)

**Comment by vitalyfriedman** [comment]
That's a bit strange. In which article did you spot it @ahmadawais? Couldn't reproduce it.

**Comment by vitalyfriedman** [comment]
![kjl68tf](https://cloud.githubusercontent.com/assets/4688396/24076676/a0c5fae4-0c2e-11e7-8b48-cda2fcba71df.png)

**Comment by ahmadawais** [comment]
Every where on the site. Even on landing pages when I clicked a button or
when scrolled down button was clicked the whole section was like this not
juat the link.

**Comment by vitalyfriedman** [comment]
So far we're going with this indeed. Outline for tabbing, red background for selecting.
