### ISSUE TITLE
Discount link to membership page is incorrect

### ISSUE THREAD

**Issue by smash-it-on** [smashingmagazine/redesign#7]
The link in the following text should be changed (please see https://next.smashingmagazine.com/events/san-francisco-2017/):

_Get 10% discounts off all tickets with a Smashing Membership._

"Smashing Membership" links to "dashboard" on the site (whatever that is, lol).

**Comment by pukhalski** [comment]
Dear @smash-it-on, thanks for your feedback. This issue is fixed now.

https://next.smashingmagazine.com/events/san-francisco-2017/

**Comment by smash-it-on** [comment]
@pukhalski ah, found the same issue when you scroll down a bit, where it says "Get Your Ticket!" — the link to the Smashing Membership should be added: _Ah, tickets are cheaper with a *Smashing Membership*, you know._ 

Thanks in advance :o)

**Comment by vitalyfriedman** [comment]
_Booo-yah!_ Fixed. Coming up with the next pull request. Thanks @smash-it-on
