### ISSUE TITLE
The shadows on the avatars disappear too quickly.

### ISSUE THREAD

**Issue by andyfitch** [smashingmagazine/redesign#70]
This is a very small visual oddity/bug – when you hover over an avatar, the shadow disappears much too quickly. It's more apparent on the larger avatars at the top of news articles.

Steps to reproduce:
- Hover over an avatar

Expected behaviour:
- Shadow to disappear at relative rate to the avatar movement (I realise it's not exactly relative as the shadow is getting smaller, whereas the avatar is just moving, but it's still slightly off.
- The main navigation items seem to disappear at the appropriate rate, however.

Actual behaviour:
- Shadows disappear very quickly

Chrome on desktop

**Comment by vitalyfriedman** [comment]
Unfortunately, we weren't able to make it better due to CSS limitations. Will look into the issue again though! @andyfitch
