### ISSUE TITLE
Mixed Content in Job Board

### ISSUE THREAD

**Issue by Marabyte** [smashingmagazine/redesign#71]
**- Do you want to request a *feature* or report a *bug*?**
It's a bug

**- What is the current behavior?**
A couple of images are being served through HTTP, ie:
http://jobs.smashingmagazine.com/logos/0000/9157/logo_diva-e-facebook_small.png
http://jobs.smashingmagazine.com/logos/0000/9161/foxcommerce_-_small_logo_480_small.jpg

**- If the current behavior is a bug, please provide the steps to reproduce.**
Go to https://next.smashingmagazine.com/jobs/, check the console.
Most thumbnails don't show any image. 
Grey HTTPS icon on URL bar

**- What is the expected behavior?**
Images should be loading.

**- Please mention your operating system version and the version of your browser**
macOS 10.11.6 - Chrome 57, Firefox 52

**Comment by vitalyfriedman** [comment]
Good catch — will fix, @Marabyte!

**Comment by indysigner** [comment]
Hi @Marabyte, we have resolved this issue, many thanks for reporting it! And happy holidays!
