### ISSUE TITLE
&nbsp; appearing in form validation

### ISSUE THREAD

**Issue by andyfitch** [smashingmagazine/redesign#72]
<img width="464" alt="screen shot 2017-03-17 at 11 39 45" src="https://cloud.githubusercontent.com/assets/265406/24041696/798c349e-0b06-11e7-99ce-42c29243769e.png">

Expected behaviour:
- Actual space to appear instead of &nbsp;

Actual behaviour:
- &nbsp; appears

Chrome on desktop

**Comment by vitalyfriedman** [comment]
Should be fixed now @andyfitch — thanks!
