### ISSUE TITLE
Flash of empty space when hovering over individual speakers

### ISSUE THREAD

**Issue by andyfitch** [smashingmagazine/redesign#73]
Flash of empty space when hovering over individual speakers whilst it loads in. Fine if repeating once it's loaded.

https://next.smashingmagazine.com/events/san-francisco-2017/

Expected behaviour:
- Prefetched content would ensure the hover image is ready before hover, rather than loading it on hover.

Actual behaviour:
- Flash of empty space whilst content loads behind the scenes

Latest Chrome on desktop

**Comment by vitalyfriedman** [comment]
Should be fixed now actually — could you add a video? Can't replicate the issue on Chrome! @andyfitch

**Comment by vitalyfriedman** [comment]
Can you please fix it, @indysigner — we know the trick ;-)

**Comment by indysigner** [comment]
Issue fixed on staging. Thanks for reporting it!
