### ISSUE TITLE
No message when no jobs found for a particular category

### ISSUE THREAD

**Issue by andyfitch** [smashingmagazine/redesign#74]
<img width="1525" alt="screen shot 2017-03-17 at 11 45 37" src="https://cloud.githubusercontent.com/assets/265406/24041881/4fd2e0d4-0b07-11e7-8961-a52138fe15ed.png">

Expected behaviour:
- Message displayed saying something to the effect 'No programming jobs available'

Actual behaviour:
- When no jobs are found for a particular category, there is just empty space.

Latest Chrome on desktop

**Comment by vitalyfriedman** [comment]
Good catch — will fix! @andyfitch

**Comment by indysigner** [comment]
Hi @andyfitch, we have resolved this issue, many thanks for reporting it! And happy holidays!
