### ISSUE TITLE
Handle Failed Promises in service worker

### ISSUE THREAD

**Issue by Marabyte** [smashingmagazine/redesign#75]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
If a service worker fail to retrieve an image (see #71) the rejected promise is not handled

**- If the current behavior is a bug, please provide the steps to reproduce.**
Open  https://next.smashingmagazine.com/jobs/

**- What is the expected behavior?**
If for some reason the image failed to be retrieved the promise could do something to enhance the user experience, ie: load a default placeholder instead showing and empty thumbnail in the Job Board.

**- Please mention your operating system version and the version of your browser**
macOS 10.11.6 - Chrome 57

**Comment by vitalyfriedman** [comment]
Thanks @Marabyte — on it!

**Comment by vitalyfriedman** [comment]
@pukhalski Has the issue been resolved? ;-)

**Comment by indysigner** [comment]
Hi @Marabyte, we have resolved this issue, many thanks for reporting it! And happy holidays!
