### ISSUE TITLE
Shopping Cart Clipped Content

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#77]
**- Do you want to request a *feature* or report a *bug*?**

Bug.

**- What is the current behavior?**

Checkout button content is clipped.

![screen shot 2017-03-17 at 2 45 42 pm](https://cloud.githubusercontent.com/assets/8038659/24043798/0acc12de-0b21-11e7-9399-39c27d1031ca.jpg)

I played a bit with `min-height`, it supposed to be like this:

![screen shot 2017-03-17 at 2 49 56 pm](https://cloud.githubusercontent.com/assets/8038659/24043811/218cbdc0-0b21-11e7-80b0-bc2c605a11f0.jpg)

Maybe to make the cart full screen? since it's a bit annoying to scroll in this small vertical area for mobile users.

Also, "clear the cart" button is looking like a tab. At first, I thought that we have 2 tabs and "clear the cart" is active (before reading the text). I suggest pushing that clear button to a new line.

**- Please mention your operating system version and the version of your browser**

Latest Chrome on OSX.

**Comment by vitalyfriedman** [comment]
Very good point! Making the cart full screen sounds like a great idea — will look into it! @shadeed
