### ISSUE TITLE
Password placeholder is overlapping with "Show" button

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#78]
**- Do you want to request a *feature* or report a *bug*?**

Bug.

**- What is the current behavior?**

Placeholder text is overlapping with "Show" button.
![screen shot 2017-03-17 at 2 54 55 pm](https://cloud.githubusercontent.com/assets/8038659/24043979/dcacf71e-0b21-11e7-84e8-1cfa8a53e0db.jpg)

**- Please mention your operating system version and the version of your browser**

Latest Chrome on OSX.

**Update**

The email input has a weird text wrapping issue on Safari iOS10.

![img_9093](https://cloud.githubusercontent.com/assets/8038659/24044463/0691fb68-0b24-11e7-9b33-8f2e72d14dd2.PNG)

**Comment by vitalyfriedman** [comment]
Issue accepted @shadeed.
