### ISSUE TITLE
Shopping cart button is overlapping the jobs fixed bar

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#79]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**

Browsing jobs listing on mobile with some items added to the cart will make it overlap the fixed bar.

![screen shot 2017-03-17 at 2 56 51 pm](https://cloud.githubusercontent.com/assets/8038659/24044035/10bab26c-0b22-11e7-8a02-7644c7f61d8a.jpg)
<!--

**- Please mention your operating system version and the version of your browser**

Latest Chrome on OSX.

**Comment by vitalyfriedman** [comment]
Issue accepted.

**Comment by indysigner** [comment]
Hi @shadeed, Many thanks for reporting the bug. We’ve fixed the issue in the meanwhile so I'm closing it. Thank you.
