### ISSUE TITLE
Link to newsletter missing

### ISSUE THREAD

**Issue by smash-it-on** [smashingmagazine/redesign#8]
Please add the link to the newsletter page (see screenshot) — currently leads to #.

![screen shot 2017-03-16 at 7 51 34 pm](https://cloud.githubusercontent.com/assets/26403660/24013538/0ac56cd0-0a82-11e7-9976-e42bee33a9de.png)

**Comment by vitalyfriedman** [comment]
Good catch! Please set up a Newsletter page, @biilmann @pukhalski @indysigner.
