### ISSUE TITLE
Jobs receipt edges looks weird

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#81]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
The receipt edges looks clipped/weird.

**- What is the expected behavior?**
Edges should be without clipping.

**- Please mention your operating system version and the version of your browser**
Safari on iOS10.

![img_9096](https://cloud.githubusercontent.com/assets/8038659/24044304/6da2146a-0b23-11e7-90e3-d35f4f07d195.PNG)
<!--

**Comment by vitalyfriedman** [comment]
Well spotted, @shadeed — we will look into it :-)

**Comment by indysigner** [comment]
Hi @shadeed, we have refined the virtual receipt, many thanks for reporting it!
