### ISSUE TITLE
read-more-link focus border is sometimes broken

### ISSUE THREAD

**Issue by IOIIOOIO** [smashingmagazine/redesign#82]
**- Do you want to request a *feature* or report a *bug*?**
Report a bug

**- What is the current behavior?**
Sometimes part of the focus border on the read-more-link us missing, or the link itself is not properly aligned. Screenshots attached.
![untitled-1](https://cloud.githubusercontent.com/assets/10476760/24044719/32634a02-0b25-11e7-9c4a-d4292814607a.jpg)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Click on a "Read More" link to show the focus border

**- What is the expected behavior?**
That the link is aligned consistently and that the whole focus border is visible

**- Please mention your operating system version and the version of your browser**

Windows 8.1
Chrome Version 56.0.2924.87
Resolution: 1920x1080

**Comment by vitalyfriedman** [comment]
Good catch, @IOIIOOIO — will look into it — thank you!

**Comment by vitalyfriedman** [comment]
The wrapping issue has been resolved, thanks @IOIIOOIO :-)
