### ISSUE TITLE
Broken &nbsp; in comment error message 

### ISSUE THREAD

**Issue by wanecek** [smashingmagazine/redesign#83]
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
When trying to submit an empty comment, the error message provided includes a non-encoded html-entity.
![image](https://cloud.githubusercontent.com/assets/1533747/24045234/a7ed1dc2-0b1e-11e7-85f2-b518f388fd9a.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Press "Submit Comment" without entering anything into the comment field, and check the error message.

**- What is the expected behavior?**
The &nbsp; should be properly encoded, and insert a non-breaking space instead of being rendered as text.

**- Please mention your operating system version and the version of your browser**
Windows 10
Chrome 56.0.2924.87 (64-bit) - Swedish

Also, the new site is amazing in all aspects. I appreciate all the hard work and talent that has gone into this rebuild. **Well done!**

**Comment by vitalyfriedman** [comment]
Fantastic — issue should be resolved now! @wanecek
