### ISSUE TITLE
To have a better right space for the accordion toggle

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#84]
**- Do you want to request a *feature* or report a *bug*?**
None! An enhancement :D 

**- What is the current behavior?**
"Amazon" word is almost overlapping with the plus icon.

![screen shot 2017-03-17 at 3 36 28 pm](https://cloud.githubusercontent.com/assets/8038659/24045374/8c77d93e-0b27-11e7-97c7-e53e8ba441a2.jpg)

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Open https://next.smashingmagazine.com/ebooks/
2. Browse on mobile mode.

**- What is the expected behavior?**
More right space by increasing `padding-right` value.

![screen shot 2017-03-17 at 3 38 12 pm](https://cloud.githubusercontent.com/assets/8038659/24045440/cffb2d5a-0b27-11e7-9c0e-678219814f10.jpg)

**- Please mention your operating system version and the version of your browser**
Latest Chrome on OSX.

**Comment by vitalyfriedman** [comment]
Thank you again, @shadeed — we'll get to it ;-)

**Comment by indysigner** [comment]
hi @shadeed, we have resolved the issue. Thanks for reporting it!
