### ISSUE TITLE
Link "Report this error using our contact form" in the 404 page is broken

### ISSUE THREAD

**Issue by leoloso** [smashingmagazine/redesign#86]
Bug: It seems the link "contact form" is just pointing to /styleguide/contact/ but missing the domain, so clicking there produces a 404.

1. To reproduce it: go to any non-existing URL, eg: https://next.smashingmagazine.com/pedro/
2. The link "contact form" is pointing to https://next.smashingmagazine.com/pedro/styleguide/pedro/

Screenshot (mouse cursor is hovering on link "contact form"):

![image](https://cloud.githubusercontent.com/assets/1981996/24046481/a87eeb64-0b5d-11e7-92ba-9d4192e8bd65.png)

**Comment by vitalyfriedman** [comment]
Ouch! Thank you very much for reporting the issue, @leoloso — @indysigner @biilmann please fix.

**Comment by indysigner** [comment]
This has been fixed in the meanwhile. Thanks for the heads-up, dear @leoloso!
