### ISSUE TITLE
New paragraph midway through a sentence

### ISSUE THREAD

**Issue by IOIIOOIO** [smashingmagazine/redesign#87]
**- Do you want to request a *feature* or report a *bug*?**
Report a bug

**- What is the current behavior?**
There is a new paragraph midway through a sentence

**- If the current behavior is a bug, please provide the steps to reproduce.**
Best I can offer is to navigate to this section and take note the sentence "What happens when the primary property is set is an implementation detail":
https://next.smashingmagazine.com/2017/01/styled-components-enforcing-best-practices-component-based-systems/#build-small-components 

I have also attached a screenshot.

![untitled-2](https://cloud.githubusercontent.com/assets/10476760/24046559/99d8939e-0b2b-11e7-91f4-2e0c3daa3f00.jpg)

**- What is the expected behavior?**
The sentence should continue on the same line and not start on anew paragraph mid-sentence.

**- Please mention your operating system version and the version of your browser**
Windows 8.1
Chrome Version 56.0.2924.87

**Comment by vitalyfriedman** [comment]
Ouch — must be a migration issue! @indysigner — please fix.

**Comment by vitalyfriedman** [comment]
Migration issues — fixed now! @IOIIOOIO
