### ISSUE TITLE
My Experience on the new Re-design

### ISSUE THREAD

**Issue by webmansa** [smashingmagazine/redesign#89]
Hi Team,
Frankly not a fan of the new re-design ,its look too busy not much white space around everything look so obfuscated.  "personal opinion" please keep the old re-design.
Best,
S.

**- Do you want to request a *feature* or report a *bug*?**

**- What is the current behavior?**

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

**- Please mention your operating system version and the version of your browser**

**Comment by vitalyfriedman** [comment]
Thanks for your opinion, @sesay — we'll see what we can do to make it better.
