### ISSUE TITLE
Author bio contact links incorrect 

### ISSUE THREAD

**Issue by smash-it-on** [smashingmagazine/redesign#9]
Example: https://next.smashingmagazine.com/author/veerle-pieters/

Links to author's Twitter and Github profiles, as well as her website do not have appropriate links. This is the case for all authors.

![screen shot 2017-03-16 at 7 53 35 pm](https://cloud.githubusercontent.com/assets/26403660/24013671/7e242c02-0a82-11e7-95f4-c51bee5a9343.png)

**Comment by indysigner** [comment]
Seems to be working fine with you example link @smash-it-on?

**Comment by vitalyfriedman** [comment]
Has been fixed.
