### ISSUE TITLE
The whole page view on mobile IE

### ISSUE THREAD

**Issue by victory-v** [smashingmagazine/redesign#90]
**- Do you want to request a feature or report a bug?**
Bug

**- What is the current behavior?**
I'm sorry, but the main page looks like a nightmare (see on the screenshot)
![q_hcfwfwxdo](https://cloud.githubusercontent.com/assets/13104389/24047149/ef0fc6d4-0b35-11e7-811a-f645afde7c2a.jpg)
![0acooztl8pe](https://cloud.githubusercontent.com/assets/13104389/24047133/df306070-0b35-11e7-9407-3a32ac32aa88.jpg)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Just open the page

**- Please mention your operating system version and the version of your browser**
Windows Phone 8.1, browser Internet Explorer.

**Comment by vitalyfriedman** [comment]
Ouch, dear @victory-v — what version of Internet Explorer are you using? We'll see what we can do!

**Comment by victory-v** [comment]
It's IE 11, I think (this stupid browser doesn't show its version :))
I know that my phone and the browser are neither new nor popular, but I've never have such problems with other web-sites, so this bug is strange.

**Comment by indysigner** [comment]
This issue was moved to smashingmagazine/smashing-magazine#587
