### ISSUE TITLE
Reflow flashes 

### ISSUE THREAD

**Issue by scottmas** [smashingmagazine/redesign#93]
This is especially obvious on https://next.smashingmagazine.com/member/ but also to a limited extent on other pages, but some pages feels jumpy on load. An image loads and then a split second later gets replaced by text. Or for instance on the job board, there's a almost imperceptible resize of the top job post a split second after load.

**Comment by vitalyfriedman** [comment]
Thanks @scottmas — the bug accepted.

**Comment by vitalyfriedman** [comment]
Made quite an effort to reduce noise across the site. Thanks so much for reporting it, @scottmas!
