### ISSUE TITLE
Flash/jank transitioning from default to external web font

### ISSUE THREAD

**Issue by scottmas** [smashingmagazine/redesign#94]
I applaud your thinking on loading a default web font before your actual font has loaded, but it just feels janky to have the entire page reflow when the actual font loads. This is especially apparent on the jobs page. 

As a user I would much prefer to have the entire page defer loading until the actual font has loaded, rather than have to suffer a flash of reflowing content.

**Comment by vitalyfriedman** [comment]
Thanks @scottmas — we are looking into web font loading as we speak. Please stay tuned.

**Comment by biilmann** [comment]
Seems like this is an issue in Safari since we currently depend on Service Worker to avoid the flash of unstyled text on repeat views. I'll make sure to get a fallback to session storage in place for browsers with no Service Worker support

**Comment by vitalyfriedman** [comment]
Sounds fantastic, Mathias! Should we look into using localstorage instead of sessionstorage? Overall, it's probably a good idea to test how fast the fonts start render with a service worker in place.

Vitaly

**Comment by vitalyfriedman** [comment]
The issue has been resolved @scottmas :-)
