### ISSUE TITLE
Selecting text on start of article

### ISSUE THREAD

**Issue by whmii** [smashingmagazine/redesign#95]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
The beginning of an article is very difficult to select

**- If the current behavior is a bug, please provide the steps to reproduce.**
`col--article-head` overlays the start of `article__content` due to the z index and positioning. This causes the initial text of the article to be almost unselectable. I have attached a GIF of the behavior.

![moo](https://cloud.githubusercontent.com/assets/2489247/24048786/51b8246a-0b00-11e7-8c8e-2c1d94f82346.gif)

**- What is the expected behavior?**

One should be able to click on the text to select it.

**- Please mention your operating system version and the version of your browser**

Using latest chrome on mac

**Comment by shadeed** [comment]
A possible duplication of #22 ?

**Comment by whmii** [comment]
@shadeed ah, my bad. I looked through the issues but I guess I missed that one.

**Closing as duplicate to https://github.com/smashingmagazine/redesign/issues/22**
