### ISSUE TITLE
Beginning of article is really hard to identify

### ISSUE THREAD

**Issue by dfosco** [smashingmagazine/redesign#96]
**Desktop View**
![image](https://cloud.githubusercontent.com/assets/3229933/24049964/43eaf57c-0b0c-11e7-9768-38cf1b78d99b.png)

**Mobile View**
![image](https://cloud.githubusercontent.com/assets/3229933/24050390/7643e1ae-0b0d-11e7-890d-e48fd8c536c5.png)

Feature? Not sure, but I'm submitting anyway

The reading order for the article page is currently **really** hard to figure out — I was 100% sure the text started on “Therefore, we think that...” and completely missed the quick summary.

Placing the summary in this layout makes it seem like an optional **TL;DR**, instead of the first paragraph of the article that's necessary to start reading.

The mobile view is even worse, _actually hiding_ the first paragraph of the article inside an accordion :scream:

**Comment by vitalyfriedman** [comment]
Ouch @dfosco — must have been a migration issue. Not sure why the first paragraph is hidden here. We will look into it!

**Comment by biilmann** [comment]
Not sure about this one, the version of the article right now starts with:

`As JavaScript developers, we often forget that not everyone has the same knowledge as us.`

https://next.smashingmagazine.com/2017/02/designing-html-apis/

**Comment by dfosco** [comment]
The summary is now part of the text — that was most likely a migration issue, as Vitaly said.

I still think the reading order is confusing, however. You don't need to be as stoic as Medium, but there's still plenty of unnecessary zig-zagging... this might be the subject for another issue, though 🙂

![smashing](https://cloud.githubusercontent.com/assets/3229933/24107774/6e371440-0d6a-11e7-8669-119786105a70.png)

**Comment by vitalyfriedman** [comment]
We did make some changes, especially on mobile. Thanks for reporting it @dfosco! :-)
