### ISSUE TITLE
Table of contents ignores article introduction

### ISSUE THREAD

**Issue by dfosco** [smashingmagazine/redesign#97]
![image](https://cloud.githubusercontent.com/assets/3229933/24050480/b04c5aac-0b0d-11e7-934a-6dc4258027c5.png)

Maybe this is intentional, or maybe it's even an error on whoever edited the article in your CMS, but it's really weird to have a table of contents and the introduction to the article not be listed in it — you click in the first section and it just... skips a bunch of text.

Might not be an issue for you folks, but I found it super weird.

Found [here](https://next.smashingmagazine.com/2017/02/designing-html-apis/#markapp-a-list-of-libraries-with-html-apis)

**Comment by vitalyfriedman** [comment]
That's a quite interesting issue to consider. The table of contents displays all headings and since there is no heading in the introduction, should it be added to the ToC? Not sure. Worth considering though! Thanks @dfosco

**Comment by indysigner** [comment]
Agreed, this really is a content issue since the TOC is being generated from the headers. Thanks for reporting it, @dfosco!
