### ISSUE TITLE
Mobile menu button flashing text and icon

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#98]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
Opening the site on a mobile will cause the mobile menu button to flash in a weird way. The search icon is pushed down and once the fonts finish loading, it will move to it's expected place. 

![smash-mag-menu](https://cloud.githubusercontent.com/assets/8038659/24051441/c093bef0-0b3a-11e7-944d-40398a97b4f1.gif)

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Use a mobile browser.
2. Open any page.

**- What is the expected behavior?**
Due to the fact of using `inline-block` for the button, this is the cause of the issue. We need to prevent that by adding `min-width` to the button so the icon won't move down at first load.

**- Please mention your operating system version and the version of your browser**
Latest Chrome on iOS.

**Comment by vitalyfriedman** [comment]
Good catch — we'll be working on it, @shadeed!

**Comment by vitalyfriedman** [comment]
Should be fixed now, @shadeed! Thanks for reporting it!
