### ISSUE TITLE
Live search doesn't work on mobile breakpoint

### ISSUE THREAD

**Issue by ziozec-zz** [smashingmagazine/redesign#99]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
Live search doesn't work on mobile breakpoint

**- If the current behavior is a bug, please provide the steps to reproduce.**
Try live search on mobile version

**- What is the expected behavior?**
To show the live results as on desktop

**- Please mention your operating system version and the version of your browser**
Chrome/Safari Mac

**Comment by vitalyfriedman** [comment]
Thanks @ziozec — we will be looking into it!
